(()=>{'use strict';
 const make=(tag,parent,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;parent.append(n);return n;};
 window.SirenPresentationAuthoring=Object.freeze({create({host,diagramFor,editable,onEdit,onStatus,onPlay}){
  let selected=null,page=0,signature='',disposed=false;
  const write=op=>{if(disposed||!editable())return false;const result=onEdit(op);if(!result.ok){onStatus('Presentation edit refused. Imported data is retained; save accepted changes before adding more steps.');return false;}return true;};
  function paint(force=false){
   if(disposed||host.hidden)return;for(const field of host.querySelectorAll('[data-deck-write]'))field.disabled=!editable();const diagram=diagramFor();if(!diagram)return;const value=diagram.presentation??{},entries=value.sequence??[];if(!Array.isArray(entries)||entries.length>600){host.replaceChildren();make('p',host,'This imported deck exceeds the editing limit. Its content is retained.');return;}
   // Keep the focused control and pointer target alive throughout input/blur.
   // Rebuilding on blur can retire a button between pointer-down and click.
   if(!force&&host.contains(document.activeElement)){for(const b of host.querySelectorAll('[data-deck-step]')){const i=entries.findIndex(v=>v.id===b.dataset.deckStep),entry=entries[i];if(entry)b.textContent=(i+1)+'. '+(entry.title||entry.card?.title||entry.nodeId||entry.type||'Imported step');}const current=entries.find(v=>v.id===selected),title=host.querySelector('#presentationStepEditor h3');if(current&&title)title.textContent=current.title||current.card?.title||current.nodeId||'Presentation step';return;}const next=JSON.stringify(value)+':'+editable()+':'+selected+':'+page;if(!force&&next===signature)return;signature=next;host.replaceChildren();
   make('h2',host,'Presentation');make('p',host,'Order the story, add content and prepare private notes. Save commits the deck and diagram together.').className='diagram-note';const tools=make('div',host);tools.className='deck-tools';
   const action=(parent,title,run,writeOnly=true)=>{const b=make('button',parent,title);b.type='button';if(writeOnly){b.dataset.deckWrite='true';b.disabled=!editable();}b.addEventListener('click',()=>{if(disposed||writeOnly&&!editable())return;run();});return b;};
   for(const [kind,title]of [['overview','+ Overview'],['title','+ Title'],['text','+ Text']]){const b=action(tools,title,()=>{const id=crypto.randomUUID();if(write({action:'add',id,kind})){selected=id;page=Math.floor((diagramFor().presentation.sequence.length-1)/40);paint(true);}});b.dataset.deckAdd=kind;b.disabled=!editable()||entries.length>=600;}
   const node=make('details',tools);make('summary',node,'+ Diagram block');const nodeId=make('input',node);nodeId.maxLength=80;nodeId.placeholder='Mermaid block ID, for example A';nodeId.setAttribute('aria-label','Mermaid block ID');nodeId.dataset.deckWrite='true';nodeId.disabled=!editable();action(node,'Add block',()=>{const id=crypto.randomUUID();if(write({action:'add',id,kind:'node',nodeId:nodeId.value.trim()})){selected=id;page=Math.floor((diagramFor().presentation.sequence.length-1)/40);paint(true);}});
   const play=action(tools,'Save & present',()=>void onPlay(),false);play.id='presentSavedDeck';play.disabled=!editable();play.title='Save local diagram/deck, then open the saved version in Presenter';
   const layout=make('div',host);layout.className='deck-layout';const sidebar=make('nav',layout);sidebar.setAttribute('aria-label','Presentation steps');const items=make('div',sidebar);items.className='deck-list';page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(entries.length/40)-1)));
   if(!entries.some(v=>v.id===selected))selected=entries[0]?.id??null;
   for(const [i,entry]of entries.slice(page*40,page*40+40).entries()){const b=action(items,(page*40+i+1)+'. '+(entry.title||entry.card?.title||entry.nodeId||entry.type||'Imported step'),()=>{selected=entry.id;paint(true);},false);b.dataset.deckStep=entry.id;b.setAttribute('aria-current',String(entry.id===selected));}
   const paging=make('div',sidebar);paging.className='deck-tools';const prev=action(paging,'Previous',()=>{page--;paint(true);},false),nextPage=action(paging,'Next',()=>{page++;paint(true);},false);prev.disabled=page===0;nextPage.disabled=(page+1)*40>=entries.length;make('small',paging,entries.length+' steps');
   const editor=make('section',layout);editor.id='presentationStepEditor';const entry=entries.find(v=>v.id===selected);if(!entry){make('p',editor,'Start with an overview, a title or a text slide.');return;}
   make('h3',editor,entry.title||entry.card?.title||entry.nodeId||'Presentation step');const commands=make('div',editor);commands.className='deck-tools';
   for(const [title,actionName,extra]of [['↑','move',{offset:-1}],['↓','move',{offset:1}],['Duplicate','duplicate',{}],['Remove…','remove',{}]]){const b=action(commands,title,()=>{if(actionName==='remove'&&!confirm('Remove this step from the draft? Its imported data and historic notes remain unchanged until you save.'))return;const newId=crypto.randomUUID();if(write({action:actionName,id:selected,...extra,...(actionName==='duplicate'?{newId}:{})})){if(actionName==='duplicate')selected=newId;const index=diagramFor().presentation.sequence.findIndex(v=>v.id===selected);if(index>=0)page=Math.floor(index/40);paint(true);}});b.dataset.deckAction=actionName+(extra.offset??'');if(actionName==='move')b.setAttribute('aria-label',extra.offset<0?'Move step up':'Move step down');}
   const field=(title,key,value,max,multiline=false)=>{const label=make('label',editor,title),input=make(multiline?'textarea':'input',label);input.value=typeof value==='string'?value:'';input.maxLength=max;input.dataset.deckField=key;input.dataset.deckWrite='true';input.disabled=!editable();input.addEventListener('input',()=>{if(!editable())return;if(!write({action:'update',id:selected,changes:{[key]:input.value}}))input.value=typeof value==='string'?value:'';});};
   const supportedCard=entry.type==='card'&&['title','text'].includes(entry.card?.kind);if(supportedCard){field('Slide title','title',entry.card.title,120);field('Eyebrow','eyebrow',entry.card.eyebrow,80);field('Public body · Editing replaces body formatting with plain text','body',entry.card.body,8000,true);}else if(['overview','section','chapter'].includes(entry.type))field('Slide title','title',entry.title,120);else make('p',editor,entry.type==='node'?'Diagram block '+entry.nodeId:'Imported content · Preserved exactly. Order and notes can be edited.').className='diagram-note';
   const key=window.SirenPresentationEdits.presentationNoteKey(entry);field('Private presenter notes · Never shown in Audience','note',value.notes?.[key]?.text,5000,true);
  }
  return Object.freeze({paint,dispose(){disposed=true;host.replaceChildren();},reset(){selected=null;page=0;signature='';paint(true);}});
 }});
})();
