(() => {
 'use strict';
 window.SirenNativeDiagramStyleView=Object.freeze({create({host,diagramFor,editable,onStyle,onStatus,onPending=()=>{}}){
  let targets=[],selected='',disposed=false,sourceFontDeclared=false;const pending=new Set();
  function field(label,id,type){const wrap=document.createElement('label'),input=document.createElement(type==='select'?'select':'input');wrap.textContent=label;input.id=id;if(type!=='select')input.type=type;wrap.append(input);host.append(wrap);return input;}
  const options=(input,values)=>{for(const value of values){const option=document.createElement('option');option.value=String(value);option.textContent=value==='inherit'?'Inherit':String(value);input.append(option);}};
  const themeDefault=input=>{const option=document.createElement('option');option.value='';option.textContent='Theme default';option.disabled=true;input.append(option);};
  const title=field('Diagram title','diagramStyleTitle','text');title.maxLength=160;
  const family=field('Font','diagramStyleFont','select');themeDefault(family);options(family,window.SirenNativeDiagramStyle.fonts);
  const size=field('Size','diagramStyleSize','number');size.min='10';size.max='28';size.step='1';size.placeholder='Theme default';
  const weight=field('Weight','diagramStyleWeight','select');themeDefault(weight);options(weight,window.SirenNativeDiagramStyle.weights);
  const target=field('Block','diagramStyleTarget','select');
  const controls={};for(const [key,label]of [['fill','Fill'],['border','Border'],['text','Text']]){const wrap=document.createElement('label'),check=document.createElement('input'),color=document.createElement('input');check.type='checkbox';check.id='diagramStyleUse_'+key;color.type='color';color.id='diagramStyle_'+key;wrap.append(check,document.createTextNode(label),color);host.append(wrap);controls[key]={check,color};}
  const nodeFamily=field('Block font','diagramStyleNodeFont','select');options(nodeFamily,['inherit',...window.SirenNativeDiagramStyle.fonts]);
  const useNodeSize=field('Block size','diagramStyleUse_nodeSize','checkbox'),nodeSize=field('Size','diagramStyle_nodeSize','number');nodeSize.min='9';nodeSize.max='28';nodeSize.step='1';nodeSize.placeholder='Inherit';
  const nodeWeight=field('Block weight','diagramStyleNodeWeight','select');options(nodeWeight,['inherit',...window.SirenNativeDiagramStyle.weights]);
  const globalFields=[title,family,size,weight],blockFields=[nodeFamily,useNodeSize,nodeSize,nodeWeight];
  const note=document.createElement('p');note.className='diagram-style-note';note.textContent='Imported Mermaid colours and fonts take priority. Inherit uses the diagram/class font. Changes stay local until Save diagram.';host.append(note);
  function paint(){if(disposed)return;const diagram=diagramFor();if(!diagram)return;const enabled=editable(),fontGlobal=sourceFontDeclared||targets.some(item=>item.protected.fontGlobal);if(!pending.has(title))title.value=diagram.diagramTitle||'';if(!pending.has(family))family.value=diagram.fontFamily||'';if(!pending.has(size))size.value=diagram.fontSize?String(diagram.fontSize):'';if(!pending.has(weight))weight.value=diagram.fontWeight?String(diagram.fontWeight):'';for(const input of [title,target])input.disabled=!enabled;for(const input of [family,size,weight]){input.disabled=!enabled||fontGlobal;input.title=fontGlobal?'This font is declared in Mermaid. Edit its source to change it.':'';}
   const styles=diagram.nodeStyles?.[selected]||{},chosen=targets.find(item=>item.id===selected),fromClass=diagram.styleClasses?.[diagram.nodeClasses?.[selected]]||{};
   for(const [key,{check,color}]of Object.entries(controls)){const protectedColour=chosen?.protected[key]===true;check.checked=Boolean(styles[key]);color.value=styles[key]||fromClass[key]||(key==='text'?'#20283a':key==='border'?'#64748b':'#dbeafe');check.disabled=!enabled||!chosen||protectedColour;color.disabled=check.disabled||!check.checked;check.title=color.title=protectedColour?'This colour is declared in Mermaid. Edit its source to change it.':'';}
   if(!pending.has(nodeFamily))nodeFamily.value=styles.fontFamily||'inherit';if(!pending.has(nodeWeight))nodeWeight.value=String(styles.fontWeight||'inherit');if(!pending.has(useNodeSize))useNodeSize.checked=Object.hasOwn(styles,'fontSize');if(!pending.has(nodeSize))nodeSize.value=styles.fontSize||fromClass.fontSize||diagram.fontSize?String(styles.fontSize||fromClass.fontSize||diagram.fontSize):'';
   for(const input of blockFields){input.disabled=!enabled||!chosen||chosen.protected.font===true;input.title=chosen?.protected.font?'This font is declared in Mermaid. Edit its source to change it.':'';}nodeSize.disabled=nodeSize.disabled||!useNodeSize.checked;
  }
  function apply(patch,fields=[]){if(disposed||!editable())return false;const result=onStyle(patch);if(!result?.ok){for(const input of fields)input.setAttribute('aria-invalid','true');onStatus('Style change refused · Correct the value, or press Esc to cancel');paint();return false;}for(const input of fields){pending.delete(input);input.removeAttribute('aria-invalid');}paint();onPending();return true;}
  function commit(){if(!pending.size)return true;const patch={};if(pending.has(title)){patch.diagramTitle=title.value;patch.diagramTitleTouched=true;}if(pending.has(family))patch.fontFamily=family.value;if(pending.has(size))patch.fontSize=Number(size.value);if(pending.has(weight))patch.fontWeight=Number(weight.value);
   if(blockFields.some(input=>pending.has(input))){if(!targets.some(item=>item.id===selected)){onStatus('The edited block is no longer available. Press Esc to cancel its fields.');return false;}const nodes=structuredClone(diagramFor().nodeStyles||{}),style={...nodes[selected]};if(pending.has(nodeFamily)){if(nodeFamily.value==='inherit')delete style.fontFamily;else style.fontFamily=nodeFamily.value;}if(pending.has(nodeWeight)){if(nodeWeight.value==='inherit')delete style.fontWeight;else style.fontWeight=Number(nodeWeight.value);}if(pending.has(useNodeSize)||pending.has(nodeSize)){if(useNodeSize.checked)style.fontSize=Number(nodeSize.value);else delete style.fontSize;}if(Object.keys(style).length)Object.defineProperty(nodes,selected,{value:style,enumerable:true,writable:true,configurable:true});else delete nodes[selected];patch.nodeStyles=nodes;}
   return apply(patch,[...pending]);
  }
  for(const input of [...globalFields,...blockFields]){input.addEventListener('input',()=>{if(editable()){pending.add(input);onPending();}});input.addEventListener('change',()=>{if(disposed||!editable()||input.disabled)return;if(input===useNodeSize&&useNodeSize.checked&&nodeSize.value==='')nodeSize.value='16';pending.add(input);commit();});input.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();pending.delete(input);input.removeAttribute('aria-invalid');paint();onPending();}});}
  target.addEventListener('change',()=>{const next=target.value;if(!commit()){target.value=selected;return;}selected=next;paint();});
  for(const [key,{check,color}]of Object.entries(controls)){const change=()=>{if(!editable()||check.disabled)return;const diagram=diagramFor(),nodes=structuredClone(diagram.nodeStyles||{}),style={...nodes[selected]};if(check.checked)style[key]=color.value;else delete style[key];if(Object.keys(style).length)Object.defineProperty(nodes,selected,{value:style,enumerable:true,writable:true,configurable:true});else delete nodes[selected];apply({nodeStyles:nodes});};check.addEventListener('change',change);color.addEventListener('change',change);}
  return Object.freeze({paint,commit,isEditing:()=>pending.size>0,setTargets(value,{fontDeclared=false}={}){sourceFontDeclared=fontDeclared===true;targets=value.map(item=>({id:item.id,protected:{...item.protected}}));if(!targets.some(item=>item.id===selected)&&!pending.size)selected=targets[0]?.id||'';target.replaceChildren();if(!targets.length){const option=document.createElement('option');option.textContent='No stable blocks · Edit Mermaid source';option.value='';target.append(option);}for(const item of targets){const option=document.createElement('option');option.value=option.textContent=item.id;target.append(option);}target.value=selected;paint();},select(id){if(!targets.some(item=>item.id===id)||!commit())return false;selected=id;target.value=id;paint();return true;},dispose(){disposed=true;targets=[];pending.clear();host.replaceChildren();}});
 }});
})();
