(() => {
 'use strict';
 window.SirenNativeDiagramStyleView=Object.freeze({create({host,diagramFor,editable,onStyle,onStatus,onPending=()=>{}}){
  let targets=[],selected='',disposed=false;const pending=new Set();
  function field(label,id,type){const wrap=document.createElement('label'),input=document.createElement(type==='select'?'select':'input');wrap.textContent=label;input.id=id;if(type!=='select')input.type=type;wrap.append(input);host.append(wrap);return input;}
  const title=field('Diagram title','diagramStyleTitle','text');title.maxLength=160;
  const family=field('Font','diagramStyleFont','select');for(const value of window.SirenNativeDiagramStyle.fonts){const option=document.createElement('option');option.value=option.textContent=value;family.append(option);}
  const size=field('Size','diagramStyleSize','number');size.min='10';size.max='28';size.step='1';
  const target=field('Block','diagramStyleTarget','select');
  const controls={};for(const [key,label]of [['fill','Fill'],['border','Border'],['text','Text']]){const wrap=document.createElement('label'),check=document.createElement('input'),color=document.createElement('input');check.type='checkbox';check.id='diagramStyleUse_'+key;color.type='color';color.id='diagramStyle_'+key;wrap.append(check,document.createTextNode(label),color);host.append(wrap);controls[key]={check,color};}
  const note=document.createElement('p');note.className='diagram-style-note';note.textContent='Imported Mermaid colours take priority. Changes stay local until Save diagram.';host.append(note);
  function paint(){if(disposed)return;const diagram=diagramFor();if(!diagram)return;const enabled=editable();if(!pending.has(title))title.value=diagram.diagramTitle||'';if(!pending.has(family))family.value=diagram.fontFamily||'Inter';if(!pending.has(size))size.value=String(diagram.fontSize||15);for(const input of [title,family,size,target])input.disabled=!enabled;
   const styles=diagram.nodeStyles?.[selected]||{},chosen=targets.find(item=>item.id===selected),fromClass=diagram.styleClasses?.[diagram.nodeClasses?.[selected]]||{};
   for(const [key,{check,color}]of Object.entries(controls)){const protectedColour=chosen?.protected[key]===true;check.checked=Boolean(styles[key]);color.value=styles[key]||fromClass[key]||(key==='text'?'#20283a':key==='border'?'#64748b':'#dbeafe');check.disabled=!enabled||!chosen||protectedColour;color.disabled=check.disabled||!check.checked;check.title=color.title=protectedColour?'This colour is declared in Mermaid. Edit its source to change it.':'';}
  }
  function apply(patch,fields=[]){if(disposed||!editable())return false;const result=onStyle(patch);if(!result?.ok){for(const input of fields)input.setAttribute('aria-invalid','true');onStatus('Style change refused · Correct the value, or press Esc to cancel');paint();return false;}for(const input of fields){pending.delete(input);input.removeAttribute('aria-invalid');}paint();return true;}
  function commit(){if(!pending.size)return true;const patch={};if(pending.has(title)){patch.diagramTitle=title.value;patch.diagramTitleTouched=true;}if(pending.has(family))patch.fontFamily=family.value;if(pending.has(size))patch.fontSize=Number(size.value);return apply(patch,[...pending]);}
  for(const input of [title,family,size]){input.addEventListener('input',()=>{if(editable()){pending.add(input);onPending();}});input.addEventListener('change',()=>{pending.add(input);commit();});input.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();pending.delete(input);input.removeAttribute('aria-invalid');paint();onPending();}});}
  target.addEventListener('change',()=>{selected=target.value;paint();});
  for(const [key,{check,color}]of Object.entries(controls)){const change=()=>{if(!editable()||check.disabled)return;const diagram=diagramFor(),nodes=structuredClone(diagram.nodeStyles||{}),style={...nodes[selected]};if(check.checked)style[key]=color.value;else delete style[key];Object.defineProperty(nodes,selected,{value:style,enumerable:true,writable:true,configurable:true});apply({nodeStyles:nodes});};check.addEventListener('change',change);color.addEventListener('change',change);}
  return Object.freeze({paint,commit,isEditing:()=>pending.size>0,setTargets(value){targets=value.map(item=>({id:item.id,protected:{...item.protected}}));if(!targets.some(item=>item.id===selected))selected=targets[0]?.id||'';target.replaceChildren();if(!targets.length){const option=document.createElement('option');option.textContent='No stable blocks · Edit Mermaid source';option.value='';target.append(option);}for(const item of targets){const option=document.createElement('option');option.value=option.textContent=item.id;target.append(option);}target.value=selected;paint();},select(id){if(!targets.some(item=>item.id===id))return false;selected=id;target.value=id;paint();return true;},dispose(){disposed=true;targets=[];pending.clear();host.replaceChildren();}});
 }});
})();
