import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {hashOwnedFile} from '../../src/updates/download.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
const evidence=resolve('evidence/diagram-guided',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let receipt=null,packageCopy=null;
if(packageRoot){receipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(receipt.kind,'development-preview');assert.equal(receipt.releaseAdmitted,false);packageCopy=join(evidence,'Pachet-Știință-Guided');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar'))),receipt.appArchive.sha256);assert.deepEqual(await hashOwnedFile(join(packageCopy,receipt.appRelativePath),1024**3),receipt.runtimeBinary);}
const paths=['src/sources/manifest.mjs','src/sources/repository.mjs','src/sources/recovery.mjs','src/main.mjs','src/windows/diagram-edits.mjs','src/windows/diagram-reads.mjs','src/windows/coordinator.mjs','src/windows/source-barrier.mjs','src/windows/preload.cjs','src/ui/diagram/session.js','src/ui/diagram/draft.js','src/ui/diagram/guided-model.js','src/ui/diagram/guided-view.js','src/ui/diagram/guided.css','src/ui/diagram/window.html','src/ui/windows/diagram.js','build/diagram-guided.mjs','build/diagram-window.mjs','generated/windows/diagram.html','tests/native/diagram-guided.mjs','tests/native/drive.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture(),data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Actual native Guided',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000,sourceBytes=Buffer.from(Array.from({length:lineCount},(_,index)=>'value_'+index+' = '+index+' # Ș😀').join('\n'));
const ref=await sources.importSource({projectId:initial.project.id,bytes:sourceBytes}),point={sourceId:ref.sourceId,version:ref.version,sha256:ref.sha256};
const original=['flowchart TD','A[Original]-->B[Next]','style A fill:#ff3366,color:#ffffff',...Array.from({length:127},(_,index)=>'%% exact retained note '+index)].join('\r\n')+'\r\n';
const workspace={diagrams:[{id:'flow',name:'Guided with imported colours',source:original,nodeMetadata:{A:{agent:'EXACT_AGENT',sourceRef:point}},presentation:{notes:{overview:{text:'EXACT_PRIVATE_NOTE'}}}}],workpapers:[{id:'doc-a',title:'Exact Docs',blocks:[{id:'heading',kind:'heading',level:2,text:'PRIVATE_DOCS'}],releases:[{id:'history',author:'Actual author',sourceRef:point,verdict:'not-run'}]}]},metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify(workspace),unrelated:'EXACT_UNRELATED'}};
assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'native-guided-fixture'})).ok,true);const selected=await projects.readProject(initial.project.id);
const result={status:'ADVERSE',lineCount,inputs,cases:[],scope:'Actual native Guided readonly, finite page DOM, real invalid-field Lock rollback and explicit Save/Ctrl+S/Lock retaining every unrelated source and field. Build/style editing and physical displays are not qualified.'};let driver,working;
if(receipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));result.package={sourceCommit:receipt.sourceCommit,archive:receipt.appArchive,runtime:receipt.runtimeBinary};}
const keys=async(page,key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
const inputValue=async(page,selector,value)=>{await page.click(selector);await keys(page,'a','KeyA',65,2);await page.send('Input.insertText',{text:value});};
const inline=async(page,line,field,value)=>{await page.click('[data-line="'+line+'"][data-field="'+field+'"]');await inputValue(page,'[data-guided-input="'+field+'"]',value);};
const unchangedSources=async saved=>{assert.deepEqual(saved.sourceRefs,selected.sourceRefs);assert.equal(JSON.parse(saved.json).storage.unrelated,'EXACT_UNRELATED');assert.deepEqual(await sources.exportSource({projectId:initial.project.id,sourceId:ref.sourceId,version:ref.version}),sourceBytes);};
try{
 driver=await launchDesktop(packageCopy?{executable:join(packageCopy,receipt.appRelativePath),packaged:true}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+initial.project.id]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 const attach=async view=>{const page=await attachNativePage(driver,'siren://app/windows/'+view.role+'.html?windowId='+view.windowId);await page.waitFor('document.body.dataset.'+(view.role==='diagram'?'diagram':view.role==='docs'?'document':'source')+'Ready==="true"');return {view,page};};
 await driver.waitFor('document.getElementById("homeDiagramWindows")?.disabled===false');await driver.click('#homeDiagramWindows');await driver.waitFor('document.querySelector(".home-library [data-entity-id=flow]")!=null');await driver.click('.home-library [data-entity-id=flow]');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="diagram")})()');
 const reader=await attach((await driver.evaluate('window.sirenWindow.listViews()')).views.find(view=>view.role==='diagram'));await reader.page.click('#diagramGuidedMode');
 assert.equal(await reader.page.evaluate('document.querySelectorAll(".guided-row").length'),64);assert.equal(await reader.page.evaluate('Array.from(document.querySelectorAll(".guided-chip")).every(button=>button.disabled)'),true);assert.equal(await reader.page.evaluate('document.getElementById("diagramSource").value'),original.replaceAll('\r\n','\n'));assert.deepEqual(await projects.readProject(initial.project.id),selected);
 assert.equal((await reader.page.evaluate('window.sirenDiagramRead.getDiagram()')).diagram.source,original,'Exact CRLF source must be read from the genuine native transport, not the normalized textarea');
 const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(view=>view.windowId);await reader.page.click('#openWorkingDiagram');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>'+before.length+'})()');working=await attach((await driver.evaluate('window.sirenWindow.listViews()')).views.find(view=>!before.includes(view.windowId)));await working.page.waitFor('document.body.dataset.diagramReadonly==="false"');
 for(const [role,entityId]of [['code',ref.sourceId],['docs','doc-a']]){const opened=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify({role,entityId,...(role==='code'?{version:ref.version}:{})})+')');assert.equal(opened.ok,true);await attach(opened.view);}
 await working.page.click('#diagramGuidedMode');assert.equal(await working.page.evaluate('document.querySelectorAll(".guided-row").length'),64);await working.page.click('#diagramGuided .guided-pages button:last-child');assert.equal(await working.page.evaluate('document.querySelector(".guided-row").dataset.guidedLine'),'64');assert.equal(await working.page.evaluate('document.querySelectorAll(".guided-row").length'),64);await working.page.click('#diagramGuided .guided-pages button:first-child');
 result.cases.push({name:'actual Home/readonly/working native Guided; finite 64-line pages and no readonly edits or project changes',ok:true});
 await inline(working.page,1,'fromId','bad id');await keys(working.page,'Enter','Enter',13);assert.equal(await working.page.evaluate('document.querySelector("[data-guided-input=fromId]").value'),'bad id');await driver.click('#homeLock');await working.page.waitFor('!document.body.inert&&document.documentElement.style.visibility!=="hidden"');assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked,true);assert.equal(await working.page.evaluate('document.querySelector("[data-guided-input=fromId]").value'),'bad id');assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),original.replaceAll('\r\n','\n'));assert.deepEqual(await projects.readProject(initial.project.id),selected);await unchangedSources(selected);await working.page.click('[data-guided-input=fromId]');await keys(working.page,'Escape','Escape',27);await working.page.waitFor('document.querySelector("[data-guided-input=fromId]")==null');
 result.cases.push({name:'real all-view Lock refuses invalid inline ID and restores exact tentative field; Escape cancels with whole project and Python source unchanged',ok:true});
 await inline(working.page,1,'fromLabel','Context Ș😀');await working.page.waitFor('document.getElementById("saveDiagram").disabled===false');await working.page.click('#saveDiagram');await working.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="2"');
 const afterSave=original.replace('A[Original]-->B[Next]','A["Context Ș😀"] --> B[Next]'),expected=structuredClone(workspace);expected.diagrams[0]={...expected.diagrams[0],source:afterSave,sirenNativeVersion:2};const saved=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(saved),expected);await unchangedSources(saved);
 await working.page.waitFor('document.body.dataset.diagramRendered==="true"');assert.equal(await working.page.evaluate('Array.from(document.querySelectorAll("#diagramCanvas .node rect")).some(node=>getComputedStyle(node).fill==="rgb(255, 51, 102)")'),true,'Actual imported fill must remain rendered');assert.equal(await working.page.evaluate('document.getElementById("diagramViewport").getBoundingClientRect().height>innerHeight*.6'),true);
 await working.page.evaluate('document.getElementById("diagramTheme").value="light";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'guided-light.png'));await working.page.evaluate('document.getElementById("diagramTheme").value="dark";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'guided-dark.png'));await working.page.click('#diagramTextMode');assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),afterSave.replaceAll('\r\n','\n'));await working.page.click('#diagramGuidedMode');
 result.cases.push({name:'actual pending inline Save button commits one CRLF line, retains imported rendered fill and all metadata/source bytes; light/dark and Text roundtrip',ok:true});
 await inline(working.page,1,'toLabel','Decision');await keys(working.page,'s','KeyS',83,2);await working.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="3"');const afterKeyboard=afterSave.replace('B[Next]','B["Decision"]');expected.diagrams[0]={...expected.diagrams[0],source:afterKeyboard,sirenNativeVersion:3};assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);
 await inline(working.page,1,'fromLabel','Saved by Lock');await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(target=>target.url.startsWith('siren://app/windows/')),false);
 expected.diagrams[0]={...expected.diagrams[0],source:afterKeyboard.replace('Context Ș😀','Saved by Lock'),sirenNativeVersion:4};const savedLock=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(savedLock),expected);await unchangedSources(savedLock);result.cases.push({name:'real Ctrl+S and all-view Lock durably commit pending valid inline fields, retire every Diagram/Code/Docs target and preserve unrelated data',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{result.runtimeLog=driver.logs().slice(-6000);if(working){result.diagnostics=await working.page.evaluate('({status:document.getElementById("viewStatus").textContent,body:{...document.body.dataset},source:document.getElementById("diagramSource").value,field:document.querySelector("[data-guided-input]")?.value})');await working.page.screenshot(join(evidence,'failure.png'));}else await driver?.screenshot(join(evidence,'failure.png'));}catch{}}
finally{if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(receipt){result.packageAfter={archive:{sha256:hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar')))},runtime:await hashOwnedFile(join(packageCopy,receipt.appRelativePath),1024**3)};result.packageUnchanged=result.packageAfter.archive.sha256===receipt.appArchive.sha256&&JSON.stringify(result.packageAfter.runtime)===JSON.stringify(receipt.runtimeBinary);if(!result.packageUnchanged)result.status='ADVERSE';}if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
