import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
const evidence=resolve('evidence/diagram-edit',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let packageReceipt=null,packageCopy=null;
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
if(packageRoot){packageReceipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(packageReceipt.kind,'development-preview');assert.equal(packageReceipt.releaseAdmitted,false);packageCopy=join(evidence,'Pachet-Știință-Diagrams');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar'))),packageReceipt.appArchive.sha256);}
const paths=['src/sources/manifest.mjs','src/sources/repository.mjs','src/sources/recovery.mjs','src/main.mjs','src/windows/domain.mjs','src/windows/diagram-edits.mjs','src/windows/diagram-reads.mjs','src/windows/coordinator.mjs','src/windows/preload.cjs','src/projects/domain-validation.mjs','src/ui/diagram/draft.js','src/ui/diagram/session.js','src/ui/diagram/window.html','src/ui/windows/diagram.js','build/diagram-window.mjs','generated/windows/diagram.html','tests/native/diagram-edit.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture();
const data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Actual native working Diagrams',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000;
const text=Array.from({length:lineCount},(_,i)=>'value_'+i+' = '+i+' # Ș😀').join('\n')+'\n',ref=await sources.importSource({projectId:initial.project.id,bytes:Buffer.from(text)}),point={sourceId:ref.sourceId,version:1,sha256:ref.sha256};
const diagrams=['flow','other'].map(id=>({id,name:id,source:'flowchart TD\nA[Original]-->B\nstyle A fill:#ff3366,color:#ffffff',nodeMetadata:{A:{agent:'EXACT_AGENT',sourceRef:point}},diagramTitle:'Preserved title'}));
const workspace={diagrams,workpapers:[{id:'doc-a',title:'Exact document',agent:{name:'EXACT_AGENT'},releases:[{id:'history',author:'Actual author',verdict:'not-run',sourceRef:point}],blocks:[{id:'heading',kind:'heading',level:2,text:'PRIVATE_DOCS'}]}]},metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify(workspace),unrelated:'EXACT_UNRELATED'}};
assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'native-diagram-edit-fixture'})).ok,true);const selected=await projects.readProject(initial.project.id);
const result={status:'ADVERSE',lineCount,inputs,cases:[],scope:'Actual source-only native Diagram editing, frozen validator, independent saves, same-entity conflicts, local preview/theme retention, explicit review/reload, real Close and all-view Lock. Build/Guided and metadata style rendering are still separate work.'};let driver;
if(packageReceipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));result.package={sourceCommit:packageReceipt.sourceCommit,archive:packageReceipt.appArchive,runtime:packageReceipt.runtimeBinary};}
const keys=async(page,key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
const replace=async(page,value)=>{await page.click('#diagramSource');await keys(page,'a','KeyA',65,2);await page.send('Input.insertText',{text:value});};
const confirmReload=async(page,accept)=>{await page.send('Page.enable');const from=driver.events.length,click=page.click('#replaceLatestDiagram');let found=false;try{const until=Date.now()+20000;while(Date.now()<until){found=driver.events.slice(from).some(event=>event.method==='Target.receivedMessageFromTarget'&&(()=>{try{const message=JSON.parse(event.params.message);return message.method==='Page.javascriptDialogOpening'&&message.params.type==='confirm';}catch{return false;}})());if(found)break;await delay(20);}assert.equal(found,true,'Actual local-source discard confirmation required');await page.send('Page.handleJavaScriptDialog',{accept});await click;}catch(error){await click.catch(()=>{});throw error;}};
try{
 driver=await launchDesktop(packageCopy?{executable:join(packageCopy,packageReceipt.appRelativePath),packaged:true}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+initial.project.id]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 const attach=async view=>{const page=await attachNativePage(driver,'siren://app/windows/'+view.role+'.html?windowId='+view.windowId);await page.waitFor('document.body.dataset.'+(view.role==='diagram'?'diagram':view.role==='docs'?'document':'source')+'Ready==="true"');return {view,page};};
 const open=async(role,entityId)=>{const result=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify({role,entityId,...(role==='code'?{version:1}:{})})+')');assert.equal(result.ok,true);return attach(result.view);};
 await driver.waitFor('document.getElementById("homeDiagramWindows")!=null');await driver.click('#homeDiagramWindows');await driver.waitFor('document.querySelector(".home-library [data-entity-id=flow]")!=null');await driver.click('.home-library [data-entity-id=flow]');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="diagram")})()');
 const firstView=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>v.role==='diagram'),reader=await attach(firstView),otherReader=await open('diagram','other'),code=await open('code',ref.sourceId),docs=await open('docs','doc-a');await reader.page.waitFor('document.getElementById("openWorkingDiagram").hidden===false');
 assert.equal((await reader.page.evaluate('window.sirenDiagramEdit.applyDiagram({})')).ok,false);assert.equal((await code.page.evaluate('window.sirenDiagramEdit.openWorkingCopy()')).ok,false);assert.equal((await docs.page.evaluate('window.sirenDiagramEdit.openWorkingCopy()')).ok,false);
 // Passive diagnostics preserve the original single click, roster-growth oracle
 // and deadlines. Extra observations can affect scheduling; a local pass is not
 // proof of the original hosted failure's cause or correction.
 const openWorkingObservations=result.openWorkingObservations=[];
 const openWorking=async own=>{
  const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(v=>v.windowId);
  const observation={callerWindowId:own.view.windowId,before,stages:[]};openWorkingObservations.push(observation);
  await own.page.evaluate(`(()=>{if(window.__sirenDiagramOpenObservation)return;const state=window.__sirenDiagramOpenObservation={events:[]};for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,event=>{if(!event.target.closest?.('#openWorkingDiagram'))return;state.events.push({type,isTrusted:event.isTrusted,at:performance.now(),bodyInert:document.body.inert,visibility:document.documentElement.style.visibility,hidden:document.getElementById('openWorkingDiagram').hidden,disabled:document.getElementById('openWorkingDiagram').disabled});if(state.events.length>16)state.events.shift();},{capture:true,passive:true});})()`);
  const observe=async stage=>{
   try{
    const page=await own.page.evaluate(`(()=>{const e=document.getElementById('openWorkingDiagram'),r=e?.getBoundingClientRect(),hit=r?document.elementFromPoint(r.x+r.width/2,r.y+r.height/2):null;return {url:location.href,bodyInert:document.body.inert,visibility:document.documentElement.style.visibility,ready:document.body.dataset.diagramReady,readonly:document.body.dataset.diagramReadonly,button:e?{hidden:e.hidden,disabled:e.disabled,rectangle:{x:r.x,y:r.y,width:r.width,height:r.height},hit:e.contains(hit),cover:hit?.id||hit?.tagName}:null,status:document.getElementById('viewStatus')?.textContent.slice(0,200),events:window.__sirenDiagramOpenObservation?.events.slice(-16)};})()`);
    const roster=await driver.evaluate('(async()=>{const r=await window.sirenWindow.listViews();return {ok:r?.ok===true,code:r?.code,views:r?.views?.slice(0,32).map(v=>({windowId:v.windowId,role:v.role,entityId:v.entityId,state:v.state}))};})()');
    observation.stages.push({stage,page,roster});
   }catch{observation.stages.push({stage,observationUnavailable:true});}
  };
  await observe('before-click');
  try{
   await own.page.click('#openWorkingDiagram');await observe('after-click');
   await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>'+before.length+'})()');
   const view=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>!before.includes(v.windowId)),opened=await attach(view);
   await opened.page.waitFor('document.body.dataset.diagramReadonly==="false"');observation.openedWindowId=view.windowId;await observe('working-ready');return opened;
  }catch(error){await observe('failure');throw error;}
 };
 const a=await openWorking(reader),stale=await openWorking(reader),b=await openWorking(otherReader),local='flowchart TD\nA[Unsaved local 😀]-->B';await replace(stale.page,local);
 assert.equal(await a.page.evaluate('document.getElementById("diagramViewport").getBoundingClientRect().height>innerHeight*.6'),true,'Diagram preview must fill the remaining window, not collapse into an auto grid row');
 const sourceA='flowchart TD\nA[Saved A 😀]-->B[Context]\nstyle A fill:#ff3366,color:#ffffff',sourceB='sequenceDiagram\nAlice->>Bob: Saved B';await replace(a.page,sourceA);await a.page.waitFor('document.body.dataset.diagramRendered==="true"&&Array.from(document.querySelectorAll("#diagramCanvas text")).some(t=>t.textContent.includes("Saved A"))');
 assert.deepEqual(await projects.readProject(initial.project.id),selected);await a.page.click('#saveDiagram');await a.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="2"');
 const expected=structuredClone(workspace);expected.diagrams[0]={...expected.diagrams[0],source:sourceA,sirenNativeVersion:2};const savedA=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(savedA),expected);assert.deepEqual(savedA.sourceRefs,selected.sourceRefs);assert.equal(JSON.parse(savedA.json).storage.unrelated,'EXACT_UNRELATED');assert.deepEqual(await sources.exportSource({projectId:initial.project.id,sourceId:ref.sourceId,version:1}),Buffer.from(text));
 result.cases.push({name:'actual hit-tested Home and working admission; genuine frozen-validator source save preserves whole entity metadata, unrelated Docs/agents/releases and large Python source',ok:true});
 await stale.page.waitFor('document.getElementById("diagramChangesNotice").hidden===false');assert.equal(await stale.page.evaluate('document.getElementById("diagramSource").value'),local);await stale.page.evaluate('document.getElementById("diagramTheme").value="dark";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await stale.page.waitFor('document.body.dataset.diagramRendered==="true"');assert.equal(await stale.page.evaluate('document.getElementById("diagramSource").value'),local);
 await replace(b.page,sourceB);await keys(b.page,'s','KeyS',83,2);await b.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="2"');expected.diagrams[1]={...expected.diagrams[1],source:sourceB,sirenNativeVersion:2};const savedB=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(savedB),expected);
 await stale.page.click('#saveDiagram');await stale.page.waitFor('document.getElementById("viewStatus").textContent.includes("refused")');assert.equal(await stale.page.evaluate('document.getElementById("diagramSource").value'),local);assert.deepEqual(await projects.readProject(initial.project.id),savedB);await driver.click('#homeLock');await stale.page.waitFor('!document.body.inert&&document.documentElement.style.visibility!=="hidden"');assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked,true);assert.equal(await stale.page.evaluate('document.getElementById("diagramSource").value'),local);assert.deepEqual(await projects.readProject(initial.project.id),savedB);
 result.cases.push({name:'actual independent Ctrl+S save and stale same-diagram refusal; theme preview retains local source and failed all-view Lock restores genuine frames without overwrite',ok:true});
 await stale.page.click('#reviewLatestDiagram');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.filter(v=>v.role==="diagram").length===6})()');assert.equal(await stale.page.evaluate('document.getElementById("diagramSource").value'),local);await confirmReload(stale.page,false);assert.equal(await stale.page.evaluate('document.getElementById("diagramSource").value'),local);await confirmReload(stale.page,true);await stale.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.getElementById("diagramSource").value==='+JSON.stringify(sourceA));
 await stale.page.evaluate('document.getElementById("diagramTheme").value="light";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await stale.page.waitFor('document.body.dataset.diagramRendered==="true"');await stale.page.screenshot(join(evidence,'diagram-working-light.png'));await stale.page.evaluate('document.getElementById("diagramTheme").value="dark";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await stale.page.waitFor('document.body.dataset.diagramRendered==="true"');await stale.page.screenshot(join(evidence,'diagram-working-dark.png'));
 const closeSource='flowchart TD\nA[Saved by Close]-->B';await replace(a.page,closeSource);assert.deepEqual(await projects.readProject(initial.project.id),savedB);await a.page.click('#closeView');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&!r.views.some(v=>v.windowId==='+JSON.stringify(a.view.windowId)+')&&!document.body.inert})()');expected.diagrams[0]={...expected.diagrams[0],source:closeSource,sirenNativeVersion:3};const savedClose=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(savedClose),expected);const reopened=await openWorking(reader);assert.equal(await reopened.page.evaluate('document.getElementById("diagramSource").value'),closeSource);
 result.cases.push({name:'actual separate latest review and Cancel/accept reload; light/dark previews; native Close durably saves unsaved source and fresh working reopen reads exact selected version',ok:true});
 await stale.page.waitFor('document.body.dataset.diagramVersion==="3"');const lockSource='flowchart TD\nA[Saved by Lock 😀]-->B';await replace(b.page,lockSource);assert.deepEqual(await projects.readProject(initial.project.id),savedClose);await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);
 expected.diagrams[1]={...expected.diagrams[1],source:lockSource,sirenNativeVersion:3};const savedLock=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(savedLock),expected);assert.deepEqual(savedLock.sourceRefs,selected.sourceRefs);assert.equal(JSON.parse(savedLock.json).storage.unrelated,'EXACT_UNRELATED');assert.deepEqual(await sources.exportSource({projectId:initial.project.id,sourceId:ref.sourceId,version:1}),Buffer.from(text));
 result.cases.push({name:'actual all-view Lock saves unsaved Diagram, independently seals multiple Diagram/Code/Docs views, destroys satellites and preserves every unrelated source and document field',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{await driver?.screenshot(join(evidence,'failure.png'));result.runtimeLog=driver?.logs().slice(-5000);result.diagnostics=[];for(const target of(await driver.send('Target.getTargets')).targetInfos.filter(t=>t.url.startsWith('siren://app/windows/diagram.html'))){const page=await attachNativePage(driver,target.url);result.diagnostics.push(await page.evaluate('({url:location.href,status:document.getElementById("viewStatus")?.textContent,body:{...document.body.dataset},source:document.getElementById("diagramSource")?.value})'));await page.screenshot(join(evidence,'view-failure-'+result.diagnostics.length+'.png'));}}catch{}}
finally{if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
