import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,readdir,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
const evidence=resolve('evidence/diagram-export',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let packageReceipt,packageCopy;
if(packageRoot){packageReceipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(packageReceipt.kind,'development-preview');assert.equal(packageReceipt.releaseAdmitted,false);packageCopy=join(evidence,'Pachet-Știință-SVG');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar'))),packageReceipt.appArchive.sha256);}
const paths=['src/main.mjs','src/windows/diagram-export.mjs','src/windows/diagram-vector-render.mjs','src/windows/diagram-reads.mjs','src/windows/coordinator.mjs','src/windows/preload.cjs','src/ui/diagram/vector.js','src/ui/diagram/style.js','src/ui/windows/diagram.js','src/ui/diagram/window.html','build/diagram-vector.mjs','build/diagram-window.mjs','generated/windows/diagram.html','generated/diagram-vector.html','tests/native/diagram-export.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture(),data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Native SVG export',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000,text=Array.from({length:lineCount},(_,i)=>'value_'+i+' = '+i+' # Ș😀').join('\n')+'\n',ref=await sources.importSource({projectId:initial.project.id,bytes:Buffer.from(text)}),point={sourceId:ref.sourceId,version:1,sha256:ref.sha256};
const original='flowchart TD\r\nA[Saved colour]-->B[Next]\r\n%% PRIVATE_COMMENT\r\nstyle A fill:#ff3366,color:#ffffff',workspace={diagrams:[{id:'flow',name:'Chosen flow',source:original,sirenNativeVersion:1,diagramTitleTouched:true,diagramTitle:'Exact title Ș😀',fontFamily:'Georgia',fontSize:20,nodeStyles:{A:{fill:'#000000'},B:{fill:'#12ab34'}},nodeMetadata:{A:{agent:'EXACT_AGENT',sourceRef:point}}},{id:'other',source:'sequenceDiagram\nA->>B: PRIVATE_OTHER_DIAGRAM'}],workpapers:[{id:'doc-a',title:'PRIVATE_DOCS',blocks:[{id:'p',kind:'paragraph',text:'PRIVATE_DOCS'}],releases:[{id:'history',author:'Actual author',verdict:'not-run'}]}]},metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify(workspace),unrelated:'EXACT_UNRELATED'}};
assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'native-svg-fixture'})).ok,true);const selected=await projects.readProject(initial.project.id),exportsDirectory=join(await projects.directory(initial.project.id),'exports');
const result={status:'ADVERSE',lineCount,inputs,cases:[],scope:'Actual native Diagram SVG button, saved-entity transport, bounded isolated rendering, readonly/dirty/stale/wrong-role behavior, whole project/source preservation and common Lock. Reveal integration uses actual receipt but does not open Explorer in this unattended fixture.'};let driver;
if(packageReceipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));result.package={sourceCommit:packageReceipt.sourceCommit,archive:packageReceipt.appArchive,runtime:packageReceipt.runtimeBinary};}
const keys=async(page,key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
const verifySvg=async receipt=>{assert.equal(receipt.ok,true);const bytes=await readFile(join(exportsDirectory,receipt.filename));assert.equal(bytes.length,receipt.bytes);assert.equal(hash(bytes),receipt.sha256);const svg=bytes.toString('utf8');for(const privateText of ['PRIVATE_DOCS','PRIVATE_OTHER_DIAGRAM','PRIVATE_COMMENT','EXACT_AGENT','value_299999'])assert.equal(svg.includes(privateText),false);assert.match(svg,/^<svg\b/);assert.equal(svg.includes('Exact title Ș😀'),true);return svg;};
try{
 driver=await launchDesktop(packageCopy?{executable:join(packageCopy,packageReceipt.appRelativePath),packaged:true}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+initial.project.id]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 const open=async(role,entityId)=>{const opened=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify({role,entityId,...(role==='code'?{version:1}:{})})+')');assert.equal(opened.ok,true);const page=await attachNativePage(driver,'siren://app/windows/'+role+'.html?windowId='+opened.view.windowId);await page.waitFor('document.body.dataset.'+(role==='diagram'?'diagram':role==='docs'?'document':'source')+'Ready==="true"');return {page,view:opened.view};};
 const reader=await open('diagram','flow'),code=await open('code',ref.sourceId),docs=await open('docs','doc-a');await reader.page.waitFor('document.body.dataset.diagramRendered==="true"&&!document.getElementById("diagramExportSvg").disabled');
 await reader.page.evaluate('document.getElementById("diagramTheme").value="light";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await reader.page.waitFor('document.body.dataset.diagramRendered==="true"');const saved=await reader.page.evaluate('window.sirenDiagramRead.getDiagram()'),request={expectedVersion:saved.version,expectedSha256:saved.sha256,appearance:'light'};for(const own of [code,docs])assert.equal((await own.page.evaluate('window.sirenDiagramExport.exportSvg('+JSON.stringify(request)+')')).ok,false);
 assert.equal((await reader.page.evaluate('window.sirenDiagramExport.exportSvg('+JSON.stringify({...request,source:'attacker',path:'outside.svg'})+')')).ok,false);
 await reader.page.click('#diagramExportSvg');await reader.page.waitFor('document.body.dataset.diagramExportId!=null&&!document.getElementById("diagramShowExport").hidden');const exportId=await reader.page.evaluate('document.body.dataset.diagramExportId'),filename='diagram-'+exportId+'.svg',bytes=await readFile(join(exportsDirectory,filename));assert.equal(await reader.page.evaluate('new DOMParser().parseFromString('+JSON.stringify(bytes.toString())+',"image/svg+xml").documentElement.textContent.includes("Saved colour")'),true);assert.equal(bytes.toString().includes('Exact title Ș😀'),true);assert.equal(bytes.toString().includes('#12ab34'),true);assert.equal(bytes.toString().includes('#ff3366'),true);assert.equal(bytes.toString().includes('PRIVATE_'),false);assert.deepEqual(await projects.readProject(initial.project.id),selected);await reader.page.screenshot(join(evidence,'svg-light.png'));
 result.cases.push({name:'actual readonly SVG button creates an owned vector file with selected saved title/styles/imported fill, no unrelated/private source and unchanged full project; wrong-role/path/source IPC refused',sha256:hash(bytes),ok:true});
 await reader.page.evaluate('document.getElementById("diagramTheme").value="dark";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await reader.page.waitFor('document.body.dataset.diagramRendered==="true"');const dark=await reader.page.evaluate('window.sirenDiagramExport.exportSvg('+JSON.stringify({...request,appearance:'dark'})+')');await verifySvg(dark);await reader.page.screenshot(join(evidence,'svg-dark.png'));assert.deepEqual(await projects.readProject(initial.project.id),selected);
 result.cases.push({name:'actual dark saved SVG export uses native exact entity receipt and preserves complete project/source metadata',ok:true});
 const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(view=>view.windowId);await reader.page.click('#openWorkingDiagram');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>'+before.length+'})()');const view=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(view=>!before.includes(view.windowId)),working=await attachNativePage(driver,'siren://app/windows/diagram.html?windowId='+view.windowId);await working.waitFor('document.body.dataset.diagramReadonly==="false"');
 const local=original.replace('Saved colour','Saved changed Ș😀');await working.click('#diagramSource');await keys(working,'a','KeyA',65,2);await working.send('Input.insertText',{text:local});await working.waitFor('document.body.dataset.diagramDirty==="true"');assert.equal(await working.evaluate('document.getElementById("diagramExportSvg").disabled'),true);assert.deepEqual(await projects.readProject(initial.project.id),selected);assert.equal((await readdir(exportsDirectory)).filter(file=>file.endsWith('.svg')).length,2);
 await working.click('#saveDiagram');await working.waitFor('document.body.dataset.diagramVersion==="2"&&document.body.dataset.diagramDirty==="false"');const expected=structuredClone(workspace);expected.diagrams[0]={...expected.diagrams[0],source:local.replaceAll('\r\n','\n'),sirenNativeVersion:2};const savedProject=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(savedProject),expected);await working.click('#diagramExportSvg');await working.waitFor('document.body.dataset.diagramExportId!=null');const workingId=await working.evaluate('document.body.dataset.diagramExportId'),workingSvg=await readFile(join(exportsDirectory,'diagram-'+workingId+'.svg'),'utf8');assert.equal(await working.evaluate('Array.from(new DOMParser().parseFromString('+JSON.stringify(workingSvg)+',"image/svg+xml").querySelectorAll("[data-native-node-id=A] text .row"),row=>row.textContent.trim()).join(" ")'),'Saved changed Ș😀');assert.equal(workingSvg.includes('Exact title Ș😀'),true);assert.deepEqual(await projects.readProject(initial.project.id),savedProject);
 assert.equal((await reader.page.evaluate('window.sirenDiagramExport.exportSvg('+JSON.stringify(request)+')')).ok,false);assert.equal((await readdir(exportsDirectory)).filter(file=>file.endsWith('.svg')).length,3);result.cases.push({name:'dirty native draft disables export until explicit Save; fresh SVG matches version2 and stale reader export is refused without extra files or project mutation',ok:true});
 await working.click('#diagramStyleToggle');await working.click('#diagramStyleSize');await keys(working,'a','KeyA',65,2);await working.send('Input.insertText',{text:'200'});await driver.click('#homeLock');await working.waitFor('!document.body.inert&&document.documentElement.style.visibility!=="hidden"');assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked,true);assert.equal(await working.evaluate('document.getElementById("diagramStyleSize").value'),'200');assert.equal(await working.evaluate('document.getElementById("diagramShowExport").hidden'),true);assert.deepEqual(await projects.readProject(initial.project.id),savedProject);assert.equal((await readdir(exportsDirectory)).filter(file=>file.endsWith('.svg')).length,3);await working.click('#diagramStyleSize');await keys(working,'Escape','Escape',27);await working.waitFor('document.getElementById("diagramStyleSize").value==="20"');result.cases.push({name:'real refused Lock restores invalid tentative style and exact saved project/exports; retired Show file receipt is cleared, Escape cancels',ok:true});
 // Satellite rollback and Home's cinematic vault have separate completion.
 // Observe the actual Home control before requesting another real Lock.
 await driver.waitFor('document.getElementById("sirenLockVault").hidden===true&&!document.getElementById("homeLock").disabled');
 await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(target=>target.url.startsWith('siren://app/windows/')||target.url.endsWith('/diagram-vector.html')),false);assert.deepEqual(await projects.readProject(initial.project.id),savedProject);assert.deepEqual(await sources.exportSource({projectId:initial.project.id,sourceId:ref.sourceId,version:1}),Buffer.from(text));assert.equal((await readdir(exportsDirectory)).some(file=>file.startsWith('pending-')),false);result.cases.push({name:'real shared Lock joins exports, destroys all native views/utilities, retains saved exports and exact large Python/project data with no temporary export left',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{await driver?.screenshot(join(evidence,'failure.png'));result.runtimeLog=driver?.logs().slice(-6000);}catch{}}
finally{if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';if(packageReceipt){result.packageUnchanged=hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar')))===packageReceipt.appArchive.sha256&&hash(await readFile(join(packageCopy,packageReceipt.appRelativePath)))===packageReceipt.runtimeBinary.sha256;if(!result.packageUnchanged)result.status='ADVERSE';}await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
