import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {hashOwnedFile} from '../../src/updates/download.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
const evidence=resolve('evidence/diagram-build',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let receipt=null,packageCopy=null;
if(packageRoot){receipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(receipt.kind,'development-preview');assert.equal(receipt.releaseAdmitted,false);packageCopy=join(evidence,'Pachet-Știință-Guided');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar'))),receipt.appArchive.sha256);assert.deepEqual(await hashOwnedFile(join(packageCopy,receipt.appRelativePath),1024**3),receipt.runtimeBinary);}
const paths=['src/ui/windows/identity.js','src/windows/source-reads.mjs','src/sources/manifest.mjs','src/sources/repository.mjs','src/sources/recovery.mjs','src/main.mjs','src/windows/diagram-edits.mjs','src/windows/diagram-reads.mjs','src/windows/coordinator.mjs','src/windows/source-barrier.mjs','src/windows/preload.cjs','src/ui/diagram/session.js','src/ui/diagram/draft.js','src/ui/diagram/guided-model.js','src/ui/diagram/guided-view.js','src/ui/diagram/guided.css','src/ui/diagram/window.html','src/ui/windows/diagram.js','build/diagram-guided.mjs','build/diagram-window.mjs','generated/windows/diagram.html','tests/native/diagram-build.mjs','src/ui/diagram/build-model.js','src/ui/diagram/build-view.js','src/ui/diagram/style.js','src/ui/diagram/style-view.js','build/diagram-style.mjs','src/projects/domain-validation.mjs','src/windows/domain.mjs','tests/native/drive.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture(),data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Actual native Guided',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000,sourceBytes=Buffer.from(Array.from({length:lineCount},(_,index)=>'value_'+index+' = '+index+' # Ș😀').join('\n'));
const ref=await sources.importSource({projectId:initial.project.id,bytes:sourceBytes}),point={sourceId:ref.sourceId,version:ref.version,sha256:ref.sha256};
const original=['flowchart TD','A[Original]-->B[Next]','style A fill:#ff3366,color:#ffffff',...Array.from({length:127},(_,index)=>'%% exact retained note '+index)].join('\r\n')+'\r\n';
const workspace={diagrams:[{id:'flow',name:'Guided with imported colours',source:original,nodeStyles:{A:{fill:'#000000',text:'#000000'},B:{fill:'#2277cc',text:'#ffffff'}},fontFamily:'Georgia',fontSize:18,diagramTitle:'Saved title',diagramTitleTouched:true,nodeMetadata:{A:{agent:'EXACT_AGENT',sourceRef:point}},presentation:{notes:{overview:{text:'EXACT_PRIVATE_NOTE'}}}}],workpapers:[{id:'doc-a',title:'Exact Docs',blocks:[{id:'heading',kind:'heading',level:2,text:'PRIVATE_DOCS'}],releases:[{id:'history',author:'Actual author',sourceRef:point,verdict:'not-run'}]}]},metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify(workspace),unrelated:'EXACT_UNRELATED'}};
assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'native-guided-fixture'})).ok,true);const selected=await projects.readProject(initial.project.id);
const result={status:'ADVERSE',lineCount,inputs,cases:[],scope:'Actual native Guided readonly, finite page DOM, real invalid-field Lock rollback and explicit Save/Ctrl+S/Lock retaining every unrelated source and field. Actual metadata styles, imported colour precedence, one-transaction source/style Save and Lock are included. Native bounded flowchart Build label/shape/add/connect/direction, explicit save and tentative-field Lock refusal are included. Free block positioning/vector export/physical displays remain unqualified.'};let driver,working;
if(receipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));result.package={sourceCommit:receipt.sourceCommit,archive:receipt.appArchive,runtime:receipt.runtimeBinary};}
const keys=async(page,key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
const inputValue=async(page,selector,value)=>{await page.click(selector);await keys(page,'a','KeyA',65,2);await page.send('Input.insertText',{text:value});};
const inline=async(page,line,field,value)=>{await page.click('[data-line="'+line+'"][data-field="'+field+'"]');await inputValue(page,'[data-guided-input="'+field+'"]',value);};
const unchangedSources=async saved=>{assert.deepEqual(saved.sourceRefs,selected.sourceRefs);assert.equal(JSON.parse(saved.json).storage.unrelated,'EXACT_UNRELATED');assert.deepEqual(await sources.exportSource({projectId:initial.project.id,sourceId:ref.sourceId,version:ref.version}),sourceBytes);};
try{
 driver=await launchDesktop(packageCopy?{executable:join(packageCopy,receipt.appRelativePath),packaged:true}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+initial.project.id]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 const attach=async view=>{const page=await attachNativePage(driver,'siren://app/windows/'+view.role+'.html?windowId='+view.windowId);await page.waitFor('document.body.dataset.'+(view.role==='diagram'?'diagram':view.role==='docs'?'document':'source')+'Ready==="true"');return {view,page};};
 await driver.waitFor('document.getElementById("homeDiagramWindows")?.disabled===false');await driver.click('#homeDiagramWindows');await driver.waitFor('document.querySelector(".home-library [data-entity-id=flow]")!=null');await driver.click('.home-library [data-entity-id=flow]');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="diagram")})()');
 const reader=await attach((await driver.evaluate('window.sirenWindow.listViews()')).views.find(view=>view.role==='diagram'));await reader.page.waitFor('document.body.dataset.diagramRendered==="true"');
 assert.equal(await reader.page.evaluate('document.title'),'SIREN — Diagrams — Guided with imported colours · v1 · Read only');
 result.initialStyleDiagnostics=await reader.page.evaluate('(async()=>{const svg=document.querySelector("#diagramCanvas svg"),db=(await window.mermaid.mermaidAPI.getDiagramFromText(document.getElementById("diagramSource").value)).db;return {groups:Array.from(svg.querySelectorAll("g.node"),g=>({id:g.id,dataId:g.getAttribute("data-id"),nativeId:g.getAttribute("data-native-node-id"),shapes:Array.from(g.querySelectorAll("rect,polygon,path"),n=>({name:n.localName,fill:getComputedStyle(n).fill}))})),data:typeof db.getData==="function"?db.getData().nodes:null,vertices:typeof db.getVertices==="function"?Array.from(db.getVertices()):null}})()');await writeFile(join(evidence,'initial-style-diagnostics.json'),JSON.stringify(result.initialStyleDiagnostics,null,2));
 assert.equal(await reader.page.evaluate('getComputedStyle(document.querySelector("[data-native-node-id=B] rect")).fill'), 'rgb(34, 119, 204)');assert.equal(await reader.page.evaluate('getComputedStyle(document.querySelector("[data-native-node-id=A] rect")).fill'),'rgb(255, 51, 102)');await reader.page.click('#diagramStyleToggle');assert.equal(await reader.page.evaluate('document.getElementById("diagramStyleFont").disabled'),true);assert.equal(await reader.page.evaluate('document.getElementById("diagramPreviewTitle").textContent'),'Saved title');await reader.page.click('#diagramStyleToggle');await reader.page.click('#diagramGuidedMode');
 assert.equal(await reader.page.evaluate('document.querySelectorAll(".guided-row").length'),64);assert.equal(await reader.page.evaluate('Array.from(document.querySelectorAll(".guided-chip")).every(button=>button.disabled)'),true);assert.equal(await reader.page.evaluate('document.getElementById("diagramSource").value'),original.replaceAll('\r\n','\n'));assert.deepEqual(await projects.readProject(initial.project.id),selected);
 assert.equal((await reader.page.evaluate('window.sirenDiagramRead.getDiagram()')).diagram.source,original,'Exact CRLF source must be read from the genuine native transport, not the normalized textarea');
 const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(view=>view.windowId);await reader.page.click('#openWorkingDiagram');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>'+before.length+'})()');working=await attach((await driver.evaluate('window.sirenWindow.listViews()')).views.find(view=>!before.includes(view.windowId)));await working.page.waitFor('document.body.dataset.diagramReadonly==="false"');
 assert.equal(await working.page.evaluate('document.title'),'SIREN — Diagrams — Guided with imported colours · v1 · Working copy');
 for(const [role,entityId]of [['code',ref.sourceId],['docs','doc-a']]){const opened=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify({role,entityId,...(role==='code'?{version:ref.version}:{})})+')');assert.equal(opened.ok,true);await attach(opened.view);}
 await working.page.click('#diagramGuidedMode');assert.equal(await working.page.evaluate('document.querySelectorAll(".guided-row").length'),64);await working.page.click('#diagramGuided .guided-pages button:last-child');assert.equal(await working.page.evaluate('document.querySelector(".guided-row").dataset.guidedLine'),'64');assert.equal(await working.page.evaluate('document.querySelectorAll(".guided-row").length'),64);await working.page.click('#diagramGuided .guided-pages button:first-child');
 result.cases.push({name:'actual Home/readonly/working native Guided; finite 64-line pages and no readonly edits or project changes',ok:true});
 await inline(working.page,1,'fromId','bad id');await keys(working.page,'Enter','Enter',13);assert.equal(await working.page.evaluate('document.querySelector("[data-guided-input=fromId]").value'),'bad id');await driver.click('#homeLock');await working.page.waitFor('!document.body.inert&&document.documentElement.style.visibility!=="hidden"');assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked,true);assert.equal(await working.page.evaluate('document.querySelector("[data-guided-input=fromId]").value'),'bad id');assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),original.replaceAll('\r\n','\n'));assert.deepEqual(await projects.readProject(initial.project.id),selected);await unchangedSources(selected);await working.page.click('[data-guided-input=fromId]');await keys(working.page,'Escape','Escape',27);await working.page.waitFor('document.querySelector("[data-guided-input=fromId]")==null');
 result.cases.push({name:'real all-view Lock refuses invalid inline ID and restores exact tentative field; Escape cancels with whole project and Python source unchanged',ok:true});
 if(process.argv.includes('--trace-slow-cpu')){await working.page.send('Emulation.setCPUThrottlingRate',{rate:8});result.traceCpuRate=8;}
 await working.page.evaluate(`(()=>{window.__guidedSaveTrace=[];const snapshot=event=>{if(window.__guidedSaveTrace.length>=120)return;const button=document.getElementById('saveDiagram'),rect=button.getBoundingClientRect();window.__guidedSaveTrace.push({type:event.type,target:event.target.id||event.target.dataset.guidedInput||event.target.dataset.field||event.target.tagName,active:document.activeElement?.id||document.activeElement?.dataset.guidedInput||document.activeElement?.dataset.field||document.activeElement?.tagName,defaultPrevented:event.defaultPrevented,disabled:button.disabled,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},dirty:document.body.dataset.diagramDirty,version:document.body.dataset.diagramVersion});};for(const type of ['pointerdown','mousedown','blur','focus','pointerup','mouseup','click'])document.addEventListener(type,snapshot,true);})()`);
 await inline(working.page,1,'fromLabel','Context Ș😀');await working.page.waitFor('document.getElementById("saveDiagram").disabled===false');await working.page.click('#saveDiagram');await working.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="2"');
 result.guidedSaveTrace=await working.page.evaluate('window.__guidedSaveTrace??[]');
 const savePress=result.guidedSaveTrace.findIndex(event=>event.type==='pointerdown'&&event.target==='saveDiagram'),saveEvents=result.guidedSaveTrace.slice(savePress);
 assert.ok(savePress>=0&&saveEvents.some(event=>event.type==='click'&&event.target==='saveDiagram'),'One genuine pointer Save must reach its button');
 assert.ok(saveEvents.some(event=>event.type==='focus'&&event.target==='saveDiagram'),'Guided blur must let Save receive focus');
 assert.equal(saveEvents.some(event=>event.type==='focus'&&event.target==='fromLabel'),false,'Guided blur must not steal focus back from Save');
 if(result.traceCpuRate)await working.page.send('Emulation.setCPUThrottlingRate',{rate:1});
 const afterSave=original.replace('A[Original]-->B[Next]','A["Context Ș😀"] --> B[Next]'),expected=structuredClone(workspace);expected.diagrams[0]={...expected.diagrams[0],source:afterSave,sirenNativeVersion:2};const saved=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(saved),expected);await unchangedSources(saved);
 await working.page.waitFor('document.body.dataset.diagramRendered==="true"');assert.equal(await working.page.evaluate('Array.from(document.querySelectorAll("#diagramCanvas .node rect")).some(node=>getComputedStyle(node).fill==="rgb(255, 51, 102)")'),true,'Actual imported fill must remain rendered');assert.equal(await working.page.evaluate('document.getElementById("diagramViewport").getBoundingClientRect().height>innerHeight*.6'),true);
 await working.page.evaluate('document.getElementById("diagramTheme").value="light";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'guided-light.png'));await working.page.evaluate('document.getElementById("diagramTheme").value="dark";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'guided-dark.png'));await working.page.click('#diagramTextMode');assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),afterSave.replaceAll('\r\n','\n'));await working.page.click('#diagramGuidedMode');
 result.cases.push({name:'actual pending inline Save button commits one CRLF line, retains imported rendered fill and all metadata/source bytes; light/dark and Text roundtrip',ok:true});
 await inline(working.page,1,'toLabel','Decision');await keys(working.page,'s','KeyS',83,2);await working.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="3"');const afterKeyboard=afterSave.replace('B[Next]','B["Decision"]');expected.diagrams[0]={...expected.diagrams[0],source:afterKeyboard,sirenNativeVersion:3};assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);

 await inline(working.page,1,'fromLabel','Atomic source');await working.page.click('#diagramStyleToggle');
 await inputValue(working.page,'#diagramStyleTitle','Atomic title Ș😀');await working.page.click('#diagramStyleSize');await inputValue(working.page,'#diagramStyleSize','20');await working.page.click('#diagramStyleTarget');
 await working.page.evaluate('document.getElementById("diagramStyleTarget").value="B";document.getElementById("diagramStyleTarget").dispatchEvent(new Event("change"));document.getElementById("diagramStyle_fill").value="#12ab34";document.getElementById("diagramStyle_fill").dispatchEvent(new Event("change"))');
 await working.page.waitFor('document.body.dataset.diagramRendered==="true"');assert.equal(await working.page.evaluate('document.body.dataset.diagramVersion'),'3');assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);
 assert.equal(await working.page.evaluate('getComputedStyle(document.querySelector("[data-native-node-id=B] rect")).fill'),'rgb(18, 171, 52)');assert.equal(await working.page.evaluate('getComputedStyle(document.querySelector("[data-native-node-id=A] rect")).fill'),'rgb(255, 51, 102)');
 await working.page.evaluate('document.getElementById("diagramStyleTarget").value="A";document.getElementById("diagramStyleTarget").dispatchEvent(new Event("change"))');assert.equal(await working.page.evaluate('document.getElementById("diagramStyleUse_fill").disabled'),true);assert.equal(await working.page.evaluate('document.getElementById("diagramStyleUse_text").disabled'),true);
 await working.page.click('#saveDiagram');await working.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="4"');
 const atomicSource=afterKeyboard.replace('Context Ș😀','Atomic source');expected.diagrams[0]={...expected.diagrams[0],source:atomicSource,fontSize:20,diagramTitle:'Atomic title Ș😀',nodeStyles:{A:{fill:'#000000',text:'#000000'},B:{fill:'#12ab34',text:'#ffffff'}},sirenNativeVersion:4};
 assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);await unchangedSources(await projects.readProject(initial.project.id));
 await working.page.evaluate('document.getElementById("diagramTheme").value="light";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'styles-light.png'));await working.page.evaluate('document.getElementById("diagramTheme").value="dark";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'styles-dark.png'));await working.page.click('#diagramStyleToggle');
 result.cases.push({name:'actual saved metadata paints B and typography/title, source A owns fill/text; readonly controls refused; tentative source/style changes commit together once and preserve complete project/source bytes',ok:true});
 await working.page.click('#diagramStyleToggle');await inputValue(working.page,'#diagramStyleSize','200');await driver.click('#homeLock');await working.page.waitFor('!document.body.inert&&document.documentElement.style.visibility!=="hidden"');assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked,true);assert.equal(await working.page.evaluate('document.getElementById("diagramStyleSize").value'),'200');assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);await working.page.click('#diagramStyleSize');await keys(working.page,'Escape','Escape',27);assert.equal(await working.page.evaluate('document.getElementById("diagramStyleSize").value'),'20');await working.page.click('#diagramStyleToggle');result.cases.push({name:'actual invalid pending style makes common Lock refuse without losing its field or saved project; Escape restores saved size',ok:true});

 await working.page.click('#diagramBuildToggle');await working.page.click('[data-native-node-id=B]');assert.equal(await working.page.evaluate('document.getElementById("diagramBuildTarget").value'),'B');
 await inputValue(working.page,'#diagramBuildLabel','Visual decision');await working.page.click('#diagramBuildApply');await working.page.evaluate('document.getElementById("diagramBuildShape").value="diamond";document.getElementById("diagramBuildShape").dispatchEvent(new Event("change"))');await working.page.click('#diagramBuildApply');
 await inputValue(working.page,'#diagramBuildNewId','C');await inputValue(working.page,'#diagramBuildNewLabel','Review');await working.page.click('#diagramBuildAdd');await working.page.waitFor('document.body.dataset.diagramRendered==="true"&&document.querySelector("[data-native-node-id=C]")!=null');
 await working.page.evaluate('document.getElementById("diagramBuildTo").value="B";document.getElementById("diagramBuildTo").dispatchEvent(new Event("change"))');await inputValue(working.page,'#diagramBuildEdgeLabel','Review complete');await working.page.click('#diagramBuildConnect');await working.page.evaluate('document.getElementById("diagramBuildDirection").value="LR";document.getElementById("diagramBuildDirection").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');
 const buildSource=atomicSource.replace('flowchart TD','flowchart LR').replace('B["Decision"]','B{"Visual decision"}')+'C["Review"]\r\nC -->|"Review complete"| B\r\n';assert.equal(await working.page.evaluate('window.sirenDiagramRead.getDiagram().then(r=>r.version)'),4);assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),buildSource.replaceAll('\r\n','\n'));assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);
 await inputValue(working.page,'#diagramBuildNewId','PENDING');await driver.click('#homeLock');await working.page.waitFor('!document.body.inert&&document.documentElement.style.visibility!=="hidden"');assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked,true);assert.equal(await working.page.evaluate('document.getElementById("diagramBuildNewId").value'),'PENDING');assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);await working.page.click('#diagramBuildNewId');await keys(working.page,'Escape','Escape',27);
 await working.page.click('#saveDiagram');await working.page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="5"');expected.diagrams[0]={...expected.diagrams[0],source:buildSource,sirenNativeVersion:5};assert.deepEqual(workspaceMetadata(await projects.readProject(initial.project.id)),expected);await unchangedSources(await projects.readProject(initial.project.id));await working.page.screenshot(join(evidence,'build-dark.png'));await working.page.evaluate('document.getElementById("diagramTheme").value="light";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'build-light.png'));await working.page.click('#diagramBuildToggle');
 result.cases.push({name:'actual canvas pointer selects B, Build changes label/shape/adds C/connects and changes direction without writing; pending Add refuses Lock with fields retained; Save commits exact source once with all metadata/Docs/source bytes unchanged',ok:true});
 await inline(working.page,1,'fromLabel','Saved by Lock');await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(target=>target.url.startsWith('siren://app/windows/')),false);
 expected.diagrams[0]={...expected.diagrams[0],source:buildSource.replace('Atomic source','Saved by Lock'),sirenNativeVersion:6};const savedLock=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(savedLock),expected);await unchangedSources(savedLock);result.cases.push({name:'real Ctrl+S and all-view Lock durably commit pending valid inline fields, retire every Diagram/Code/Docs target and preserve unrelated data',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{result.runtimeLog=driver.logs().slice(-6000);if(working){result.diagnostics=await working.page.evaluate('({status:document.getElementById("viewStatus").textContent,body:{...document.body.dataset},source:document.getElementById("diagramSource").value,field:document.querySelector("[data-guided-input]")?.value})');await working.page.screenshot(join(evidence,'failure.png'));}else await driver?.screenshot(join(evidence,'failure.png'));}catch{}}
finally{if(working)try{result.guidedSaveTrace=await working.page.evaluate('window.__guidedSaveTrace??[]');}catch{}if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(receipt){result.packageAfter={archive:{sha256:hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar')))},runtime:await hashOwnedFile(join(packageCopy,receipt.appRelativePath),1024**3)};result.packageUnchanged=result.packageAfter.archive.sha256===receipt.appArchive.sha256&&JSON.stringify(result.packageAfter.runtime)===JSON.stringify(receipt.runtimeBinary);if(!result.packageUnchanged)result.status='ADVERSE';}if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
