import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
import {reserveInspectorPort,attachNativeKeyboard} from './native-keyboard.mjs';
import {waitForNativeCondition} from './condition.mjs';
const evidence=resolve('evidence/diagram-dock',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const hash=b=>createHash('sha256').update(b).digest('hex');
const paths=['src/main.mjs','src/windows/factory.mjs','src/windows/registry.mjs','src/windows/surface.mjs','src/windows/focus.mjs','src/windows/dock-ipc.mjs','src/windows/layout.mjs','src/windows/diagram-edits.mjs','src/windows/preload.cjs','src/ui/windows/diagram-transfer.js','src/ui/windows/diagram.js','src/ui/windows/shelf.js','src/ui/windows/shelf.css','build/diagram-window.mjs','generated/windows/diagram.html','generated/home.html','tests/native/diagram-dock.mjs','tests/native/native-keyboard.mjs','tests/native/drive.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async p=>[p,hash(await readFile(p))]))),inputs=await capture();
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let packageReceipt=null,packageCopy=null;
if(packageRoot){packageReceipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(packageReceipt.kind,'development-preview');assert.equal(packageReceipt.releaseAdmitted,false);packageCopy=join(evidence,'Pachet-Știință-Docking');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar'))),packageReceipt.appArchive.sha256);}
const data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Diagrams in the desktop workspace',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000;
const text=Array.from({length:lineCount},(_,i)=>'value_'+i+' = '+i+' # Ș😀').join('\n')+'\n',ref=await sources.importSource({projectId:initial.project.id,bytes:Buffer.from(text)});
const originalSource='flowchart TD\nA[Original] --> B[Next]\nstyle A fill:#12ab34,color:#ffffff',workspace={diagrams:[{id:'flow',name:'Exact diagram',source:originalSource,diagramTitle:'Retained title',nodeMetadata:{A:{agent:'PRIVATE_AGENT',sourceRef:{sourceId:ref.sourceId,version:1,sha256:ref.sha256}}}},{id:'other',name:'Other',source:'flowchart LR\nZ[Other diagram]'}],workpapers:[{id:'doc-a',title:'Exact context',blocks:[{id:'text-a',kind:'text',html:'<p>PRIVATE_DOCS unchanged</p>'}]}]},metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify(workspace),unrelated:'EXACT_UNRELATED'}};
assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'diagram-dock-fixture'})).ok,true);const selected=await projects.readProject(initial.project.id);
if(packageReceipt)await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));
const result={status:'ADVERSE',lineCount,inputs,cases:[],scope:'Actual same-renderer Diagram attachment, original native toolbar/keys/shelf, draft/selection/zoom/theme, Code/Docs peers, exact coordinated Close/Lock and source preservation. Presentation roles/physical monitors remain separate.'};let driver,native;
const keys=async(page,key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
const edit=async(page,text)=>{await page.click('#diagramSource');await keys(page,'a','KeyA',65,2);await page.send('Input.insertText',{text});await page.waitFor('document.body.dataset.diagramDirty==="true"');};
try{
 const port=await reserveInspectorPort();driver=await launchDesktop(packageCopy?{executable:join(packageCopy,packageReceipt.appRelativePath),packaged:true,extraArgs:[`--inspect=127.0.0.1:${port}`]}:{extraArgs:[`--siren-test-root=${data}`,`--siren-test-project=${initial.project.id}`,`--inspect=127.0.0.1:${port}`]});native=await attachNativeKeyboard({port,pid:driver.pid});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 const attach=async view=>{const url=`siren://app/windows/${view.role}.html?windowId=${view.windowId}`,page=await attachNativePage(driver,url);await page.waitFor(`document.body.dataset.${view.role==='diagram'?'diagram':view.role==='code'?'source':'document'}Ready==='true'`);return {view,page,url};};
 const open=async(role,entityId)=>{const r=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify({role,entityId,...(role==='code'?{version:1}:{})})+')');assert.equal(r.ok,true);return attach(r.view);};
 const reader=await open('diagram','flow'),other=await open('diagram','other'),code=await open('code',ref.sourceId),docs=await open('docs','doc-a');
 const opened=await reader.page.evaluate('window.sirenDiagramEdit.openWorkingCopy()');assert.equal(opened.ok,true);const working=await attach(opened.view);await working.page.waitFor('document.body.dataset.diagramReadonly==="false"');
 const all=[reader,other,working],before=await Promise.all(all.map(item=>native.surfaceState(item.url)));
 assert.ok(before.every(s=>s.nativeClass==='BaseWindow'&&s.parents.length===1));
 const draft=originalSource.replace('Original','Unsaved Ș😀');await edit(working.page,draft);await working.page.click('#diagramZoomIn');await working.page.click('#diagramZoomIn');
 await working.page.click('#diagramSource');
 await working.page.evaluate('document.getElementById("diagramTheme").value="dark";document.getElementById("diagramTheme").dispatchEvent(new Event("change"));document.getElementById("diagramSource").setSelectionRange(3,12);globalThis.__dockIdentity={node:document.getElementById("diagramSource"),time:performance.timeOrigin,transform:document.getElementById("diagramCanvas").style.transform};true');
 assert.deepEqual(await working.page.evaluate('(()=>{const e=document.getElementById("diagramSource");return [document.activeElement===e,e.selectionStart,e.selectionEnd];})()'),[true,3,12]);
 for(const item of all)if(item!==working)await item.page.evaluate('globalThis.__dockIdentity={node:document.getElementById("diagramSource"),time:performance.timeOrigin};true');
 for(let cycle=0;cycle<3;cycle++)for(const item of all){
  await item.page.waitFor('!document.getElementById("transferView").hidden&&document.body.dataset.nativePlacement==="detached"');await item.page.click('#transferView');await item.page.waitFor('document.body.dataset.nativePlacement==="attached"');
  const current=await native.surfaceState(item.url),old=before[all.indexOf(item)];for(const key of ['nativeId','contentsId','frameRoutingId','frameProcessId'])assert.equal(current[key],old[key],key);
  assert.equal(current.parents.length,1);assert.equal(current.parents[0].bounds.y,48);assert.equal(current.parents[0].drawn,true);assert.equal(current.visible,false);
  assert.equal(await item.page.evaluate('__dockIdentity.node===document.getElementById("diagramSource")&&__dockIdentity.time===performance.timeOrigin'),true);
  if(cycle<2){await native.windowShortcut(item.url,'D');await item.page.waitFor('document.body.dataset.nativePlacement==="detached"');}
 }
 const current=await Promise.all(all.map(item=>native.surfaceState(item.url)));assert.equal(current.filter(s=>s.parents[0].drawn).length,1);
 assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),draft);assert.deepEqual(await working.page.evaluate('(()=>{const e=document.getElementById("diagramSource");return [e.selectionStart,e.selectionEnd];})()'),[3,12]);
 assert.equal(await working.page.evaluate('document.getElementById("diagramCanvas").style.transform===__dockIdentity.transform&&document.getElementById("diagramTheme").value==="dark"'),true);assert.deepEqual(await projects.readProject(initial.project.id),selected);
 result.cases.push({name:'nine real toolbar attachments and native detach preserve three exact Diagram renderers/frames, draft/selection/zoom/theme; only selected native view drawn, no project save',ok:true});
 assert.equal((await working.page.evaluate('window.sirenWindowDock.detach('+JSON.stringify({windowId:code.view.windowId})+')')).code,'ACCESS_REFUSED');
 assert.equal((await code.page.evaluate('window.sirenDiagramEdit.openWorkingCopy()')).ok,false);assert.equal((await docs.page.evaluate('window.sirenDiagramRead.getDiagram()')).ok,false);
 await driver.waitFor('document.querySelectorAll("#nativeWindowShelf [data-window-id]").length===5');assert.equal(await driver.evaluate('Array.from(document.querySelectorAll("#nativeWindowShelf [data-window-id]")).filter(e=>e.textContent.startsWith("Diagrams ")).length'),3);
 await driver.click('#nativeWindowShelf [data-window-id="'+code.view.windowId+'"]');assert.equal((await native.surfaceState(working.url)).parents[0].drawn,true,'Detached Code restores without selecting a different attached view');
 await driver.click('#nativeWindowShelf [data-window-id="'+working.view.windowId+'"]');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');
 assert.equal(await working.page.evaluate('document.getElementById("diagramCanvas").textContent.includes("PRIVATE_DOCS")'),false);assert.deepEqual(await projects.readProject(initial.project.id),selected);
 result.cases.push({name:'shared shelf labels Diagram/Code/Docs distinctly and restores peers; Diagram cannot borrow another view ID, wrong-role diagram read/edit refused',ok:true});
 await native.placeView('siren://app/home.html',{x:40,y:40,width:1120,height:780});const bounds=(await native.surfaceState('siren://app/home.html')).contentBounds;
 await working.page.waitFor('innerWidth==='+bounds.width);assert.deepEqual((await native.surfaceState(working.url)).parents[0].bounds,{x:0,y:48,width:bounds.width,height:bounds.height-48});await working.page.screenshot(join(evidence,'diagram-attached-dark.png'));
 await native.windowShortcut(working.url,'D');await working.page.waitFor('document.body.dataset.nativePlacement==="detached"');await native.windowShortcut(working.url,'A');await working.page.waitFor('document.body.dataset.nativePlacement==="attached"');
 await working.page.evaluate('document.getElementById("diagramTheme").value="light";document.getElementById("diagramTheme").dispatchEvent(new Event("change"))');await working.page.waitFor('document.body.dataset.diagramRendered==="true"');await working.page.screenshot(join(evidence,'diagram-attached-light.png'));
 assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),draft);await working.page.click('#diagramFit');assert.equal(await working.page.evaluate('document.getElementById("diagramZoom").textContent'),'100%');assert.equal(await working.page.evaluate('document.getElementById("diagramSource").value'),draft);result.cases.push({name:'actual host resize fits same Diagram below shelf; native CtrlAltD/A route restores same dirty diagram and light/dark preview; explicit Fit resets zoom without editing source',ok:true});
 await native.closeShortcut('siren://app/home.html','W');await waitForNativeCondition(async()=>{const r=await driver.evaluate('window.sirenWindow.listViews()');return r.ok&&!r.views.some(v=>v.windowId===working.view.windowId)&&await driver.evaluate('!document.body.inert');},'Attached dirty Diagram Close must save and destroy current view');
 const saved=await projects.readProject(initial.project.id),expected=structuredClone(workspace);expected.diagrams[0]={...expected.diagrams[0],source:draft,sirenNativeVersion:2};assert.deepEqual(workspaceMetadata(saved),expected);assert.deepEqual(saved.sourceRefs,selected.sourceRefs);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url===working.url),false);
 result.cases.push({name:'actual main CtrlW closes only selected attached dirty Diagram after exact source save; complete metadata, Docs and original large-source references retained',ok:true});
 await driver.waitFor('document.querySelector('+JSON.stringify('#nativeWindowShelf [data-window-id="'+reader.view.windowId+'"]')+')!=null'); await driver.click('#nativeWindowShelf [data-window-id="'+reader.view.windowId+'"]');assert.equal((await native.surfaceState(reader.url)).parents[0].drawn,true);await reader.page.waitFor('document.hasFocus()&&!document.body.inert');await reader.page.click('#refreshDiagram');await reader.page.waitFor('document.body.dataset.diagramVersion==="2"');assert.equal(await reader.page.evaluate('document.getElementById("diagramSource").value'),draft);const nextOpened=await reader.page.evaluate('window.sirenDiagramEdit.openWorkingCopy()');assert.equal(nextOpened.ok,true);const next=await attach(nextOpened.view);await next.page.waitFor('document.body.dataset.diagramReadonly==="false"');const lockDraft=draft.replace('Next','Saved by Lock');await edit(next.page,lockDraft);await next.page.waitFor('!document.getElementById("transferView").hidden');await next.page.click('#transferView');await next.page.waitFor('document.body.dataset.nativePlacement==="attached"');
 await driver.click('#nativeWindowShelf button:first-child');await driver.waitFor('(async()=>{const r=await window.sirenWindowDock.getShelf();return r.ok&&r.items.every(v=>!v.selected);})()');await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');
 assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);assert.equal((await driver.evaluate('window.sirenWindowDock.getShelf()')).ok,false);
 expected.diagrams[0]={...expected.diagrams[0],source:lockDraft,sirenNativeVersion:3};const final=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(final),expected);assert.deepEqual(final.sourceRefs,selected.sourceRefs);assert.equal(JSON.parse(final.json).storage.unrelated,'EXACT_UNRELATED');assert.deepEqual(await sources.exportSource({projectId:initial.project.id,sourceId:ref.sourceId,version:1}),Buffer.from(text));
 result.cases.push({name:'real shared Lock saves attached dirty Diagram, destroys all attached/detached renderers and hidden shells, clears locked shelf and preserves exact complete project/large Python source',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};await driver?.screenshot(join(evidence,'failure.png')).catch(()=>{});result.runtimeLog=driver?.logs().slice(-6000);}
finally{native?.close();if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';if(packageReceipt){result.package={sourceCommit:packageReceipt.sourceCommit,archive:packageReceipt.appArchive,runtime:packageReceipt.runtimeBinary};result.packageUnchanged=hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar')))===packageReceipt.appArchive.sha256;if(!result.packageUnchanged)result.status='ADVERSE';}await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
