import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,readdir,lstat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {join,resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {RecoveryStore} from '../../src/recovery/checkpoints.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {AppearanceStore} from '../../src/appearance/store.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
import {copiedPackageContext} from './package-context.mjs';

// Actual Diagram controls, drafts, finite domain CAS and exact owned readback.
// No product handlers, DOM.value, synthetic DOM events or persistence adapters.
const root=resolve('.'),evidence=resolve('evidence/diagram-layout-native',new Date().toISOString().replaceAll(':','-'));
await mkdir(evidence,{recursive:true});
const hash=b=>createHash('sha256').update(b).digest('hex');
const hashFile=async path=>{const digest=createHash('sha256');for await(const chunk of createReadStream(path))digest.update(chunk);return digest.digest('hex');};
async function capture(){const paths=[];async function walk(path){const entry=await lstat(path);assert.equal(entry.isSymbolicLink(),false);if(entry.isDirectory()){for(const name of(await readdir(path)).sort())await walk(join(path,name));}else if(entry.isFile())paths.push(path);}for(const name of ['src','build','generated','tests','baseline','package.json','package-lock.json'])await walk(join(root,name));paths.push(join(root,'node_modules/electron/dist/electron.exe'));return Object.fromEntries(await Promise.all(paths.sort().map(async path=>[relative(root,path).replaceAll('\\','/'),await hashFile(path)])));}
const keys=async(page,key,code,windowsVirtualKeyCode,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode,modifiers,...(type==='keyDown'&&key==='Enter'?{text:'\r',unmodifiedText:'\r'}:{})});};
const click=async(page,selector)=>{await page.evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'})`);await page.click(selector);};
const replace=async(page,selector,value)=>{await click(page,selector);await keys(page,'a','KeyA',65,2);await page.send('Input.insertText',{text:value});};
async function choose(page,selector,value,{refusedValue}={}){
 const options=await page.evaluate(`Array.from(document.querySelector(${JSON.stringify(selector)}).options).filter(o=>!o.disabled).map(o=>o.value)`),index=options.indexOf(value);assert.ok(index>=0&&options.length<=64,'Bounded real select option must exist');
 await click(page,selector);await keys(page,'Escape','Escape',27);const end=index>options.length/2;await keys(page,end?'End':'Home',end?'End':'Home',end?35:36);
 for(let i=0;i<(end?options.length-1-index:index);i++)await keys(page,end?'ArrowUp':'ArrowDown',end?'ArrowUp':'ArrowDown',end?38:40);
 await keys(page,'Tab','Tab',9);await page.waitFor(`document.querySelector(${JSON.stringify(selector)}).value===${JSON.stringify(refusedValue??value)}`);
}

const result={status:'ADVERSE',author:'/root',executor:process.env.GITHUB_ACTIONS==='true'?'GitHub Actions':'/root',startedAt:new Date().toISOString(),cases:[],scope:'Actual native layout select, distinct engine geometry, source precedence, exact domain save/history/readback and common Lock. No physical-monitor/IME/hosted/release claim.'};
let driver,working,packaged,phase='fixture';
try{
 result.harness={path:'tests/native/diagram-layout.mjs',sha256:await hashFile(join(root,'tests/native/diagram-layout.mjs'))};packaged=await copiedPackageContext(evidence);const data=packaged?.data??join(evidence,'owned-data');await mkdir(data,{recursive:true});result.inputs=await capture();
 const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Owned layout proof',json:'{}'}),sourceBytes=Buffer.from('# retained Python\r\nprint(1494)\r\n'),ref=await sources.importSource({projectId:initial.project.id,bytes:sourceBytes});
 const originalSource='flowchart TD\nA[Original]-->B[Branch]\nA-->C[Other]\nB-->D[Join]\nC-->D\nB-->E[End]\nD-->E\nstyle A fill:#ff3366,color:#ffffff';
 const workspace={diagrams:[{id:'flow-a',name:'Layout proof',source:originalSource,opaque:'EXACT_DIAGRAM',nodeMetadata:{A:{private:'EXACT_AGENT'}},presentation:{notes:{overview:{text:'PRIVATE_NOTES'}}}},{id:'flow-peer',name:'Source layout',source:'---\nconfig:\n  layout: dagre\n---\n'+originalSource,sirenNativeLayoutEngine:'elk',opaque:'EXACT_PEER'},{id:'sequence-a',name:'Other grammar',source:'sequenceDiagram\nA->>B: Exact'}],workpapers:[{id:'doc-a',title:'EXACT_DOC',blocks:[],releases:[{author:'Actual author',verdict:'not-run'}]}],codeFiles:[]};
 const metadata={kind:'siren-desktop',schema:2,storage:{'t-industries-siren-v23-state':JSON.stringify(workspace),unrelated:'EXACT_STORAGE'}};assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'layout-fixture'})).ok,true);const selected=await projects.readProject(initial.project.id);
 await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));await new AppearanceStore(data).set({theme:'kpmg'});
 phase='startup';driver=await launchDesktop({...packaged?.launch,extraArgs:!packaged?['--siren-test-root='+data]:[]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 const views=async()=>(await driver.evaluate('window.sirenWindow.listViews()')).views;
 const attach=async view=>{const page=await attachNativePage(driver,'siren://app/windows/diagram.html?windowId='+view.windowId);await page.waitFor('document.body.dataset.diagramReady==="true"&&document.body.dataset.diagramRendered==="true"');return{page,view};};
 const openReader=async entityId=>{const opened=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify({role:'diagram',entityId})+')');assert.equal(opened.ok,true);return attach(opened.view);};
 const openWorking=async reader=>{const previous=(await views()).map(v=>v.windowId);await click(reader.page,'#openWorkingDiagram');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="diagram"&&!'+JSON.stringify(previous)+'.includes(v.windowId));})()');return attach((await views()).find(v=>!previous.includes(v.windowId)));};
 const reader=await openReader('flow-a');await click(reader.page,'#diagramStyleToggle');assert.equal(await reader.page.evaluate('document.getElementById("diagramStyleLayout").disabled'),true);working=await openWorking(reader);const page=working.page;await click(page,'#diagramStyleToggle');assert.equal(await page.evaluate('document.getElementById("diagramStyleLayout").value'),'auto');assert.equal(await page.evaluate('document.getElementById("diagramStyleLayout").disabled'),false);
 const geometry=()=>page.evaluate('JSON.stringify(Array.from(document.querySelectorAll("#diagramCanvas .node"),n=>({id:n.getAttribute("data-native-node-id"),transform:n.getAttribute("transform"),box:(()=>{const b=n.getBBox();return{x:b.x,y:b.y,width:b.width,height:b.height};})()})))');
 const colour=()=>page.evaluate('getComputedStyle(document.querySelector("[data-native-node-id=A] rect")).fill');const idle=()=>page.waitFor('document.body.dataset.diagramRendered==="true"');
 phase='engine-select';await choose(page,'#diagramStyleLayout','dagre');await idle();const standard=await geometry();assert.equal(await colour(),'rgb(255, 51, 102)');await choose(page,'#diagramStyleLayout','elk');await idle();const elk=await geometry();assert.notEqual(standard,elk,'Actual nodes must be laid out differently, not merely change a select label');assert.equal(await colour(),'rgb(255, 51, 102)');assert.deepEqual(await projects.readProject(initial.project.id),selected);result.geometry={standard,elk};result.cases.push({name:'Actual readonly refusal and real keyboard engine selection change preview geometry with imported fill exact, no automatic persistence',ok:true});
 phase='history';await click(page,'#diagramUndo');await idle();assert.equal(await page.evaluate('document.getElementById("diagramStyleLayout").value'),'dagre');assert.equal(await geometry(),standard);await click(page,'#diagramRedo');await idle();assert.equal(await geometry(),elk);await click(page,'#saveDiagram');await page.waitFor('document.body.dataset.diagramDirty==="false"&&document.body.dataset.diagramVersion==="2"');const expected=structuredClone(workspace);expected.diagrams[0]={...expected.diagrams[0],sirenNativeLayoutEngine:'elk',sirenNativeVersion:2};const saved=await projects.readProject(initial.project.id);assert.deepEqual(workspaceMetadata(saved),expected);assert.deepEqual(saved.sourceRefs,selected.sourceRefs);assert.deepEqual(await sources.exportSource({projectId:initial.project.id,...ref}),sourceBytes);assert.equal(JSON.parse(saved.json).storage.unrelated,'EXACT_STORAGE');result.cases.push({name:'Native Undo/Redo restore engine geometry; one exact CAS Save retains source/metadata/other diagrams/Docs/source refs and Python bytes',ok:true});
 phase='source-owned';const peer=await openWorking(await openReader('flow-peer'));await click(peer.page,'#diagramStyleToggle');assert.equal(await peer.page.evaluate('document.getElementById("diagramStyleLayout").disabled'),true);assert.match(await peer.page.evaluate('document.getElementById("diagramStyleLayout").title'),/Mermaid/);const other=await openWorking(await openReader('sequence-a'));await click(other.page,'#diagramStyleToggle');assert.equal(await other.page.evaluate('document.getElementById("diagramStyleLayout").disabled'),true);assert.match(await other.page.evaluate('document.getElementById("diagramStyleLayout").title'),/diagram type/);assert.deepEqual(await projects.readProject(initial.project.id),saved);result.cases.push({name:'Imported frontmatter layout owns actual native picker; unsupported grammar honestly disabled; saved preference/source and siblings remain exact',ok:true});
 phase='reopen-lock';const reopened=await openReader('flow-a');await click(reopened.page,'#diagramStyleToggle');assert.equal(await reopened.page.evaluate('document.getElementById("diagramStyleLayout").value'),'elk');await page.screenshot(join(evidence,'layout-native.png'));await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);assert.deepEqual(await projects.readProject(initial.project.id),saved);result.cases.push({name:'Saved engine returns in new native reader and common Lock retires all native windows without changing the clean saved project',ok:true});result.status='COMPLETE';
}catch(cause){result.error={phase,message:cause.message,stack:cause.stack};try{result.runtimeLog=driver?.logs().slice(-6000);result.observed=await working?.page.evaluate('({body:{...document.body.dataset},status:document.getElementById("viewStatus")?.textContent,layout:document.getElementById("diagramStyleLayout")?.value,disabled:document.getElementById("diagramStyleLayout")?.disabled})');await(working?.page??driver)?.screenshot(join(evidence,'failure.png'));}catch{}}
finally{await driver?.close();result.afterInputs=await capture();result.changedInputs=Object.keys({...result.inputs,...result.afterInputs}).filter(p=>result.inputs?.[p]!==result.afterInputs[p]);if(result.changedInputs.length)result.status='ADVERSE';if(packaged){result.package={sourceCommit:packaged.receipt.sourceCommit,copy:packaged.copy,archive:packaged.receipt.appArchive,runtime:packaged.receipt.runtimeBinary};try{await packaged.verify();result.packageUnchanged=true;}catch(cause){result.packageUnchanged=false;result.packageError=cause.message;result.status='ADVERSE';}}result.endedAt=new Date().toISOString();await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,changedInputs:result.changedInputs,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
