import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
const evidence=resolve('evidence/docs-sources',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),packageAt=process.argv.indexOf('--package');let receipt=null,packageCopy=null;
if(packageAt>=0){const root=resolve(process.argv[packageAt+1]);receipt=JSON.parse(await readFile(join(root,'BUILD-IDENTITY.json'),'utf8'));assert.equal(receipt.kind,'development-preview');assert.equal(receipt.releaseAdmitted,false);packageCopy=join(evidence,'Pachet-Știință-Code');await cp(root,packageCopy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar'))),receipt.appArchive.sha256);}
const paths=['src/main.mjs','src/windows/docs-sources.mjs','src/windows/docs-reads.mjs','src/windows/preload.cjs','src/ui/windows/docs.js','src/ui/windows/code.js','build/windows.mjs','generated/windows/docs.html','generated/windows/code.html','tests/native/docs-sources.mjs','tests/native/drive.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture(),data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const projects=new ProjectStore(data),sources=new SourceRepository(data),first=await projects.createProject({label:'Docs exact historical code',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000;
const text=Array.from({length:lineCount},(_,i)=>`saved_${i} = ${i} # Ș😀`).join('\r\n')+'\r\n',ref=await sources.importSource({projectId:first.project.id,bytes:Buffer.from(text)}),point={sourceId:ref.sourceId,version:1,sha256:ref.sha256};
assert.equal((await sources.applyEdit({projectId:first.project.id,edit:{sourceId:ref.sourceId,expectedVersion:1,operationId:'newer-source-head',start:0,end:0,insertedText:'# NEWER HEAD\n'}})).ok,true);const newer=await sources.getMetrics({projectId:first.project.id,sourceId:ref.sourceId});assert.equal(newer.version,2);
const metadata={workpapers:[{id:'agent-doc',title:'Agent documentation',blocks:[{id:'knowledge-a',kind:'knowledge',rows:[{id:'row-a',name:'agent.py Ș😀 <literal>',sourceRef:point}]}]},{id:'private-doc',title:'Other agent',private:'PRIVATE_OTHER_AGENT'}],codeFiles:[{id:'code-a',name:'agent.py',sourceRef:point}],unrelated:'EXACT_UNRELATED'};
assert.equal((await commitManifest({projects,repository:sources,projectId:first.project.id,baseRevision:1,sourceRefs:[ref,newer],metadata,operationId:'docs-source-native'})).ok,true);const before=await projects.readProject(first.project.id);
const result={status:'ADVERSE',lineCount,utf8Bytes:Buffer.byteLength(text),sourceSha256:point.sha256,newerSourceSha256:newer.sha256,inputs,cases:[],scope:'Actual Docs-to-Code saved historical version, Light/Dark source card, dirty draft preservation, concurrent document refusal, immutable source authority and common Lock. No physical monitor qualification.'};let driver,activePage;
if(receipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:first.project.id}));result.package={sourceCommit:receipt.sourceCommit,archive:receipt.appArchive,runtime:receipt.runtimeBinary};}
const keys=async(page,key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
const replace=async(page,selector,value)=>{await page.click(selector);await keys(page,'a','KeyA',65,2);await page.send('Input.insertText',{text:value});};
try{
 driver=await launchDesktop(packageCopy?{executable:join(packageCopy,receipt.appRelativePath),packaged:true}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+first.project.id]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 await driver.waitFor('document.getElementById("homeModule-docs")?.disabled===false');await driver.click('#homeModule-docs');await driver.waitFor('document.querySelector(".home-library [data-entity-id=agent-doc]")!=null');await driver.click('.home-library [data-entity-id=agent-doc]');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="docs")})()');
 const docView=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>v.role==='docs'),doc=await attachNativePage(driver,'siren://app/windows/docs.html?windowId='+docView.windowId);await doc.waitFor('document.body.dataset.documentReady==="true"&&document.querySelectorAll(".document-source-open").length===1');
 assert.equal(await doc.evaluate('document.querySelector(".document-source strong").textContent'),'agent.py Ș😀 <literal>');assert.equal(await doc.evaluate('document.querySelector(".document-source literal")'),null);assert.equal(await doc.evaluate('document.getElementById("documentContent").textContent.includes("PRIVATE_OTHER_AGENT")'),false);
 assert.equal(await doc.evaluate('document.querySelectorAll(".document-source-preview-toggle").length'),1,'Linked source has an explicit native preview control');
 const previewWindows=(await driver.evaluate('window.sirenWindow.listViews()')).views;await doc.click('.document-source-preview-toggle');await doc.waitFor('document.querySelector(".document-source-preview")?.dataset.previewReady==="true"');
 const readPreview=page=>page.evaluate('(()=>{const p=document.querySelector(".document-source-preview");return {text:p.querySelector("pre").textContent,start:Number(p.dataset.previewStart),end:Number(p.dataset.previewEnd),total:Number(p.dataset.previewTotal)}})()');
 const preview=await readPreview(doc);assert.equal(preview.start,0);assert.equal(preview.total,text.length);assert.ok(preview.end<=8192);assert.equal(preview.text,text.slice(0,preview.end));assert.equal(preview.text.includes('NEWER HEAD'),false);assert.equal(preview.text.isWellFormed(),true);assert.deepEqual((await driver.evaluate('window.sirenWindow.listViews()')).views,previewWindows);assert.deepEqual(await projects.readProject(first.project.id),before);
 await doc.click('.document-preview-next');await doc.waitFor('Number(document.querySelector(".document-source-preview").dataset.previewStart)>0&&document.querySelector(".document-source-preview").dataset.previewReady==="true"');const next=await readPreview(doc);assert.equal(next.start,preview.end);assert.equal(next.text,text.slice(next.start,next.end));assert.ok(next.end-next.start<=8192);await doc.click('.document-preview-previous');await doc.waitFor('document.querySelector(".document-source-preview").dataset.previewStart==="0"&&document.querySelector(".document-source-preview").dataset.previewReady==="true"');assert.deepEqual(await readPreview(doc),preview);
 await doc.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'light'}]});await doc.screenshot(join(evidence,'docs-code-light.png'));await doc.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'dark'}]});await doc.screenshot(join(evidence,'docs-code-dark.png'));
 await doc.click('.document-source-preview-toggle');assert.equal(await doc.evaluate('document.querySelector(".document-source-preview").hidden'),true);assert.equal(await doc.evaluate('document.querySelector(".document-source-preview pre").textContent'),'');result.cases.push({name:'actual large Docs source preview pages retain exact historical UTF-16 ranges and Unicode, match both themes, open no window and clear hidden text',ok:true});
 const openLinked=async page=>{const previous=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(v=>v.windowId);await page.click('#documentOutline button');await page.waitFor('(()=>{const e=document.querySelector(".document-source-open"),r=e?.getBoundingClientRect();return r&&r.top>=0&&r.bottom<=innerHeight})()');await page.click('.document-source-open');await page.waitFor('document.getElementById("viewStatus").textContent.includes("opened")');const views=(await driver.evaluate('window.sirenWindow.listViews()')).views,view=views.find(v=>!previous.includes(v.windowId));assert.equal(view.role,'code');const code=await attachNativePage(driver,'siren://app/windows/code.html?windowId='+view.windowId);await code.waitFor('document.body.dataset.sourceReady==="true"');return code;};
 const code=await openLinked(doc);assert.equal(await code.evaluate('document.body.dataset.sourceVersion'),'1');assert.equal(await code.evaluate('document.body.dataset.sourceSha256'),point.sha256);assert.equal(await code.evaluate('document.body.dataset.sourceLines'),String(lineCount+1));assert.equal(await code.evaluate('document.body.dataset.sourceReadonly'),'true');assert.equal((await code.evaluate('window.sirenDocsSources.openLinkedSource({blockId:"knowledge-a",rowId:"row-a",expectedDocumentVersion:"'+before.sha256+'"})')).code,'ACCESS_REFUSED');
 assert.equal((await code.evaluate('window.sirenSource.applyEdit('+JSON.stringify({sourceId:ref.sourceId,expectedVersion:1,operationId:'forbidden-native-write',start:0,end:0,insertedText:'oops'})+')')).code,'ACCESS_REFUSED');assert.deepEqual(await sources.exportSource({projectId:first.project.id,...point}),Buffer.from(text));assert.deepEqual(await projects.readProject(first.project.id),before);
 result.cases.push({name:'actual large saved Docs pointer opens immutable Code version1 despite native source head2, literal labels and other-agent privacy; cannot borrow Docs or source write authority',ok:true});
 await doc.click('#openWorkingDocument');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.filter(v=>v.role==="docs").length===2})()');const workingView=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>v.role==='docs'&&v.windowId!==docView.windowId),editor=await attachNativePage(driver,'siren://app/windows/docs.html?windowId='+workingView.windowId);await editor.waitFor('document.body.dataset.documentReadonly==="false"&&document.querySelector(".document-source-open")!=null');
 activePage=editor;await replace(editor,'#documentTitleInput','Local unsaved title');await editor.click('#documentOutline button');await editor.waitFor('(()=>{const e=document.querySelector(".document-source-preview-toggle"),r=e?.getBoundingClientRect();return r&&r.top>=0&&r.bottom<=innerHeight&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})()');await editor.click('.document-source-preview-toggle');await editor.waitFor('document.querySelector(".document-source-preview")?.dataset.previewReady==="true"');assert.deepEqual(await readPreview(editor),preview);assert.equal(await editor.evaluate('document.getElementById("documentTitleInput").value'),'Local unsaved title');assert.equal(await editor.evaluate('document.body.dataset.documentDirty'),'true');assert.deepEqual(await projects.readProject(first.project.id),before);await editor.click('.document-source-preview-toggle');
 const second=await openLinked(editor);assert.equal(await second.evaluate('document.body.dataset.sourceVersion'),'1');assert.equal(await editor.evaluate('document.getElementById("documentTitleInput").value'),'Local unsaved title');assert.equal(await editor.evaluate('document.body.dataset.documentDirty'),'true');assert.deepEqual(await projects.readProject(first.project.id),before);
 result.cases.push({name:'actual working Docs opens exact saved code in another window while retaining unsaved title and untouched manifest',ok:true});
 await editor.click('#saveDocument');await editor.waitFor('document.body.dataset.documentDirty==="false"');const saved=await projects.readProject(first.project.id);assert.equal(JSON.parse(saved.json).workpapers[0].title,'Local unsaved title');
 const count=(await driver.evaluate('window.sirenWindow.listViews()')).views.length;await doc.click('.document-source-preview-toggle');await doc.waitFor('document.querySelector(".document-preview-paging").textContent.includes("saved document changed")');assert.equal(await doc.evaluate('document.querySelector(".document-source-preview pre").textContent'),'');await doc.click('.document-source-preview-toggle');await doc.click('.document-source-open');await doc.waitFor('document.getElementById("viewStatus").textContent.includes("saved document changed")');assert.equal((await driver.evaluate('window.sirenWindow.listViews()')).views.length,count);assert.equal(await code.evaluate('document.body.dataset.sourceVersion'),'1');assert.deepEqual(await projects.readProject(first.project.id),saved);
 await doc.click('#retryDocument');await doc.waitFor('document.body.dataset.documentReady==="true"&&document.getElementById("viewTitle").textContent==="Docs · Local unsaved title"');const third=await openLinked(doc);assert.equal(await third.evaluate('document.body.dataset.sourceVersion'),'1');result.cases.push({name:'actual concurrent Docs save refuses stale readonly source button without opening a window; explicit refresh admits original exact historical version',ok:true});
 await driver.waitFor('document.getElementById("homeLock")?.disabled===false');await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal((await driver.send('Target.getTargets')).targetInfos.some(target=>target.url.startsWith('siren://app/windows/')),false);assert.deepEqual(await projects.readProject(first.project.id),saved);assert.deepEqual(await sources.exportSource({projectId:first.project.id,...point}),Buffer.from(text));assert.equal((await sources.getMetrics({projectId:first.project.id,sourceId:ref.sourceId})).sha256,newer.sha256);result.cases.push({name:'actual shared Lock closes all Docs and pinned Code windows and preserves historical source, newer head, saved Docs and other agent',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{await driver?.screenshot(join(evidence,'failure.png'));result.runtimeLog=driver?.logs().slice(-6000);if(activePage){await activePage.screenshot(join(evidence,'failure-active.png'));result.activeControls=await activePage.evaluate('(()=>{const e=document.querySelector(".document-source-preview-toggle"),r=e?.getBoundingClientRect(),h=r&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {width:innerWidth,height:innerHeight,ready:document.body.dataset.documentReady,inert:document.body.inert,rect:r?{x:r.x,y:r.y,width:r.width,height:r.height}:null,cover:h?.id||h?.className||h?.tagName,outline:Array.from(document.querySelectorAll("#documentOutline button"),e=>({label:e.textContent,hidden:e.hidden}))};})()');}}catch{}}
finally{await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
