import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {documentVersion} from '../../src/windows/docs.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
import {waitForHomeModule} from './home-ready.mjs';
const evidence=resolve('evidence/docs-format',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let packageReceipt=null,packageCopy=null;
if(packageRoot){packageReceipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(packageReceipt.kind,'development-preview');assert.equal(packageReceipt.releaseAdmitted,false);packageCopy=join(evidence,'Pachet-Știință-Docs');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});assert.equal(createHash('sha256').update(await readFile(join(packageCopy,'App/versions/0.1.0/resources/app.asar'))).digest('hex'),packageReceipt.appArchive.sha256);}
const data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const paths=['src/ui/windows/identity.js','src/windows/source-reads.mjs','build/import-validation.mjs','generated/import-validation.html','src/sources/repository.mjs','src/sources/recovery.mjs','src/main.mjs','src/windows/factory.mjs','src/windows/surface.mjs','src/windows/registry.mjs','src/windows/domain.mjs','src/windows/docs-edits.mjs','src/windows/docs-reads.mjs','src/windows/coordinator.mjs','src/windows/primary.mjs','src/windows/source-barrier.mjs','src/windows/preload.cjs','src/projects/domain-validation.mjs','src/recovery/checkpoints.mjs','src/sources/manifest.mjs','src/ui/docs/draft.js','src/ui/docs/rich.js','src/ui/docs/reader.js','src/ui/windows/docs.js','build/windows.mjs','generated/windows/docs.html','tests/native/docs-format.mjs','tests/native/attach-page.mjs','tests/native/home-ready.mjs','tests/native/condition.mjs'];
paths.push('src/ui/docs/structured.js','src/ui/shared/shell.css','generated/assets/shell.css');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture();
const projects=new ProjectStore(data),sources=new SourceRepository(data),original=await projects.createProject({label:'Actual native Docs editing',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000;
const text=Array.from({length:lineCount},(_,i)=>`value_${i} = ${i} # Ș😀`).join('\n')+'\n',ref=await sources.importSource({projectId:original.project.id,bytes:Buffer.from(text)}),point={sourceId:ref.sourceId,version:1,sha256:ref.sha256};
const docs=['doc-a','doc-b'].map(id=>({id,title:id,agent:{name:id,private:'EXACT_AGENT_'+id},releases:[{id:'historic',author:'Original actual author',verdict:'not-run',sourceRef:point}],blocks:[{id:'heading-a',kind:'heading',level:2,text:'Original heading'},{id:'text-a',kind:'text',html:'<p>Original text</p>'},{id:'knowledge-a',kind:'knowledge',reasoningEffort:'EXACT_REASONING',rows:[{id:'row-a',name:'Preserve source',notes:'Original context',sourceRef:point,private:'EXACT_ROW_METADATA'},{id:'row-b',name:'Another source',sourceRef:point,private:'EXACT_OTHER_ROW'}]}]}));
const workspace={diagrams:[{id:'diagram-a',name:'Preserved diagram',source:'flowchart TD\nA-->B'}],workpapers:docs};const metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify(workspace),unrelated:'EXACT_UNRELATED'}};
assert.equal((await commitManifest({projects,repository:sources,projectId:original.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'initial-docs-edit'})).ok,true);const selected=await projects.readProject(original.project.id);
const result={status:'ADVERSE',inputs,lineCount,cases:[],scope:'Actual native rich text Bold/Colour, history, exact save/readback/provenance and Lock. No images/comments/releases or physical-monitor qualification.'};let driver;
if(packageReceipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:original.project.id}));result.package={sourceCommit:packageReceipt.sourceCommit,archive:packageReceipt.appArchive,runtime:packageReceipt.runtimeBinary};}
const keys=async(page,key,code,windowsVirtualKeyCode,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode,modifiers});};
const replaceInput=async(page,selector,value)=>{await page.evaluate('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"center",behavior:"instant"})');await page.waitFor('(()=>{const e=document.querySelector('+JSON.stringify(selector)+'),r=e?.getBoundingClientRect();return r&&r.top>=0&&r.bottom<=innerHeight&&e.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2));})()');await page.click(selector);await keys(page,'a','KeyA',65,2);await page.send('Input.insertText',{text:value});};
const confirmClick=async(page,selector,accept)=>{await page.send('Page.enable');const from=driver.events.length,click=page.click(selector);let found=false;try{const until=Date.now()+20000;while(Date.now()<until){found=driver.events.slice(from).some(event=>event.method==='Target.receivedMessageFromTarget'&&(()=>{try{const message=JSON.parse(event.params.message);return message.method==='Page.javascriptDialogOpening'&&message.params.type==='confirm';}catch{return false;}})());if(found)break;await delay(20);}assert.equal(found,true,'Actual document confirmation must open');await page.send('Page.handleJavaScriptDialog',{accept});await click;}catch(error){await click.catch(()=>{});throw error;}};
const confirmReload=(page,accept)=>confirmClick(page,'#replaceLatestDocument',accept);
try{
 driver=await launchDesktop(packageCopy?{executable:join(packageCopy,packageReceipt.appRelativePath),packaged:true}:{extraArgs:[`--siren-test-root=${data}`,`--siren-test-project=${original.project.id}`]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 const openReader=async(role,id)=>{await waitForHomeModule(driver,role);await driver.click('#homeModule-'+role);await driver.waitFor(`document.querySelector('.home-library [data-entity-id="${id}"]')!=null`);const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(v=>v.windowId);await driver.click(`.home-library [data-entity-id="${id}"]`);await driver.waitFor(`(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>${before.length}})()`);const view=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>!before.includes(v.windowId));const page=await attachNativePage(driver,`siren://app/windows/${role}.html?windowId=${view.windowId}`);await page.waitFor(`document.body.dataset.${role==='docs'?'document':'source'}Ready==="true"`);return {view,page};};
 const a=await openReader('docs','doc-a'),b=await openReader('docs','doc-b'),code=await openReader('code',ref.sourceId);assert.equal(await code.page.evaluate('document.body.dataset.sourceSha256'),ref.sha256);
 const openWorking=async reader=>{const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(v=>v.windowId);await reader.page.click('#openWorkingDocument');await driver.waitFor(`(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>${before.length}})()`);const view=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>!before.includes(v.windowId));const page=await attachNativePage(driver,`siren://app/windows/docs.html?windowId=${view.windowId}`);await page.waitFor('document.body.dataset.documentReady==="true"&&document.body.dataset.documentReadonly==="false"');return {view,page};};
 const first=await openWorking(a),second=await openWorking(a),other=await openWorking(b);

 for(const view of [first,second,other])assert.equal(await view.page.evaluate('document.body.dataset.documentReadonly'), 'false');
 const page=first.page;
 const click=async selector=>{await page.evaluate('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"nearest",inline:"nearest",behavior:"instant"})');await page.click(selector);};
 await click('[data-open-rich="text-a"]');await page.waitFor('document.querySelector("[data-rich-block-id=text-a]")?.contentEditable==="true"');
 const inspected=await page.evaluate('(()=>{const rich=window.SirenNativeDocsRichText;return {safe:rich.inspect("<p><strong>safe</strong></p>").ok,unsafe:rich.inspect("<img src=x onerror=bad()>").ok,unknown:rich.inspect("<custom data-exact=kept>text</custom>").ok}})()');assert.deepEqual(inspected,{safe:true,unsafe:false,unknown:false});
 await click('[data-rich-block-id="text-a"]');
 await page.send('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',modifiers:2,windowsVirtualKeyCode:65});
 await click('[data-format="strong"]');await page.waitFor('document.querySelector("[data-rich-block-id=text-a] strong")!=null');
 const bold=await page.evaluate('document.querySelector("[data-rich-block-id=text-a]").innerHTML');assert.match(bold,/<strong>/);assert.equal(await page.evaluate('document.body.dataset.documentDirty'),'true');assert.deepEqual(await projects.readProject(original.project.id),selected);
 result.cases.push({name:'real selection and Bold pointer produce local formatting only; unsafe and unknown input refused',ok:true});
 await click('[data-document-history="undo"]');await page.waitFor('document.querySelector("textarea[data-block-id=text-a]")?.value==="Original text"');
 assert.equal(await page.evaluate('document.body.dataset.documentDirty'),'false');
 await page.send('Input.dispatchKeyEvent',{type:'keyDown',key:'z',code:'KeyZ',modifiers:10,windowsVirtualKeyCode:90});await page.waitFor('document.querySelector("[data-rich-block-id=text-a] strong")!=null');assert.equal(await page.evaluate('document.activeElement.dataset.richBlockId'),'text-a');
 const observeSelection=()=>page.evaluate('(()=>{const s=document.getSelection(),r=s?.rangeCount?s.getRangeAt(0):null;return {active:document.activeElement?.className,collapsed:r?.collapsed,selectedLength:s?.toString().length,start:r?.startContainer?.nodeName,end:r?.endContainer?.nodeName,status:document.getElementById("viewStatus").textContent,html:document.querySelector("[data-rich-block-id=text-a]").innerHTML}})()');
 await page.send('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',modifiers:2,windowsVirtualKeyCode:65});
 result.selectionBeforeColour=await observeSelection();assert.equal(result.selectionBeforeColour.selectedLength,13);await click('.document-format-tools summary');result.selectionAfterPalette=await observeSelection();await click('[data-text-colour="wp-c-blue"]');result.selectionAfterColour=await observeSelection();await page.waitFor('document.querySelector("[data-rich-block-id=text-a] span")?.className==="wp-c-blue"');
 const formatted=await page.evaluate('document.querySelector("[data-rich-block-id=text-a]").innerHTML');assert.match(formatted,/strong/);assert.match(formatted,/wp-c-blue/);
 result.cases.push({name:'actual Undo/keyboard Redo restore local text/formatting and focused selection for Colour',ok:true});
 await click('#saveDocument');await page.waitFor('document.body.dataset.documentDirty==="false"');const saved=await projects.readProject(original.project.id),expected=structuredClone(workspace);expected.workpapers[0].blocks[1].html=formatted;assert.deepEqual(workspaceMetadata(saved),expected);
 await a.page.click('#retryDocument');await a.page.waitFor('document.querySelector(".document-reader-block strong")!=null');assert.equal(await a.page.evaluate('document.querySelector(".document-reader-block span")?.className'),'wp-c-blue');assert.notEqual(await a.page.evaluate('getComputedStyle(document.querySelector(".document-reader-block span")).color'),await a.page.evaluate('getComputedStyle(document.querySelector(".document-reader-block")).color'));await page.screenshot(join(evidence,'docs-rich-workspace.png'));
 result.cases.push({name:'explicit native save/readback preserves all agent/release/source references and inert reader colours',ok:true});
 await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal((await driver.evaluate('window.sirenWindow.listViews()')).ok,false);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(target=>target.url.includes('windows/docs.html?windowId='+first.view.windowId)),false,'Lock must retire the old private working renderer');assert.deepEqual(await projects.readProject(original.project.id),saved);
 result.cases.push({name:'actual common Lock refuses private editing while preserving saved rich text',ok:true});result.status='COMPLETE';

}catch(cause){result.error={message:cause.message,stack:cause.stack};try{await driver?.screenshot(join(evidence,'failure.png'));result.runtimeLog=driver?.logs().slice(-5000);result.diagnostics=[];for(const target of(await driver.send('Target.getTargets')).targetInfos.filter(t=>t.url.startsWith('siren://app/windows/docs.html'))){const page=await attachNativePage(driver,target.url);result.diagnostics.push(await page.evaluate('({url:location.href,status:document.getElementById("viewStatus")?.textContent,body:{...document.body.dataset},title:document.getElementById("documentTitleInput")?.value})'));await page.screenshot(join(evidence,'view-failure-'+result.diagnostics.length+'.png'));}}catch{}}
finally{if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
