import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {buildWorkspaceEntrypoint} from '../../build/workspace.mjs';
const desktop=fileURLToPath(new URL('../../',import.meta.url)),root=resolve(desktop,'evidence/home-entry',new Date().toISOString().replaceAll(':','-'));
await mkdir(join(root,'owned-data'),{recursive:true});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const names=['package.json','package-lock.json','tests/native/home-entry.mjs','tests/native/home-entry-app.mjs'];
async function walk(dir){for(const entry of await readdir(join(desktop,dir),{withFileTypes:true})){const name=dir+'/'+entry.name;if(entry.isDirectory())await walk(name);else if(entry.isFile())names.push(name);}}
await walk('src');await walk('build');
const capture=async()=>Object.fromEntries(await Promise.all(names.sort().map(async name=>[name,hash(await readFile(join(desktop,name)))])));
const inputs=await capture(),build=await buildWorkspaceEntrypoint({outputDir:join(root,'generated')});
const preload=`const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('sirenDesktopBootstrap',ipcRenderer.sendSync('owned:bootstrap'));
contextBridge.exposeInMainWorld('sirenDesktop',Object.freeze(Object.fromEntries(['getPinState','setupPin','unlockPin','lockPin','requestClose'].map(method=>[method,payload=>ipcRenderer.invoke('owned:pin',method,payload)]))));
contextBridge.exposeInMainWorld('sirenDesktopReady',()=>ipcRenderer.send('owned:ready'));
const home=Object.fromEntries(['getHomeState','continueWork','openProject','createProject'].map(method=>[method,payload=>ipcRenderer.invoke('owned:home',method,payload)]));
home.onInvalidated=callback=>{const listener=()=>callback();ipcRenderer.on('owned:invalidated',listener);return()=>ipcRenderer.removeListener('owned:invalidated',listener);};
contextBridge.exposeInMainWorld('sirenHome',Object.freeze(home));`;
await writeFile(join(root,'owned-preload.cjs'),preload);
await writeFile(join(root,'prepared.json'),JSON.stringify({inputs,build,preloadSHA256:hash(Buffer.from(preload))},null,2));
const child=spawn(join(desktop,'node_modules/electron/dist/electron.exe'),[join(desktop,'tests/native/home-entry-app.mjs'),'--siren-home-fixture='+root],{cwd:desktop,windowsHide:true,env:{...process.env,ELECTRON_RUN_AS_NODE:undefined},stdio:['ignore','pipe','pipe']});
let logs='',timedOut=false;child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);const timer=setTimeout(()=>{timedOut=true;child.kill();},120000);
const exit=await new Promise((yes,no)=>{child.once('error',no);child.once('exit',(code,signal)=>yes({code,signal}));}).finally(()=>clearTimeout(timer));
await writeFile(join(root,'electron.log'),logs);const after=await capture();let native;try{native=JSON.parse(await readFile(join(root,'native-result.json'),'utf8'));}catch{}
const result={root,ownedPid:child.pid,exit,timedOut,inputs,afterInputs:after,inputsUnchanged:JSON.stringify(inputs)===JSON.stringify(after),nativeStatus:native?.status,nativeSHA256:native?hash(await readFile(join(root,'native-result.json'))):null};
result.status=exit.code===0&&!timedOut&&result.inputsUnchanged&&native?.status==='COMPLETE'?'COMPLETE':'ADVERSE';
await writeFile(join(root,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({root,status:result.status,exit,error:native?.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;
