import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {reserveInspectorPort,attachNativeKeyboard} from './native-keyboard.mjs';
import {waitForNativeCondition} from './condition.mjs';
const evidence=resolve('evidence/monitor-memory',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let receipt,copy;
if(packageRoot){receipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(receipt.kind,'development-preview');assert.equal(receipt.releaseAdmitted,false);copy=join(evidence,'Pachet-Știință-Monitoare');await cp(packageRoot,copy,{recursive:true,errorOnExist:true,force:false});assert.equal(createHash('sha256').update(await readFile(join(copy,'App/versions/0.1.0/resources/app.asar'))).digest('hex'),receipt.appArchive.sha256);}
const data=copy?join(copy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const paths=['src/main.mjs','src/windows/layout.mjs','src/windows/layout-memory.mjs','src/windows/factory.mjs','tests/native/native-keyboard.mjs','tests/native/monitor-memory.mjs','generated/home.html'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash('sha256').update(await readFile(p)).digest('hex')]))),inputs=await capture();
const projects=new ProjectStore(data),sources=new SourceRepository(data),created=await projects.createProject({label:'Owned monitor restart',json:'{}'});
const text='def agent(value):\n    return value * 2\n',ref=await sources.importSource({projectId:created.project.id,bytes:Buffer.from(text),provenance:{kind:'standalone',fileName:'agent.py'}});
assert.equal((await commitManifest({projects,repository:sources,projectId:created.project.id,baseRevision:1,sourceRefs:[ref],metadata:{workpapers:[{id:'_AgentNotes',title:'Imported agent notes',blocks:[]}],diagrams:[{id:'Flow-A',name:'Imported flow',source:'flowchart TD\nA-->B'}]},operationId:'owned-monitor-memory'})).ok,true);
const original=await projects.readProject(created.project.id),result={status:'ADVERSE',inputs,cases:[],scope:'Owned development Electron native monitor menu callback on actual displays and clean process restart. No physical menu click, monitor removal or mixed-DPI qualification.'};let driver,native;
if(receipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:created.project.id}));result.package={sourceCommit:receipt.sourceCommit,archive:receipt.appArchive};result.scope='Actual copied development package native menu callback, monitor placement and clean process restart. No physical menu click/removal or mixed-DPI settings-change qualification.';}
const launch=async()=>{const port=await reserveInspectorPort();driver=await launchDesktop(copy?{executable:join(copy,receipt.appRelativePath),packaged:true,extraArgs:['--inspect=127.0.0.1:'+port]}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+created.project.id,'--inspect=127.0.0.1:'+port]});native=await attachNativeKeyboard({port,pid:driver.pid});await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});await driver.waitFor('document.getElementById("homeModule-code")?.disabled===false');};
const open=async(role,id)=>{const module=role==='diagram'?'diagrams':role,before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(v=>v.windowId);await driver.click('#homeModule-'+module);await driver.waitFor(`document.querySelector(${JSON.stringify('.home-library [data-entity-id="'+id+'"]')})!=null`);await driver.click('.home-library [data-entity-id="'+id+'"]');await driver.waitFor(`(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>!${JSON.stringify(before)}.includes(v.windowId));})()`);const view=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>!before.includes(v.windowId));await driver.waitFor(`document.querySelector(${JSON.stringify('#homeRoot [data-window-id="'+view.windowId+'"]')})!=null&&document.getElementById(${JSON.stringify('homeModule-'+module)})?.disabled===false`);return 'siren://app/windows/'+role+'.html?windowId='+view.windowId;};
const snapshot=async()=>JSON.parse(await readFile(join(data,'UI/window-layout.json'),'utf8'));
try{
 await launch();const displays=await native.displayAreas();assert.ok(displays.length>0);result.displays=displays;
 const a=await open('code',ref.sourceId),b=await open('code',ref.sourceId),doc=await open('docs','_AgentNotes');
 const area=displays[0].workArea;const normal={x:area.x+40,y:area.y+45,width:700,height:500};await native.placeView(a,normal);await native.placeView(b,{...normal,x:area.x+150,y:area.y+90},'maximized');
 await native.traceLayout();const destination=displays.length>1?1:0,move=await native.monitorCommand(a,destination);result.move={receipt:move,state:await native.windowState(a),trace:await native.readLayoutTrace()};assert.equal(move.ok,true);assert.equal(move.choices.length,displays.length);assert.ok(move.choices.every(c=>c.type==='radio'));const selectedArea=displays[destination].workArea;
 const actualA=(await native.windowState(a)).normalBounds;assert.ok(actualA.x>=selectedArea.x&&actualA.y>=selectedArea.y&&actualA.x+actualA.width<=selectedArea.x+selectedArea.width&&actualA.y+actualA.height<=selectedArea.y+selectedArea.height);assert.equal((await native.windowState(b)).maximized,true);
 result.cases.push({name:'Actual native monitor menu callback moves only selected Code onto the chosen actual display and leaves its duplicate maximized',ok:true});
 await native.placeView(doc,{...normal,x:area.x+80,y:area.y+75},'fullscreen');await waitForNativeCondition(async()=>(await native.windowState(doc)).fullScreen,'Actual imported Docs fullscreen');
 await waitForNativeCondition(async()=>{try{const record=await snapshot();return record.entries.filter(e=>e.key!=='main').length===3&&record.entries.some(e=>e.layout.fullscreen)&&record.entries.some(e=>e.layout.maximized);}catch{return false;}},'Actual bounded layout file includes independent native mode snapshots');
 const savedA=await native.windowState(a),savedB=await native.windowState(b),savedDoc=await native.windowState(doc);result.beforeRestart={a:savedA,b:savedB,doc:savedDoc};
 await native.closeView('siren://app/home.html');native.close();native=null;await driver.waitForExit();await writeFile(join(evidence,'first-electron.log'),driver.logs());await driver.close();driver=null;
 assert.deepEqual(await projects.readProject(created.project.id),original);assert.deepEqual(await sources.exportSource({projectId:created.project.id,sourceId:ref.sourceId,version:1}),Buffer.from(text));
 await launch();const aa=await open('code',ref.sourceId),bb=await open('code',ref.sourceId),dd=await open('docs','_AgentNotes');
 await waitForNativeCondition(async()=>{const first=await native.windowState(aa),second=await native.windowState(bb),document=await native.windowState(dd);result.observedRestart={a:first,b:second,doc:document};return JSON.stringify(first.normalBounds)===JSON.stringify(savedA.normalBounds)&&JSON.stringify(second.normalBounds)===JSON.stringify(savedB.normalBounds)&&second.maximized&&document.fullScreen;},'Actual clean restart restores two distinct Code positions and imported Docs fullscreen');
 result.afterRestart={a:await native.windowState(aa),b:await native.windowState(bb),doc:await native.windowState(dd)};assert.deepEqual(result.afterRestart.doc.normalBounds,savedDoc.normalBounds);
 result.cases.push({name:'Clean process restart restores duplicate Code normal/maximized geometries and imported uppercase/underscore Docs fullscreen independently',ok:true});
 const layout=await snapshot();assert.ok(Buffer.byteLength(JSON.stringify(layout))<65536);assert.equal(/agent\.py|_AgentNotes|Flow-A|def agent|sourceId|projectId|pin/i.test(JSON.stringify(layout)),false);
 await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);
 assert.deepEqual(await projects.readProject(created.project.id),original);assert.deepEqual(await sources.exportSource({projectId:created.project.id,sourceId:ref.sourceId,version:1}),Buffer.from(text));result.cases.push({name:'Layout file contains finite geometry and opaque identities only; common Lock destroys restored satellites and preserves exact project/source bytes',ok:true});result.status='COMPLETE';
}catch(error){result.error={message:error.message,stack:error.stack};await driver?.screenshot(join(evidence,'failure.png')).catch(()=>{});}
finally{native?.close();if(driver){await writeFile(join(evidence,'electron.log'),driver.logs());await driver.close();}result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';result.physicalMonitorRemovalQualified=false;result.physicalMixedDPIQualified=false;await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
