import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile, cp, access } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { ProjectStore } from '../../src/projects/store.mjs';
import { RecoveryStore } from '../../src/recovery/checkpoints.mjs';
import { launchDesktop, unlockDesktop } from './drive.mjs';
import { hashOwnedFile } from '../../src/updates/download.mjs';

const original = resolve(process.argv[2] || '');
assert.ok(process.argv[2], 'Supply a development package root, not a development renderer');
const receipt = JSON.parse(await readFile(join(original, 'BUILD-IDENTITY.json'), 'utf8'));
assert.equal(receipt.kind, 'development-preview'); assert.equal(receipt.releaseAdmitted, false);
const evidence = resolve('evidence', `packaged-${new Date().toISOString().replaceAll(':', '-')}`); await mkdir(evidence, { recursive: true });
const firstRoot = join(evidence, 'Pachet-Știință-1'); await cp(original, firstRoot, { recursive: true, errorOnExist: true, force: false });
assert.equal((await hashOwnedFile(join(dirname(join(firstRoot, receipt.appRelativePath)), 'resources', 'app.asar'), 1024 ** 3)).sha256, receipt.appArchive.sha256, 'Executed package archive must match its development build receipt');
const dataRoot = join(firstRoot, 'Data'); await mkdir(dataRoot); const projects = new ProjectStore(dataRoot);
const source = 'flowchart TD\n A[Packaged Unicode] --> B[Owned local recovery]';
const project = await projects.createProject({ label: 'Packaged local-PIN fixture', json: JSON.stringify({ source }) });
await new RecoveryStore(dataRoot).checkpointProject({ snapshot: project, kind: 'saved' });
await writeFile(join(dataRoot, 'session-selection.json'), JSON.stringify({ schema: 1, accountId: null, projectId: project.project.id }));
const forbiddenRoot = join(evidence, 'must-not-be-used'); let driver;
try {
  const launch = async root => launchDesktop({ executable: join(root, receipt.appRelativePath), packaged: true, extraArgs: ['--enable-logging=file', `--log-file=${join(evidence, 'runtime.log')}`, `--siren-test-root=${forbiddenRoot}`, '--siren-test-project=ignored-project'] });
  driver = await launch(firstRoot);
  await driver.waitFor('window.sirenDesktopBootstrap?.mode === "locked"');
  assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'), null, 'Locked package must not disclose its selected snapshot');
  assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.readonly'), true);
  assert.equal(await driver.evaluate('typeof window.require'), 'undefined');
  const denied = await driver.evaluate(`window.sirenDesktop.saveProject({projectId:${JSON.stringify(project.project.id)},baseRevision:1,json:'{}',purpose:'workspace'})`);
  assert.equal(denied.ok, false, 'Known project ID cannot bypass the native PIN gate');
  assert.equal(denied.code, 'PIN_REQUIRED');
  await assert.rejects(access(forbiddenRoot), { code: 'ENOENT' });
  assert.equal((await projects.readProject(project.project.id)).sha256, project.sha256);
  await unlockDesktop(driver, { pin: '4826', autoSetup: true });
  await driver.waitFor('document.getElementById("brandVersion")?.textContent === "v1.131.0" && !!document.querySelector("svg .node")');
  assert.equal(await driver.evaluate('document.getElementById("source").value'), source);
  assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.readonly'), false, 'Real local PIN unlock permits packaged editing without an online account');
  await driver.waitFor('!document.body.classList.contains("read-only-mode")');
  await driver.evaluate('window.sirenDesktopFlush?.()');
  const live = await projects.readProject(project.project.id);
  const savedJson = JSON.stringify({ source, ownedPackagedSave: 'acknowledged-native-write' });
  const saved = await driver.evaluate(`window.sirenDesktop.saveProject(${JSON.stringify({ projectId: project.project.id, baseRevision: live.revision, json: savedJson, purpose: 'workspace' })})`);
  assert.equal(saved.ok, true, 'Actual packaged native save must acknowledge after PIN unlock');
  const acknowledged = await projects.readProject(project.project.id);
  assert.equal(acknowledged.json, savedJson); assert.equal(acknowledged.sha256, saved.sha256); assert.equal(acknowledged.revision, saved.revision);
  // The acknowledged saved original is the preservation boundary for recovery.
  const restorePoint = (await new RecoveryStore(dataRoot).scan(project.project.id)).valid.find(p => p.kind === 'saved' && p.snapshot.sha256 === acknowledged.sha256 && p.snapshot.json === acknowledged.json);
  assert.ok(restorePoint, 'Acknowledged native write must have a verified recovery checkpoint');
  await driver.waitFor(`[...document.querySelectorAll('[id$="IntroOverlay"]')].every(e=>getComputedStyle(e).display==='none'||Number(getComputedStyle(e).opacity)<0.01)`);
  if (await driver.evaluate('document.getElementById("introOverviewDialog")?.open')) await driver.click('#closeIntroOverview');
  await driver.click('#desktopOptions'); await driver.click('#desktopCheckUpdates');
  await driver.waitFor('document.querySelector(".desktop-state").textContent.includes("not configured")');
  await driver.waitFor('Number(getComputedStyle(document.getElementById("desktopControlsPanel")).opacity) >= 0.99');
  await driver.screenshot(join(evidence, 'packaged-desktop.png'));
  await driver.click('#desktopRecovery'); await driver.waitFor('document.getElementById("desktopRecoveryPanel")?.open');
  await driver.waitFor('Number(getComputedStyle(document.getElementById("desktopRecoveryPanel")).opacity) >= 0.99');
  assert.ok(await driver.evaluate('document.querySelectorAll(".desktop-recovery-row").length') > 0);
  await driver.screenshot(join(evidence, 'packaged-recovery.png'));
  const pointId = restorePoint.id;
  await driver.click(`#recover-${pointId}`);
  await driver.waitFor(`!!window.sirenDesktopBootstrap?.snapshot && window.sirenDesktopBootstrap.snapshot.project.id !== ${JSON.stringify(project.project.id)} && !document.body?.classList.contains('read-only-mode')`);
  await driver.waitFor('document.getElementById("brandVersion")?.textContent === "v1.131.0" && !!document.querySelector("svg .node")');
  assert.equal(await driver.evaluate('document.getElementById("source").value'), source);
  assert.deepEqual(await projects.readProject(project.project.id), acknowledged, 'Recovery must preserve the acknowledged saved original exactly');
  const recoveredId = await driver.evaluate('window.sirenDesktopBootstrap.snapshot.project.id');
  assert.equal((await projects.readProject(recoveredId)).json, acknowledged.json);
  assert.equal((await projects.readProject(recoveredId)).sha256, acknowledged.sha256);
  await driver.evaluate('window.sirenDesktop.requestClose()');
  await driver.waitForExit();
  await driver.close(); driver = null;
  const closeEvents = JSON.parse(await readFile(join(dataRoot, 'Recovery', 'sessions.json'), 'utf8')).events;
  assert.equal(closeEvents.at(-1)?.event, 'clean-close', 'Moving the full package requires an acknowledged normal application exit, not killing only its parent process');
  assert.deepEqual(await projects.readProject(project.project.id), acknowledged);
  const recoveredAfterExit = await projects.readProject(recoveredId);
  const exitedBag = JSON.parse(recoveredAfterExit.json);
  const exitedSource = exitedBag.source ?? JSON.parse(exitedBag.storage['t-industries-siren-v23-state']).source;
  assert.equal(exitedSource, source, 'Normal editable close must retain recovered source while serializing renderer state');
  const secondRoot = join(evidence, 'Mutat-Știință-2'); await cp(firstRoot, secondRoot, { recursive: true, errorOnExist: true, force: false });
  driver = await launch(secondRoot);
  await driver.waitFor('window.sirenDesktopBootstrap?.mode === "locked"');
  assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'), null, 'Copied package must relock on fresh process startup');
  assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked, false);
  const movedDenied = await driver.evaluate(`window.sirenDesktop.saveProject(${JSON.stringify({ projectId: recoveredId, baseRevision: 1, json: '{}', purpose: 'workspace' })})`);
  assert.equal(movedDenied.ok, false);
  assert.equal(movedDenied.code, 'PIN_REQUIRED');
  await unlockDesktop(driver, { pin: '4826', autoSetup: false });
  await driver.waitFor('document.getElementById("brandVersion")?.textContent === "v1.131.0" && !!document.querySelector("svg .node")');
  assert.equal(await driver.evaluate('document.getElementById("source").value'), source);
  assert.deepEqual(await new ProjectStore(join(secondRoot, 'Data')).readProject(recoveredId), recoveredAfterExit, 'Folder copy must retain the actual acknowledged normal-exit recovered snapshot');
  assert.deepEqual(await new ProjectStore(join(secondRoot, 'Data')).readProject(project.project.id), acknowledged);
  assert.equal((await hashOwnedFile(join(secondRoot, receipt.appRelativePath), 1024 ** 3)).sha256, receipt.runtimeBinary.sha256);
  await driver.evaluate('window.sirenDesktop.requestClose()'); await driver.waitForExit(); await driver.close(); driver = null;
  const recoveredBeforeSafety = await new ProjectStore(join(secondRoot, 'Data')).readProject(recoveredId);
  assert.deepEqual(await new ProjectStore(join(secondRoot, 'Data')).readProject(project.project.id), acknowledged);
  // An owned damaged-journal variant verifies PIN cannot override native safety.
  const safetyRoot = join(evidence, 'Siguranță-readonly-3');
  await cp(secondRoot, safetyRoot, { recursive: true, errorOnExist: true, force: false });
  await writeFile(join(safetyRoot, 'Data', 'Recovery', 'sessions.json'), '{owned damaged journal fixture');
  driver = await launch(safetyRoot);
  await driver.waitFor('window.sirenDesktopBootstrap?.mode === "locked"');
  await unlockDesktop(driver, { pin: '4826', autoSetup: false });
  await driver.waitFor('window.sirenDesktopBootstrap?.mode === "readonly"');
  assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.readonly'), true, 'Native damaged-journal safety remains authoritative after a correct PIN');
  const safetyDenied = await driver.evaluate(`window.sirenDesktop.saveProject(${JSON.stringify({ projectId: recoveredId, baseRevision: 1, json: '{}', purpose: 'workspace' })})`);
  assert.equal(safetyDenied.ok, false, 'Correct PIN cannot bypass native safety read-only');
  assert.equal(safetyDenied.code, 'ACCESS_REFUSED');
  assert.deepEqual(await new ProjectStore(join(safetyRoot, 'Data')).readProject(project.project.id), acknowledged);
  assert.deepEqual(await new ProjectStore(join(safetyRoot, 'Data')).readProject(recoveredId), recoveredBeforeSafety);
  await writeFile(join(evidence, 'result.json'), JSON.stringify({ completed: true, scope: 'Actual packaged app.asar/SIREN.exe, locked null snapshot/refused saves, production native fixture PIN unlock, real local save/readback, rejected dev CLI, Unicode folder copy relock/unlock, pointer recovery into a new project preserving the acknowledged saved original, native damaged-journal read-only authority despite correct PIN, and unconfigured updates. No launcher/apply/clean-PC/online account qualification.', sourceCommit: receipt.sourceCommit, rendererSha256: receipt.renderer.rendererSha256, archive: receipt.appArchive, runtime: receipt.runtimeBinary, initialProjectSha256: project.sha256, acknowledgedProjectSha256: acknowledged.sha256 }, null, 2));
  console.log(JSON.stringify({ completed: true, evidence }));
} catch (error) {
  await writeFile(join(evidence, 'result.json'), JSON.stringify({ completed: false, error: String(error.stack || error), sourceCommit: receipt.sourceCommit, rendererSha256: receipt.renderer.rendererSha256, archive: receipt.appArchive, runtime: receipt.runtimeBinary }, null, 2));
  if (driver) {
    await driver.screenshot(join(evidence, 'failure.png')).catch(() => {});
    const state = await driver.evaluate(`(()=>{const panel=document.getElementById('desktopControlsPanel');return {visibility:document.visibilityState,focused:document.hasFocus(),inert:document.body.inert,locked:window.sirenDesktopStorageLocked,bodyClasses:document.body.className,panel:panel?{open:panel.open,opacity:getComputedStyle(panel).opacity,display:getComputedStyle(panel).display,visibility:getComputedStyle(panel).visibility,animation:getComputedStyle(panel).animation,rect:panel.getBoundingClientRect().toJSON()}:null,animations:document.getAnimations().map(a=>({playState:a.playState,currentTime:a.currentTime,finish:a.effect?.getComputedTiming()?.endTime})),bootstrap: {mode:window.sirenDesktopBootstrap?.mode,readonly:window.sirenDesktopBootstrap?.readonly}};})()`).catch(() => null);
    await writeFile(join(evidence, 'failure-state.json'), JSON.stringify({ error: error.message, state }, null, 2));
  }
  throw error;
} finally { if (driver) { await writeFile(join(evidence, 'electron.log'), driver.logs()); await driver.close(); } }
