import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile, cp, access } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { ProjectStore } from '../../src/projects/store.mjs';
import { RecoveryStore } from '../../src/recovery/checkpoints.mjs';
import { launchDesktop } from './drive.mjs';
import { hashOwnedFile } from '../../src/updates/download.mjs';

const original = resolve(process.argv[2] || '');
assert.ok(process.argv[2], 'Supply a development package root, not a development renderer');
const receipt = JSON.parse(await readFile(join(original, 'BUILD-IDENTITY.json'), 'utf8'));
assert.equal(receipt.kind, 'development-preview'); assert.equal(receipt.releaseAdmitted, false);
const evidence = resolve('evidence', `packaged-${new Date().toISOString().replaceAll(':', '-')}`); await mkdir(evidence, { recursive: true });
const firstRoot = join(evidence, 'Pachet-Știință-1'); await cp(original, firstRoot, { recursive: true, errorOnExist: true, force: false });
const dataRoot = join(firstRoot, 'Data'); await mkdir(dataRoot); const projects = new ProjectStore(dataRoot);
const source = 'flowchart TD\n A[Packaged Unicode] --> B[Owned local recovery]';
const project = await projects.createProject({ label: 'Packaged read-only fixture', json: JSON.stringify({ source }) });
await new RecoveryStore(dataRoot).checkpointProject({ snapshot: project, kind: 'saved' });
await writeFile(join(dataRoot, 'session-selection.json'), JSON.stringify({ schema: 1, accountId: null, projectId: project.project.id }));
const forbiddenRoot = join(evidence, 'must-not-be-used'); let driver;
try {
  const launch = async root => launchDesktop({ executable: join(root, receipt.appRelativePath), packaged: true, extraArgs: ['--enable-logging=file', `--log-file=${join(evidence, 'runtime.log')}`, `--siren-test-root=${forbiddenRoot}`, '--siren-test-project=ignored-project'] });
  driver = await launch(firstRoot);
  await driver.waitFor('document.getElementById("brandVersion")?.textContent === "v1.131.0" && !!document.querySelector("svg .node")');
  assert.equal(await driver.evaluate('document.getElementById("source").value'), source);
  assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.readonly'), true, 'No production account configured: packaged project must be read-only');
  await driver.waitFor('document.body.classList.contains("read-only-mode")');
  assert.ok((await driver.evaluate('document.getElementById("saveStateText").textContent')).includes('Read-only'));
  assert.equal(await driver.evaluate('typeof window.require'), 'undefined');
  const denied = await driver.evaluate(`window.sirenDesktop.saveProject({projectId:${JSON.stringify(project.project.id)},baseRevision:1,json:'{}',purpose:'workspace'})`);
  assert.equal(denied.ok, false, 'Renderer cannot save without packaged activation');
  await assert.rejects(access(forbiddenRoot), { code: 'ENOENT' });
  assert.equal((await projects.readProject(project.project.id)).sha256, project.sha256);
  await driver.waitFor(`[...document.querySelectorAll('[id$="IntroOverlay"]')].every(e=>getComputedStyle(e).display==='none'||Number(getComputedStyle(e).opacity)<0.01)`);
  if (await driver.evaluate('document.getElementById("introOverviewDialog")?.open')) await driver.click('#closeIntroOverview');
  await driver.click('#desktopOptions'); await driver.click('#desktopCheckUpdates');
  await driver.waitFor('document.querySelector(".desktop-state").textContent.includes("not configured")');
  await driver.waitFor('Number(getComputedStyle(document.getElementById("desktopControlsPanel")).opacity) >= 0.99');
  await driver.screenshot(join(evidence, 'packaged-desktop.png'));
  await driver.click('#desktopRecovery'); await driver.waitFor('document.getElementById("desktopRecoveryPanel")?.open');
  await driver.waitFor('Number(getComputedStyle(document.getElementById("desktopRecoveryPanel")).opacity) >= 0.99');
  assert.ok(await driver.evaluate('document.querySelectorAll(".desktop-recovery-row").length') > 0);
  await driver.screenshot(join(evidence, 'packaged-recovery.png'));
  const pointId = await driver.evaluate('document.querySelector(".desktop-recovery-row").dataset.pointId');
  await driver.click(`#recover-${pointId}`);
  await driver.waitFor(`!!window.sirenDesktopBootstrap?.snapshot && window.sirenDesktopBootstrap.snapshot.project.id !== ${JSON.stringify(project.project.id)} && document.body?.classList.contains('read-only-mode')`);
  assert.equal(await driver.evaluate('document.getElementById("source").value'), source);
  assert.equal((await projects.readProject(project.project.id)).sha256, project.sha256);
  const recoveredId = await driver.evaluate('window.sirenDesktopBootstrap.snapshot.project.id');
  await driver.close(); driver = null;
  const secondRoot = join(evidence, 'Mutat-Știință-2'); await cp(firstRoot, secondRoot, { recursive: true, errorOnExist: true, force: false });
  driver = await launch(secondRoot); await driver.waitFor('document.getElementById("brandVersion")?.textContent === "v1.131.0"');
  assert.equal(await driver.evaluate('document.getElementById("source").value'), source);
  assert.equal((await new ProjectStore(join(secondRoot, 'Data')).readProject(recoveredId)).sha256, project.sha256);
  assert.equal((await hashOwnedFile(join(secondRoot, receipt.appRelativePath), 1024 ** 3)).sha256, receipt.runtimeBinary.sha256);
  await writeFile(join(evidence, 'result.json'), JSON.stringify({ completed: true, scope: 'Actual packaged app.asar/SIREN.exe, sandbox, Unicode folder/copy, owned fixture/visible read-only activation, rejected dev CLI, pointer recovery into a new project preserving the original and unconfigured update check. No launcher/apply/clean-PC/production account qualification.', sourceCommit: receipt.sourceCommit, rendererSha256: receipt.renderer.rendererSha256, archive: receipt.appArchive, runtime: receipt.runtimeBinary, projectSha256: project.sha256 }, null, 2));
  console.log(JSON.stringify({ completed: true, evidence }));
} finally { if (driver) { await writeFile(join(evidence, 'electron.log'), driver.logs()); await driver.close(); } }
