import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {hashOwnedFile} from '../../src/updates/download.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
import {reserveInspectorPort,attachNativeKeyboard} from './native-keyboard.mjs';
import {waitForNativeCondition} from './condition.mjs';
const evidence=resolve('evidence/presentation-windows',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');
let packageReceipt=null,packageCopy=null;
if(packageRoot){
 packageReceipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(packageReceipt.kind,'development-preview');assert.equal(packageReceipt.releaseAdmitted,false);
 packageCopy=join(evidence,'Pachet-Știință-Present');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});
 const archive=await readFile(join(packageCopy,'App','versions','0.1.0','resources','app.asar'));assert.equal(createHash('sha256').update(archive).digest('hex'),packageReceipt.appArchive.sha256);
 assert.deepEqual(await hashOwnedFile(join(packageCopy,packageReceipt.appRelativePath),1024**3),packageReceipt.runtimeBinary);
}
const paths=['src/main.mjs','src/protocol.mjs','src/windows/registry.mjs','src/windows/factory.mjs','src/windows/coordinator.mjs','src/windows/readonly-seals.mjs','src/windows/control.mjs','src/windows/source-barrier.mjs','src/windows/presentation.mjs','src/windows/presentation-deck.mjs','src/windows/presentation-render.mjs','src/windows/presentation-ipc.mjs','src/windows/presentation-preload.cjs','src/ui/presentation/window.js','src/ui/presentation/render.js','src/ui/workspace/home.js','generated/home.html','generated/windows/presenter.html','generated/windows/audience.html','generated/presentation-render.html','tests/native/presentation-windows.mjs','tests/native/drive.mjs','tests/native/attach-page.mjs'];
paths.push('src/ui/presentation/cards.js','src/ui/diagram/vector.js','src/ui/diagram/style.js','build/presentation-render.mjs','build/diagram-style.mjs','tests/native/native-keyboard.mjs','tests/native/condition.mjs','src/ui/presentation/window.css','build/presentation-windows.mjs');const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture();
const data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data'),projects=new ProjectStore(data),sources=new SourceRepository(data);await mkdir(data,{recursive:true});
const linesAt=process.argv.indexOf('--lines'),lineCount=linesAt<0?100000:Number(process.argv[linesAt+1]);if(![100000,300000].includes(lineCount))throw Error('Declared source line count required');
const sourceBytes=Buffer.from('PRIVATE_CODE_SOURCE\n'+Array.from({length:lineCount},(_,i)=>'value_'+i+' = "Ș😀"').join('\n'));
const initial=await projects.createProject({label:'Owned native presentation',json:'{}'}),ref=await sources.importSource({projectId:initial.project.id,bytes:sourceBytes});
const diagram={id:'deck-a',name:'Context connects ideas',source:'flowchart TD\nA[Public context]-->B[Public decision]\n%% PRIVATE_MERMAID_COMMENT\nstyle A fill:#ff3366,color:#ffffff',diagramTitleTouched:true,diagramTitle:'Saved presentation title',fontFamily:'Georgia',fontSize:20,nodeStyles:{A:{fill:'#000000'},B:{fill:'#12ab34'}},nodeMetadata:{A:{agent:'PRIVATE_AGENT_ID',sourceRef:{sourceId:ref.sourceId,version:ref.version,sha256:ref.sha256}}},presentation:{sequence:[{id:'overview-slide',type:'overview',title:'The big picture'},{id:'focus-a',type:'node',nodeId:'A',title:'Understand the context'},{id:'section-c',type:'section',title:'Decisions with context'},{id:'card-text',type:'card',card:{kind:'text',title:'How context helps',eyebrow:'FROM CODE TO UNDERSTANDING',html:'<p>Understand the agent.</p><ul><li>Review its inputs</li><li>Check the decisions</li></ul>',body:'PRIVATE_STALE_BODY',notes:'PRIVATE_CARD_FIELD'}},{id:'card-title',type:'card',card:{kind:'title',title:'Ideas, connected. Ș😀',body:'A clear explanation makes review possible.',align:'centre',textScale:1.2}},{id:'unsupported-media',type:'card',card:{kind:'image',assetId:'PRIVATE_ASSET',title:'Unsupported image'}}],notes:{overview:{text:'PRIVATE_OVERVIEW_NOTES'},'node:A':{text:'PRIVATE_NODE_NOTES'},'section:section-c':{text:'PRIVATE_SECTION_NOTES'},'card:card-text':{text:'PRIVATE_CARD_TEXT_NOTES'},'card:card-title':{text:'PRIVATE_CARD_TITLE_NOTES'}}}};
const metadata={diagrams:[diagram],workpapers:[{id:'doc-a',title:'Exact document',content:'PRIVATE_DOCS_CONTENT',releases:[{author:'Actual author',verdict:'not-run'}]}]};assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'native-presentation-fixture'})).ok,true);let expected=await projects.readProject(initial.project.id);
const result={status:'ADVERSE',inputs,cases:[],sourceFixture:{lineCount,bytes:sourceBytes.length,sha256:hash(sourceBytes)},scope:'Actual native Home/Presenter/Audience, Mermaid image and section navigation, role/privacy refusal, explicit deck refresh, observed native fullscreen/Escape/minimize/restore and all-view Lock with Code/Docs. Physical multi-monitor/DPI, rich media, exported decks and packaged runtime are not qualified here.'};let driver,presenter,audience,native;
if(packageReceipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));result.package={sourceCommit:packageReceipt.sourceCommit,archive:packageReceipt.appArchive,runtime:packageReceipt.runtimeBinary};result.scope=result.scope.replace(' and packaged runtime','');}
const views=async()=>{const r=await driver.evaluate('window.sirenWindow.listViews()');assert.equal(r.ok,true);return r.views;};
const attach=async view=>{const page=await attachNativePage(driver,'siren://app/windows/'+view.role+'.html?windowId='+view.windowId);await page.waitFor('document.body.dataset.'+(['presenter','audience'].includes(view.role)?'presentation':view.role==='code'?'source':'document')+'Ready==="true"');return {view,page};};
const forbidden=['PRIVATE_OVERVIEW_NOTES','PRIVATE_NODE_NOTES','PRIVATE_SECTION_NOTES','PRIVATE_MERMAID_COMMENT','PRIVATE_AGENT_ID','PRIVATE_DOCS_CONTENT','PRIVATE_CODE_SOURCE','PRIVATE_STALE_BODY','PRIVATE_CARD_FIELD','PRIVATE_CARD_TEXT_NOTES','PRIVATE_CARD_TITLE_NOTES','PRIVATE_ASSET'];
try{
 const port=await reserveInspectorPort();driver=await launchDesktop(packageCopy?{executable:join(packageCopy,packageReceipt.appRelativePath),packaged:true,extraArgs:['--inspect=127.0.0.1:'+port]}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+initial.project.id,'--inspect=127.0.0.1:'+port]});result.ownedPid=driver.pid;native=await attachNativeKeyboard({port,pid:driver.pid});await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 await driver.waitFor('document.getElementById("homeModule-present")?.disabled===false');await driver.click('#homeModule-present');await driver.waitFor('document.querySelector(".home-library [data-entity-id=deck-a]")!=null');await driver.click('.home-library [data-entity-id=deck-a]');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="presenter")})()');presenter=await attach((await views()).find(v=>v.role==='presenter'));await presenter.page.waitFor('document.body.dataset.publicReady==="true"&&document.getElementById("presenterNotes").textContent==="PRIVATE_OVERVIEW_NOTES"');
 await driver.waitFor('(async()=>{const r=await window.sirenHome.getHomeState();return r.ok&&r.state.continuation?.location.surface==="present"&&r.state.continuation.location.entityId==="deck-a"&&document.getElementById("homeModule-present")?.disabled===false})()');
 await presenter.page.click('#openAudience');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="audience")})()');audience=await attach((await views()).find(v=>v.role==='audience'));await audience.page.waitFor('document.body.dataset.publicReady==="true"');
 const audienceView=await audience.page.evaluate('window.sirenWindow.getView()');assert.deepEqual(audienceView.view.entityIds,[]);assert.equal(await audience.page.evaluate('typeof window.sirenSourceRead'),'undefined');assert.equal(await audience.page.evaluate('typeof window.sirenDocsRead'),'undefined');
 for(const method of ['getPresenter','getPreview','navigate','refreshDeck','openAudience','getDisplays'])assert.equal((await audience.page.evaluate('window.sirenPresentation.'+method+'({})')).ok,false);
 let publicState=await audience.page.evaluate('window.sirenPresentation.getFrame()');assert.equal(publicState.ok,true);assert.equal(publicState.frame.publicSlide.kind,'image');for(const value of forbidden){assert.equal(JSON.stringify(publicState).includes(value),false);assert.equal((await audience.page.evaluate('document.body.textContent')).includes(value),false);}
 result.publicStylePixels=await audience.page.evaluate('(async()=>{const image=document.querySelector("#publicSlide img");await image.decode();const canvas=document.createElement("canvas");canvas.width=1600;canvas.height=900;const context=canvas.getContext("2d");context.drawImage(image,0,0,1600,900);const data=context.getImageData(0,0,1600,900).data,counts={pink:0,green:0};for(let i=0;i<data.length;i+=4){if(data[i]===255&&data[i+1]===51&&data[i+2]===102)counts.pink++;if(data[i]===18&&data[i+1]===171&&data[i+2]===52)counts.green++;}return counts;})()');assert.ok(result.publicStylePixels.pink>100,'Audience PNG must retain imported A colour');assert.ok(result.publicStylePixels.green>100,'Audience PNG must paint saved B metadata');
 const imageBefore=hash(Buffer.from(publicState.frame.publicSlide.image.slice(22),'base64'));await presenter.page.screenshot(join(evidence,'presenter-overview.png'));await audience.page.screenshot(join(evidence,'audience-overview.png'));
 result.previewGeometry=await presenter.page.evaluate('(()=>{const host=document.getElementById("publicSlide").getBoundingClientRect(),image=document.querySelector("#publicSlide img").getBoundingClientRect();return {hostHeight:host.height,imageHeight:image.height,hostWidth:host.width,imageWidth:image.width};})()');assert.ok(result.previewGeometry.imageHeight<=result.previewGeometry.hostHeight,'Public preview image must fit the measured available height');
 assert.equal((await audience.page.evaluate('document.getElementById("viewStatus").textContent')).includes('Waiting'),false,'Audience must clear its waiting state after a real frame is displayed');assert.deepEqual(await projects.readProject(initial.project.id),expected);result.cases.push({name:'actual Home opens native Presenter and zero-source-grant Audience; fitted real PNG contains only public slide while genuine notes remain in Presenter',ok:true,imageSha256:imageBefore});
 await presenter.page.waitFor('document.getElementById("openAudience").disabled===false');await presenter.page.click('#openAudience');
 await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.filter(v=>v.role==="audience").length===2})()');
 const secondAudience=await attach((await views()).find(v=>v.role==='audience'&&v.windowId!==audience.view.windowId));await secondAudience.page.waitFor('document.body.dataset.publicReady==="true"');
 for(const theme of ['light','dark']){
  for(const page of [presenter.page,audience.page])await page.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:theme},{name:'prefers-reduced-motion',value:'reduce'}]});
  assert.equal(await presenter.page.evaluate('matchMedia("(prefers-reduced-motion: reduce)").matches'),true);
  await presenter.page.screenshot(join(evidence,'presenter-'+theme+'.png'));await audience.page.screenshot(join(evidence,'audience-'+theme+'.png'));
 }
 await presenter.page.waitFor('document.getElementById("nextSlide").disabled===false');await presenter.page.click('#nextSlide');await audience.page.waitFor('document.body.dataset.slideId==="focus-a"');await secondAudience.page.waitFor('document.body.dataset.slideId==="focus-a"');await presenter.page.waitFor('document.getElementById("presenterNotes").textContent==="PRIVATE_NODE_NOTES"&&document.getElementById("nextSlide").disabled===false');publicState=await audience.page.evaluate('window.sirenPresentation.getFrame()');assert.notEqual(hash(Buffer.from(publicState.frame.publicSlide.image.slice(22),'base64')),imageBefore);
 await presenter.page.key('ArrowRight','ArrowRight',39);await audience.page.waitFor('document.body.dataset.slideId==="section-c"');await presenter.page.waitFor('document.getElementById("presenterNotes").textContent==="PRIVATE_SECTION_NOTES"');
 for(const [id,note]of [['card-text','PRIVATE_CARD_TEXT_NOTES'],['card-title','PRIVATE_CARD_TITLE_NOTES']]){await presenter.page.click('button[data-slide-id="'+id+'"]');await audience.page.waitFor('document.body.dataset.slideId==='+JSON.stringify(id));await secondAudience.page.waitFor('document.body.dataset.slideId==='+JSON.stringify(id));await presenter.page.waitFor('document.getElementById("presenterNotes").textContent==='+JSON.stringify(note)+'&&!document.getElementById("nextSlide").disabled');const actual=await audience.page.evaluate('window.sirenPresentation.getFrame()');assert.equal(actual.frame.publicSlide.kind,'image');assert.equal(Object.keys(actual.frame.publicSlide).sort().join(','),'image,kind,title');for(const value of forbidden){assert.equal(JSON.stringify(actual).includes(value),false);assert.equal((await audience.page.evaluate('document.body.textContent')).includes(value),false);}await audience.page.screenshot(join(evidence,'audience-'+id+'.png'));}
 const beforeUnsupported=await audience.page.evaluate('window.sirenPresentation.getFrame()');await presenter.page.click('button[data-slide-id="unsupported-media"]');await presenter.page.waitFor('document.getElementById("viewStatus").textContent.includes("could not be rendered")&&!document.getElementById("nextSlide").disabled');assert.deepEqual(await audience.page.evaluate('window.sirenPresentation.getFrame()'),beforeUnsupported);assert.equal(await presenter.page.evaluate('document.getElementById("presenterNotes").textContent'),'PRIVATE_CARD_TITLE_NOTES');assert.deepEqual(await projects.readProject(initial.project.id),expected);result.cases.push({name:'actual saved Title/Text cards navigate two native Audiences with PNG-only projection/private notes; unsupported media retains exact prior public frame and whole project',ok:true});
 await presenter.page.click('button[data-slide-id="section-c"]');await audience.page.waitFor('document.body.dataset.slideId==="section-c"');await presenter.page.waitFor('document.getElementById("presenterNotes").textContent==="PRIVATE_SECTION_NOTES"&&!document.getElementById("nextSlide").disabled');
 const audienceURL='siren://app/windows/audience.html?windowId='+audience.view.windowId;
 await audience.page.click('#fullscreen');await waitForNativeCondition(async()=> (await native.windowState(audienceURL)).fullScreen===true,'Actual owned Audience fullscreen');result.fullscreen=await native.windowState(audienceURL);
 await audience.page.waitFor('document.body.dataset.fullscreen==="true"&&getComputedStyle(document.querySelector("header")).display==="none"');await audience.page.screenshot(join(evidence,'audience-fullscreen.png'));
 result.fullscreenGeometry=await audience.page.evaluate('(()=>{const slide=document.getElementById("publicSlide").getBoundingClientRect();return {width:slide.width,height:slide.height,viewportWidth:innerWidth,viewportHeight:innerHeight};})()');
 assert.ok(result.fullscreenGeometry.height>=result.fullscreenGeometry.viewportHeight-2,'Fullscreen public slide must occupy the actual viewport instead of a hidden zero-height row');
 assert.ok(result.fullscreenGeometry.width>=result.fullscreenGeometry.viewportWidth-2);
 await audience.page.key('Escape','Escape',27);await waitForNativeCondition(async()=> (await native.windowState(audienceURL)).fullScreen===false,'Actual owned Audience exits fullscreen');result.restored=await native.windowState(audienceURL);
 await native.minimizeView(audienceURL);await waitForNativeCondition(async()=> (await native.windowState(audienceURL)).minimized===true,'Actual owned Audience minimized');await driver.evaluate('window.sirenHomeView.refresh()');const restore='.home-project-row[data-window-id="'+audience.view.windowId+'"]';assert.equal((await driver.evaluate('document.querySelector('+JSON.stringify(restore)+').textContent')).includes('Minimized'),true);await driver.click(restore);await waitForNativeCondition(async()=> (await native.windowState(audienceURL)).minimized===false,'Actual Home restores owned Audience');
 await secondAudience.page.waitFor('document.body.dataset.slideId==="section-c"');for(const value of forbidden)assert.equal((await secondAudience.page.evaluate('document.body.textContent')).includes(value),false);
 await presenter.page.screenshot(join(evidence,'presenter-section.png'));await audience.page.screenshot(join(evidence,'audience-section.png'));result.cases.push({name:'actual mouse and keyboard advance two genuine Audiences with private notes, Light/Dark reduced-motion visuals; PID-checked native observations prove fullscreen, Escape, minimize and Home restore',ok:true});
 const changed=structuredClone(metadata);changed.diagrams[0].presentation.sequence[2].title='Refreshed public section';changed.diagrams[0].presentation.notes['section:section-c'].text='PRIVATE_REFRESHED_NOTES';assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:expected.revision,sourceRefs:expected.sourceRefs,metadata:changed,operationId:'owned-refresh-deck'})).ok,true);expected=await projects.readProject(initial.project.id);
 const oldVersion=await presenter.page.evaluate('document.body.dataset.deckVersion');assert.equal((await presenter.page.evaluate('window.sirenPresentation.getPresenter()')).deck.version,oldVersion);await presenter.page.click('#refreshDeck');await audience.page.waitFor('document.body.dataset.slideId==="section-c"&&document.body.dataset.deckVersion!=='+JSON.stringify(oldVersion));await presenter.page.waitFor('document.getElementById("presenterNotes").textContent==="PRIVATE_REFRESHED_NOTES"');assert.equal((await audience.page.evaluate('document.body.textContent')).includes('PRIVATE_REFRESHED_NOTES'),false);assert.deepEqual(await projects.readProject(initial.project.id),expected);result.cases.push({name:'actual explicit Refresh adopts genuine changed saved deck/notes and preserves current slide identity without writing presentation content',ok:true});
 await driver.waitFor('document.getElementById("homeContinue")?.disabled===false');const existingPresenter=presenter.view.windowId;
 await driver.click('#homeContinue');await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.filter(v=>v.role==="presenter").length===2})()');
 const continued=await attach((await views()).find(v=>v.role==='presenter'&&v.windowId!==existingPresenter));await continued.page.waitFor('document.body.dataset.publicReady==="true"');assert.equal((await continued.page.evaluate('window.sirenPresentation.getPresenter()')).deck.deckId,'deck-a');
 assert.equal(await audience.page.evaluate('document.body.dataset.slideId'),'section-c','Another Presenter must not replace an existing Audience owner');await continued.page.click('#closeView');
 await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.filter(v=>v.role==="presenter").length===1})()');assert.deepEqual(await projects.readProject(initial.project.id),expected);result.cases.push({name:'actual Home Continue opens another exact saved Presenter; original Audiences stay attached to their own Presenter; close preserves the whole project',ok:true});
 for(const request of [{role:'code',entityId:ref.sourceId,version:1},{role:'docs',entityId:'doc-a'}]){const r=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify(request)+')');assert.equal(r.ok,true);await attach(r.view);}
 await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);assert.deepEqual(await projects.readProject(initial.project.id),expected);assert.deepEqual(await sources.exportSource({projectId:initial.project.id,sourceId:ref.sourceId,version:1}),sourceBytes);result.cases.push({name:'actual all-view Lock seals Presenter/Audience/Code/Docs, destroys all satellite renderers and returns locked Home with null snapshot, exact saved project and original source bytes',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{await driver?.screenshot(join(evidence,'failure.png'));for(const [name,view]of [['presenter',presenter],['audience',audience]])if(view){result[name]=await view.page.evaluate('({body:{...document.body.dataset},status:document.getElementById("viewStatus")?.textContent})');await view.page.screenshot(join(evidence,name+'-failure.png'));}}catch{}}
finally{native?.close();if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();if(packageReceipt){result.packageIdentitiesUnchanged=JSON.stringify(await hashOwnedFile(join(packageCopy,packageReceipt.appRelativePath),1024**3))===JSON.stringify(packageReceipt.runtimeBinary)&&JSON.stringify(await hashOwnedFile(join(packageCopy,'App','versions','0.1.0','resources','app.asar'),1024**3))===JSON.stringify(packageReceipt.appArchive);if(!result.packageIdentitiesUnchanged)result.status='ADVERSE';}result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
