import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {hashOwnedFile} from '../../src/updates/download.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
const evidence=resolve('evidence/source-map',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let receipt=null,copy=null;
if(packageRoot){receipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(receipt.kind,'development-preview');assert.equal(receipt.releaseAdmitted,false);copy=join(evidence,'Pachet-Știință-Syntax');await cp(packageRoot,copy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(copy,'App/versions/0.1.0/resources/app.asar'))),receipt.appArchive.sha256);assert.deepEqual(await hashOwnedFile(join(copy,receipt.appRelativePath),1024**3),receipt.runtimeBinary);}
const paths=['src/windows/source-context.mjs','src/windows/source-reads.mjs','src/ui/code/commands.js','src/ui/workspace/icons.js','src/ui/workspace/home.js','build/appearance.mjs','build/workspace.mjs','src/main.mjs','src/sources/analysis.mjs','src/sources/analysis-worker.mjs','src/sources/map-worker.mjs','src/sources/repository.mjs','src/windows/source-analysis.mjs','src/windows/source-barrier.mjs','src/windows/coordinator.mjs','src/windows/preload.cjs','src/ui/code/analysis.js','src/ui/code/editor.js','src/ui/windows/code.js','build/analysis.mjs','build/renderer.mjs','build/windows.mjs','generated/build.json','generated/code-analysis-worker.cjs','generated/windows/code.html','generated/home.html','tests/native/source-map.mjs','tests/native/drive.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture(),data=copy?join(copy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Actual native selected syntax map',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000;
const prefix=Array.from({length:lineCount},(_,i)=>`item_${i} = ${i} # Ș😀\n`).join(''),tail='class Agent:\n    async def run(self, items):\n        result: int\n        result = 1\n        result += 2\n        for item in items:\n            if item:\n                yield process(item)\n            else:\n                return None\n\n',text=prefix+tail,bytes=Buffer.from(text),ref=await sources.importSource({projectId:initial.project.id,bytes}),point={sourceId:ref.sourceId,version:ref.version,sha256:ref.sha256};
const metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify({codeFiles:[{id:'map-file',name:'map.py',language:'python',sourceRef:point}],diagrams:[{id:'flow',name:'Original',source:'flowchart TD\nA[Original]-->B'}],workpapers:[{id:'doc',title:'Unrelated exact Docs',agent:{id:'AGENT_EXACT'},blocks:[]} ]})},unrelated:'EXACT_UNRELATED'};
assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:[ref],metadata,operationId:'native-selected-map-initial'})).ok,true);const selected=await projects.readProject(initial.project.id);if(copy)await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));
const result={status:'ADVERSE',scope:'Actual native selected stored Python syntax-containment map past300k, finite coloured blocks/collapse/exact navigation, genuine cancellation/common Lock, immutable source/project preservation. Implementer evidence only; no runtime/execution graph, unlimited graphs or physical display qualification.',inputs,lineCount,source:point,cases:[]};let driver,page;
const keys=async(key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
try{
 driver=await launchDesktop(copy?{executable:join(copy,receipt.appRelativePath),packaged:true}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+initial.project.id]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 await driver.waitFor('document.getElementById("homeModule-code")?.disabled===false');await driver.click('#homeModule-code');const selector='.home-library [data-entity-id="'+point.sourceId+'"]';await driver.waitFor('document.querySelector('+JSON.stringify(selector)+')!=null');await driver.click(selector);await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.views.some(v=>v.role==="code")})()');const view=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(v=>v.role==='code');page=await attachNativePage(driver,'siren://app/windows/code.html?windowId='+view.windowId);await page.waitFor('document.body.dataset.sourceReady==="true"');
 await page.click('.cm-content');await keys('End','End',35,2);for(let i=0;i<tail.split('\n').length-1;i++)await keys('ArrowUp','ArrowUp',38);await keys('Home','Home',36);await keys('End','End',35,10);assert.deepEqual(await page.evaluate('(()=>{const s=document.querySelector(".siren-code-editor").dataset;return [Number(s.selectionFrom),Number(s.selectionTo)]})()'),[prefix.length,text.length]);
 await page.click('#toggleAnalysis');await page.click('#analysisScope');await keys('Home','Home',36);await keys('ArrowDown','ArrowDown',40);await keys('ArrowDown','ArrowDown',40);await keys('Enter','Enter',13);const started=performance.now();await page.click('#analyzeSource');await page.waitFor('document.getElementById("codeAnalysis").dataset.analysisState==="complete"');result.mapMs=performance.now()-started;
 assert.equal(await page.evaluate('document.querySelectorAll(".analysis-map-node").length'),11);assert.match(await page.evaluate('document.getElementById("analysisStatus").textContent'),/syntax nesting/);assert.equal(await page.evaluate('document.querySelector(".analysis-map-node[data-map-kind=call] strong").textContent'),'process(item)');assert.equal(await page.evaluate('document.querySelector(".analysis-map-node[data-map-kind=loop]").dataset.mapDepth'),'3');assert.deepEqual(await page.evaluate('Array.from(document.querySelectorAll(".analysis-map-node"),n=>n.dataset.mapKind)'),['selection','class','function','annotation','assignment','assignment','loop','branch','yield','call','return']);assert.match(await page.evaluate('document.querySelector(".analysis-map-node[data-map-kind=annotation] button[data-map-node-id]").title'),/type annotation without assigning a value here/);result.cases.push({name:'actual keyboard selection beyond300k yields exact eleven-block syntax tree including annotation, assignment and update from the stored parser, with colour/nesting and explicit static semantics',ok:true});
 await page.evaluate('document.querySelector("[data-map-node-id=\\"9\\"]").scrollIntoView({block:"center"})');await page.click('[data-map-node-id="9"]');assert.deepEqual(await page.evaluate('(()=>{const s=document.querySelector(".siren-code-editor").dataset;return [Number(s.selectionFrom),Number(s.selectionTo)]})()'),[prefix.length+tail.indexOf('process(item)'),prefix.length+tail.indexOf('process(item)')+13]);await page.evaluate('document.querySelector("[data-collapse-id=\\"2\\"]").scrollIntoView({block:"center"})');await page.click('[data-collapse-id="2"]');assert.equal(await page.evaluate('document.querySelectorAll(".analysis-map-node").length'),3);await page.click('[data-collapse-id="2"]');assert.equal(await page.evaluate('document.querySelectorAll(".analysis-map-node").length'),11);result.cases.push({name:'real block selects its exact source expression; folding/reopening the function reduces/restores the actual map without editing source',ok:true});
 await page.evaluate('document.getElementById("codeAnalysis").scrollTop=0');await page.waitFor('document.getElementById("sirenAppNavigation")?.hidden===false&&!document.getElementById("sirenAppTheme").disabled');await page.click('#sirenAppTheme');await keys('Home','Home',36);await keys('ArrowDown','ArrowDown',40);await keys('Enter','Enter',13);await page.screenshot(join(evidence,'map-dark.png'));await page.waitFor('!document.getElementById("sirenAppTheme").disabled');await page.click('#sirenAppTheme');await keys('Home','Home',36);await keys('ArrowDown','ArrowDown',40);await keys('ArrowDown','ArrowDown',40);await keys('Enter','Enter',13);await page.screenshot(join(evidence,'map-light.png'));result.cases.push({name:'actual Light/Dark optional map retains full-height Code editing area and coloured nested blocks',ok:true});
 await page.click('#analyzeSource');await page.click('#cancelAnalysis');await page.waitFor('document.getElementById("analyzeSource").disabled===false');assert.equal(await page.evaluate('document.querySelectorAll(".analysis-map-node").length'),0);await page.click('#analyzeSource');assert.equal(await page.evaluate('document.getElementById("codeAnalysis").dataset.analysisState'),'running');await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);assert.deepEqual(await projects.readProject(initial.project.id),selected);assert.deepEqual(await sources.exportSource({projectId:initial.project.id,...point}),bytes);
 const activities=driver.logs().split('\n').filter(line=>line.includes('SIREN_ANALYSIS_ACTIVITY'));result.workerActivities=activities;assert.equal(activities.filter(line=>line.includes('worker-started')).length,activities.filter(line=>line.includes('worker-exited')).length);assert.ok(activities.some(line=>line.includes('worker-started')));result.cases.push({name:'actual Clear/Cancel and common Lock admit zero stale blocks, join real workers and preserve complete source/project bytes with all satellites retired',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{result.runtimeLog=driver?.logs().slice(-10000);result.ui=await page?.evaluate('({body:{...document.body.dataset},panel:document.getElementById("codeAnalysis").dataset,status:document.getElementById("analysisStatus").textContent,blocks:document.querySelectorAll(".analysis-map-node").length})');await page?.screenshot(join(evidence,'failure.png'));}catch{}}
finally{if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(receipt){result.package={sourceCommit:receipt.sourceCommit,archive:receipt.appArchive,runtime:receipt.runtimeBinary};result.packageUnchanged=hash(await readFile(join(copy,'App/versions/0.1.0/resources/app.asar')))===receipt.appArchive.sha256&&JSON.stringify(await hashOwnedFile(join(copy,receipt.appRelativePath),1024**3))===JSON.stringify(receipt.runtimeBinary);if(!result.packageUnchanged)result.status='ADVERSE';}if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
