import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {hashOwnedFile} from '../../src/updates/download.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
const evidence=resolve('evidence/source-diff',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');let receipt=null,copy=null;
if(packageRoot){receipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(receipt.kind,'development-preview');assert.equal(receipt.releaseAdmitted,false);copy=join(evidence,'Pachet-Știință-Comparison');await cp(packageRoot,copy,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(await readFile(join(copy,'App/versions/0.1.0/resources/app.asar'))),receipt.appArchive.sha256);assert.deepEqual(await hashOwnedFile(join(copy,receipt.appRelativePath),1024**3),receipt.runtimeBinary);}
const paths=['src/windows/source-context.mjs','src/windows/source-reads.mjs','src/ui/code/commands.js','src/ui/workspace/icons.js','src/ui/workspace/home.js','build/appearance.mjs','build/workspace.mjs','src/main.mjs','src/sources/analysis.mjs','src/sources/analysis-worker.mjs','src/sources/diff-worker.mjs','src/sources/repository.mjs','src/windows/source-analysis.mjs','src/windows/source-barrier.mjs','src/windows/coordinator.mjs','src/windows/preload.cjs','src/ui/code/analysis.js','src/ui/code/editor.js','src/ui/windows/code.js','build/analysis.mjs','build/renderer.mjs','build/windows.mjs','generated/build.json','generated/code-analysis-worker.cjs','generated/windows/code.html','generated/home.html','tests/native/source-diff.mjs','tests/native/drive.mjs','tests/native/attach-page.mjs'];
const capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture(),data=copy?join(copy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const projects=new ProjectStore(data),sources=new SourceRepository(data),initial=await projects.createProject({label:'Actual native immutable comparison',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000;
const leftText=Array.from({length:lineCount},(_,i)=>`item_${i} = ${i} # Ș😀\r\n`).join(''),tail='# EOF literal <img src=x> Ș😀\r\n',rightText=leftText+tail,bytes=[Buffer.from(leftText),Buffer.from(rightText)],refs=[];
for(const b of bytes)refs.push(await sources.importSource({projectId:initial.project.id,bytes:b}));const points=refs.map(({sourceId,version,sha256})=>({sourceId,version,sha256}));
const metadata={kind:'siren-desktop',schema:1,storage:{'t-industries-siren-v23-state':JSON.stringify({diagrams:[{id:'flow',name:'Original',source:'flowchart TD\nA[Original]-->B'}],workpapers:[{id:'doc',title:'Unrelated exact Docs',agent:{id:'AGENT_EXACT'},blocks:[]} ]})},unrelated:'EXACT_UNRELATED'};
assert.equal((await commitManifest({projects,repository:sources,projectId:initial.project.id,baseRevision:1,sourceRefs:refs,metadata,operationId:'native-comparison-initial'})).ok,true);const selected=await projects.readProject(initial.project.id);
if(copy)await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:initial.project.id}));
const result={status:'ADVERSE',scope:'Actual native A/B immutable comparison through two genuine Code windows, exact 300k EOF coverage/navigation, literal previews, Cancel and common Lock. Root implementer evidence only; no independent approval, draft comparison or physical monitor qualification.',inputs,lineCount,sources:points,cases:[]};let driver,page;
const keys=async(key,code,vk,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:vk,modifiers});};
try{
 driver=await launchDesktop(copy?{executable:join(copy,receipt.appRelativePath),packaged:true}:{extraArgs:['--siren-test-root='+data,'--siren-test-project='+initial.project.id]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 for(let i=0;i<points.length;i++){
  await driver.waitFor('document.getElementById("homeModule-code")?.disabled===false');await driver.click('#homeModule-code');
  const selector='.home-library [data-entity-id="'+points[i].sourceId+'"]';await driver.waitFor('document.querySelector('+JSON.stringify(selector)+')!=null');await driver.click(selector);
  await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.views.filter(v=>v.role==="code").length==='+String(i+1)+'})()');await driver.waitFor('document.querySelector(".home-library[open]")==null');
 }
 await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.views.filter(v=>v.role==="code").length===2})()');const views=(await driver.evaluate('window.sirenWindow.listViews()')).views.filter(v=>v.role==='code'),left=views.find(v=>v.entityId===points[0].sourceId),right=views.find(v=>v.entityId===points[1].sourceId);
 page=await attachNativePage(driver,'siren://app/windows/code.html?windowId='+left.windowId);await page.waitFor('document.body.dataset.sourceReady==="true"');await page.click('#toggleAnalysis');await page.click('#analysisScope');await keys('End','End',35);await keys('Enter','Enter',13);await page.waitFor('document.getElementById("analysisCompareWindow").options.length===1&&document.getElementById("analyzeSource").disabled===false');
 assert.equal(await page.evaluate('document.getElementById("analysisCompareWindow").value'),right.windowId);const start=performance.now();await page.click('#analyzeSource');await page.waitFor('document.getElementById("codeAnalysis").dataset.analysisState==="complete"');result.comparisonMs=performance.now()-start;
 assert.match(await page.evaluate('document.getElementById("analysisStatus").textContent'),/Exact comparison/);assert.equal(await page.evaluate('document.querySelectorAll(".analysis-hunk").length'),1);assert.deepEqual(await page.evaluate('[...document.querySelectorAll(".analysis-hunk pre")].map(e=>e.textContent)'),['(empty)',tail]);assert.equal(await page.evaluate('document.querySelectorAll(".analysis-hunk img").length'),0);
 const identity=await page.evaluate('document.getElementById("analysisIdentity").textContent');assert.ok(identity.includes(points[0].sha256)&&identity.includes(points[1].sha256));await page.evaluate('document.querySelector(".analysis-hunk button").scrollIntoView({block:"center"})');await page.click('.analysis-hunk button');assert.deepEqual(await page.evaluate('(()=>{const s=document.querySelector(".siren-code-editor").dataset;return [Number(s.selectionFrom),Number(s.selectionTo)]})()'),[leftText.length,leftText.length]);result.cases.push({name:'actual 300k CRLF/Unicode immutable A/B window selection, exact EOF comparison, literal bounded preview and real editor navigation',ok:true});
 await page.evaluate('document.getElementById("codeAnalysis").scrollTop=0');await page.waitFor('document.getElementById("sirenAppNavigation")?.hidden===false&&!document.getElementById("sirenAppTheme").disabled');await page.click('#sirenAppTheme');await keys('Home','Home',36);await keys('ArrowDown','ArrowDown',40);await keys('Enter','Enter',13);await page.screenshot(join(evidence,'comparison-dark.png'));await page.waitFor('!document.getElementById("sirenAppTheme").disabled');await page.click('#sirenAppTheme');await keys('Home','Home',36);await keys('ArrowDown','ArrowDown',40);await keys('ArrowDown','ArrowDown',40);await keys('Enter','Enter',13);await page.screenshot(join(evidence,'comparison-light.png'));result.cases.push({name:'actual Light/Dark compact comparison within Code without covering the editor',ok:true});
 const bad=await page.evaluate('window.sirenSourceAnalysis.submit('+JSON.stringify({...points[0],kind:'diff',jobId:'forged-version',rightWindowId:right.windowId,rightRef:{...points[1],version:2}})+')');assert.equal(bad.ok,false);assert.equal(bad.code,'ACCESS_REFUSED');result.cases.push({name:'actual native bridge refuses an unopened right version without renderer-controlled path/text or grant widening',ok:true});
 await page.click('#analyzeSource');await page.click('#cancelAnalysis');await page.waitFor('document.getElementById("analyzeSource").disabled===false');assert.equal(await page.evaluate('document.querySelectorAll(".analysis-hunk").length'),0);result.cases.push({name:'actual Cancel drains both-source job and retains zero stale hunks',ok:true});
 await page.click('#analyzeSource');assert.equal(await page.evaluate('document.getElementById("codeAnalysis").dataset.analysisState'),'running');await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);assert.deepEqual(await projects.readProject(initial.project.id),selected);
 for(let i=0;i<points.length;i++)assert.deepEqual(await sources.exportSource({projectId:initial.project.id,...points[i]}),bytes[i]);const activities=driver.logs().split('\n').filter(line=>line.includes('SIREN_ANALYSIS_ACTIVITY'));result.workerActivities=activities;assert.equal(activities.filter(line=>line.includes('worker-started')).length,activities.filter(line=>line.includes('worker-exited')).length);assert.ok(activities.some(line=>line.includes('worker-started')));result.cases.push({name:'common Lock joins actual workers and retires both native windows with complete exact project and source-byte preservation',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{result.runtimeLog=driver?.logs().slice(-10000);result.ui=await page?.evaluate('({body:{...document.body.dataset},panel:document.getElementById("codeAnalysis").dataset,status:document.getElementById("analysisStatus").textContent,identity:document.getElementById("analysisIdentity").textContent})');await page?.screenshot(join(evidence,'failure.png'));}catch{}}
finally{if(driver)await writeFile(join(evidence,'electron.log'),driver.logs());await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(receipt){result.package={sourceCommit:receipt.sourceCommit,archive:receipt.appArchive,runtime:receipt.runtimeBinary};result.packageUnchanged=hash(await readFile(join(copy,'App/versions/0.1.0/resources/app.asar')))===receipt.appArchive.sha256&&JSON.stringify(await hashOwnedFile(join(copy,receipt.appRelativePath),1024**3))===JSON.stringify(receipt.runtimeBinary);if(!result.packageUnchanged)result.status='ADVERSE';}if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
