import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';

const evidence=resolve('evidence/source-sync',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const packageAt=process.argv.indexOf('--package'),packageRoot=packageAt<0?null:resolve(process.argv[packageAt+1]||'');
let packageReceipt=null,packageCopy=null;
if(packageRoot){
 packageReceipt=JSON.parse(await readFile(join(packageRoot,'BUILD-IDENTITY.json'),'utf8'));assert.equal(packageReceipt.kind,'development-preview');assert.equal(packageReceipt.releaseAdmitted,false);
 packageCopy=join(evidence,'Pachet-Știință-Sync');await cp(packageRoot,packageCopy,{recursive:true,errorOnExist:true,force:false});
 const archive=await readFile(join(packageCopy,'App','versions','0.1.0','resources','app.asar'));assert.equal(createHash('sha256').update(archive).digest('hex'),packageReceipt.appArchive.sha256);
}
const data=packageCopy?join(packageCopy,'Data'):join(evidence,'owned-data');await mkdir(data,{recursive:true});
const paths=['src/main.mjs','src/sources/ipc.mjs','src/windows/working-sources.mjs','src/windows/coordinator.mjs','src/windows/preload.cjs','src/ui/windows/code.js','src/ui/code/source-changes.js','src/ui/code/editor.js','generated/windows/code.html','tests/native/source-sync.mjs','tests/native/attach-page.mjs'];
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),capture=async()=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,hash(await readFile(path))]))),inputs=await capture();
const projects=new ProjectStore(data),sources=new SourceRepository(data),original=await projects.createProject({label:'Actual shared Code views',json:'{}'}),lineCount=process.argv.includes('--300k')?300000:100000;
const text=Array.from({length:lineCount},(_,i)=>`value_${i} = ${i} # Python Ș😀`).join('\n')+'\n',ref=await sources.importSource({projectId:original.project.id,bytes:Buffer.from(text)});
assert.equal((await commitManifest({projects,repository:sources,projectId:original.project.id,baseRevision:1,sourceRefs:[ref],metadata:{workpapers:[{id:'doc-a',title:'Keep Docs',blocks:[{kind:'knowledge',rows:[{id:'row-a',sourceRef:{sourceId:ref.sourceId,version:1,sha256:ref.sha256}}]}]}]},operationId:'initial-sync-source'})).ok,true);
const selected=await projects.readProject(original.project.id),result={status:'ADVERSE',inputs,lineCount,cases:[],scope:'Actual native same-source working windows: clean coalesced refresh, dirty local retention, separate latest review, real explicit replacement confirmation/cancellation and all-view Lock. No concurrent merge or physical-monitor qualification.'};let driver;
if(packageReceipt){await writeFile(join(data,'session-selection.json'),JSON.stringify({schema:1,accountId:null,projectId:original.project.id}));result.package={sourceCommit:packageReceipt.sourceCommit,archive:packageReceipt.appArchive,runtime:packageReceipt.runtimeBinary};}
const keys=async(page,key,code,windowsVirtualKeyCode,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode,modifiers});};
const append=async(page,name,version)=>{const insertion=`\ndef ${name}(context: dict[str, int]) -> int:\n    return sum(context.values())\n`;await page.click('.cm-content');await keys(page,'End','End',35,2);await keys(page,'Enter','Enter',13);await page.send('Input.insertText',{text:insertion.slice(1)});await page.waitFor(`document.body.dataset.sourceReady==="true"&&Number(document.body.dataset.sourceVersion)===${version}`);return insertion;};
const confirmReplace=async(page,accept)=>{
 await page.send('Page.enable');const from=driver.events.length,click=page.click('#replaceLatestSource');let found=false;
 try{const until=Date.now()+20000;while(Date.now()<until){found=driver.events.slice(from).some(event=>event.method==='Target.receivedMessageFromTarget'&&(()=>{try{const message=JSON.parse(event.params.message);return message.method==='Page.javascriptDialogOpening'&&message.params.type==='confirm'&&message.params.message.startsWith('Discard the local text in this window');}catch{return false;}})());if(found)break;await delay(20);}assert.equal(found,true,'Actual native confirmation must open');await page.send('Page.handleJavaScriptDialog',{accept});await click;}catch(error){await click.catch(()=>{});throw error;}
};
try{
 driver=await launchDesktop(packageCopy?{executable:join(packageCopy,packageReceipt.appRelativePath),packaged:true}:{extraArgs:[`--siren-test-root=${data}`,`--siren-test-project=${original.project.id}`]});result.ownedPid=driver.pid;await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 await driver.waitFor('document.getElementById("homeModule-code")!=null');await driver.click('#homeModule-code');await driver.waitFor('document.querySelector(".home-library [data-entity-id]")!=null');await driver.click('.home-library [data-entity-id]');
 await driver.waitFor('(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.some(v=>v.role==="code")})()');let views=(await driver.evaluate('window.sirenWindow.listViews()')).views;const immutable=views.find(view=>view.role==='code'),reader=await attachNativePage(driver,'siren://app/windows/code.html?windowId='+immutable.windowId);await reader.waitFor('document.body.dataset.sourceReady==="true"');
 const openWorking=async()=>{const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(view=>view.windowId);await reader.click('#openWorkingCopy');await driver.waitFor(`(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>${before.length}})()`);const view=(await driver.evaluate('window.sirenWindow.listViews()')).views.find(view=>!before.includes(view.windowId));const page=await attachNativePage(driver,'siren://app/windows/code.html?windowId='+view.windowId);await page.waitFor('document.body.dataset.sourceReady==="true"');return {view,page};};
 const first=await openWorking(),second=await openWorking();const one=await append(first.page,'first_agent',3);await first.page.click('[data-command=save]');await first.page.waitFor('document.querySelector(".siren-code-editor").textContent.includes("Source saved")');
 await second.page.waitFor('document.body.dataset.sourceReady==="true"&&document.body.dataset.sourceVersion==="3"');const actual3=await sources.getMetrics({projectId:original.project.id,sourceId:ref.sourceId});assert.equal(await second.page.evaluate('document.body.dataset.sourceSha256'),actual3.sha256);await keys(second.page,'End','End',35,2);assert.equal(await second.page.evaluate('document.querySelector(".cm-content").textContent.includes("def first_agent")'),true);
 assert.equal(await reader.evaluate('document.body.dataset.sourceVersion'),'1');assert.deepEqual(await projects.readProject(original.project.id),selected);assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:3}),Buffer.from(text+one));
 result.cases.push({name:'actual owner notifications coalesce two real Python edits into an exact clean sibling reload while immutable Code and Docs/project remain unchanged',ok:true});
 const two=await append(second.page,'second_agent',5);await first.page.waitFor('document.body.dataset.sourceReady==="true"&&document.body.dataset.sourceVersion==="5"');const three=await append(first.page,'third_agent',7);await first.page.click('[data-command=save]');await first.page.waitFor('document.querySelector(".siren-code-editor").textContent.includes("Source saved")');
 await second.page.waitFor('document.getElementById("sourceChangesNotice").hidden===false&&document.getElementById("sourceChangesMessage").textContent.includes("Version 7")');assert.equal(await second.page.evaluate('document.body.dataset.sourceVersion'),'5');await keys(second.page,'End','End',35,2);const kept=await second.page.evaluate('document.querySelector(".cm-content").textContent');assert.equal(kept.includes('def second_agent'),true);assert.equal(kept.includes('def third_agent'),false);
 assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:7}),Buffer.from(text+one+two+three));assert.deepEqual(await projects.readProject(original.project.id),selected);await second.page.screenshot(join(evidence,'local-text-retained.png'));
 result.cases.push({name:'actual dirty sibling retains its stored local version/text and shows a restrained newer-version notice without an automatic replacement',ok:true});
 const before=(await driver.evaluate('window.sirenWindow.listViews()')).views.map(view=>view.windowId);await second.page.click('#reviewLatestSource');await driver.waitFor(`(async()=>{const r=await window.sirenWindow.listViews();return r.ok&&r.views.length>${before.length}})()`);views=(await driver.evaluate('window.sirenWindow.listViews()')).views;const latestView=views.find(view=>!before.includes(view.windowId)),latestPage=await attachNativePage(driver,'siren://app/windows/code.html?windowId='+latestView.windowId);await latestPage.waitFor('document.body.dataset.sourceReady==="true"&&document.body.dataset.sourceVersion==="7"');assert.equal(await second.page.evaluate('document.body.dataset.sourceVersion'),'5');
 await driver.click('#homeLock');await second.page.waitFor('document.getElementById("sourceChangesMessage").textContent.includes("Preparation was refused")&&!document.body.inert&&document.documentElement.style.visibility!=="hidden"');
 assert.equal((await driver.evaluate('window.sirenDesktop.getPinState()')).unlocked,true);const retainedViews=(await driver.evaluate('window.sirenWindow.listViews()')).views;assert.equal(retainedViews.filter(view=>view.role==='code').length,4);assert.equal(retainedViews.filter(view=>view.role==='workspace').length,1);assert.equal(await second.page.evaluate('document.body.dataset.sourceVersion'),'5');assert.equal(await second.page.evaluate('document.body.dataset.sourceReady'),'true');assert.equal(await second.page.evaluate('document.querySelector(".cm-content").textContent.includes("def second_agent")'),true);assert.deepEqual(await projects.readProject(original.project.id),selected);
 result.cases.push({name:'actual stale dirty-view Lock refuses retirement, restores four live native windows and retains the visible local text instead of clearing it',ok:true});
 await confirmReplace(second.page,false);assert.equal(await second.page.evaluate('document.body.dataset.sourceVersion'),'5');assert.deepEqual(await projects.readProject(original.project.id),selected);
 await confirmReplace(second.page,true);await second.page.waitFor('document.body.dataset.sourceReady==="true"&&document.body.dataset.sourceVersion==="7"');assert.equal(await second.page.evaluate('document.getElementById("sourceChangesNotice").hidden'),true);assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:5}),Buffer.from(text+one+two));
 result.cases.push({name:'actual latest source opens separately without replacing local work; real confirmation cancellation retains text, explicit confirmation reloads latest and historical stored version remains exact',ok:true});
 await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(target=>target.url.startsWith('siren://app/windows/')),false);assert.deepEqual(await projects.readProject(original.project.id),selected);assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:7}),Buffer.from(text+one+two+three));
 result.cases.push({name:'actual all-view Lock commits three settled working views, destroys all four Code windows and preserves exact historical/current source and full project',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};try{await driver?.screenshot(join(evidence,'failure.png'));result.runtimeLog=driver?.logs().slice(-5000);result.diagnostics=[];for(const target of (await driver.send('Target.getTargets')).targetInfos.filter(target=>target.url.startsWith('siren://app/windows/code.html'))){const page=await attachNativePage(driver,target.url);result.diagnostics.push(await page.evaluate('({url:location.href,status:document.getElementById("viewStatus")?.textContent,body:{...document.body.dataset},notice:document.getElementById("sourceChangesMessage")?.textContent,editor:document.querySelector(".siren-code-editor")?.textContent.slice(0,200)})'));await page.screenshot(join(evidence,'view-failure-'+result.diagnostics.length+'.png'));}}catch{}}
finally{await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
