import test from 'node:test';import assert from 'node:assert/strict';
let observed,stream;try{({isAggregateFlowObserved:observed,isAggregateStreamObserved:stream}=await import('./terminal-aggregate-flow-verdict.mjs'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
const hash='a'.repeat(64);
function fixture(){const ring=(next)=>({receivedUtf8Bytes:next,nextSequence:next,retainedUtf8Bytes:Math.min(next,4194304),allocatedBytes:4194304,droppedUtf8Bytes:Math.max(0,next-4194304),firstSequence:Math.max(0,next-4194304),inputWrites:1,inputWriteAttempts:1,inputUtf8Bytes:100,inputWriteSha256:hash,inputAttemptSha256:hash,open:false,unavailable:false});const locked=ring(5000000),final={...ring(5000001),inputWrites:2,inputWriteAttempts:2,inputUtf8Bytes:250,open:true};return{flood:{admitted:false,minimumMs:62000,elapsedMs:62001,byteCap:134217728,generatedAsciiBytes:4997120,blocks:610,startedQpc:1000,finishedQpc:62002000,qpcFrequency:1000000},commands:{first:{bytes:100,sha256:hash},fresh:{bytes:150,sha256:hash}},locked:{result:{ok:false},stats:locked},completedWhileLocked:locked,finalStats:final,finalScanner:{seen:['start','done','fresh']},samples:[{ageMs:100,stats:locked,gap:{fromSequence:0,resumeSequence:805696,droppedUtf8Bytes:805696,resetParser:true},chunks:[{sequence:805696,utf8Bytes:32768,sha256:hash}],tailGap:{fromSequence:838464,toSequence:5000000,droppedUtf8Bytes:4161536,resetParser:true,reason:'fixed-probe-tail-selection'}},{ageMs:63000,stats:final,gap:null,chunks:[{sequence:5000000,utf8Bytes:1,sha256:hash}],tailGap:null}],historyReplay:{stats:locked,gap:{fromSequence:0,resumeSequence:805696,droppedUtf8Bytes:805696,resetParser:true},chunks:[{sequence:805696,utf8Bytes:32768,sha256:hash}]},controller:{nativeExecutionAdmitted:false,requests:90,dataPending:0,control:{pending:0},gateAckMs:[20,20,20],inputAckMs:[20,20]}};}
test('stream oracle accepts complete conservation and refuses removed/forged gaps, bytes, input and clock contradictions',()=>{assert.equal(typeof stream,'function');const original=fixture();assert.equal(stream(original,70000),true);for(const mutate of [r=>{r.samples[0].tailGap=null;},r=>{r.samples[0].gap=null;},r=>{r.finalStats.receivedUtf8Bytes++;},r=>{r.samples[1].chunks[0].sequence++;},r=>{r.completedWhileLocked.inputWriteAttempts=2;},r=>{r.flood.finishedQpc=r.flood.startedQpc;},r=>{r.historyReplay.stats.inputWrites=2;},r=>{r.controller.gateAckMs[1]=501;},r=>{r.samples.at(-1).stats={...r.finalStats,nextSequence:5000002};}]){const r=structuredClone(original);mutate(r);assert.equal(stream(r,70000),false);}});
test('aggregate oracle rejects empty/partial and copied one-session approvals',()=>{assert.equal(typeof observed,'function');for(const r of [null,{},fixture(),{native:{status:'AGGREGATE_FLOW_OBSERVED_NOT_ADMITTED',admitted:false,slots:Array(8).fill(fixture())}}])assert.equal(observed(r),false);});
test('review regressions: exact live main/utility binding and distinct pressure slots/maxima',()=>{const baseline=aggregate();assert.equal(observed(baseline),true);for(const mutate of [v=>{const omit=new Set([v.observer.main.pid,v.native.hostBefore.root.pid]);v.observer.before=v.observer.before.filter(p=>!omit.has(p.pid));v.observer.after=v.observer.after.filter(p=>!omit.has(p.pid));for(const s of v.observer.samples){s.heldCount-=2;s.active-=2;}},v=>{v.observer.main.createdFileTime+='9';},v=>{v.native.hostBefore.root.alive=false;},v=>{for(const t of v.native.pressure.views)t.slot=0;},v=>{v.native.pressure.maxOutstandingUtf8Bytes=0;},v=>{v.native.pressure.views[0].slot=8;},v=>{v.native.pressure.views[0].slot=0.5;},v=>{v.native.hostBefore.held[0].alive=false;},v=>{v.observer.before[0].alive=false;},v=>{v.observer.after[0].exitCode=1;}]){const v=structuredClone(baseline);mutate(v);assert.equal(observed(v),false,mutate.toString());}});
test('separate held Electron infrastructure is retained exactly; missing/mismatched/unknown helper is refused',()=>{const v=aggregate(),helper={pid:900,image:v.observer.main.image,createdFileTime:'100900',alive:true};v.observer.before.push(helper);v.observer.after.push({...helper,alive:false,exitCode:0});for(const s of v.observer.samples){s.active++;s.heldCount++;}assert.equal(observed(v),true);for(const mutate of [r=>{r.observer.after.pop();},r=>{r.observer.before.at(-1).image='C:/unknown/helper.exe';r.observer.after.at(-1).image='C:/unknown/helper.exe';},r=>{r.observer.after.at(-1).createdFileTime='100901';},r=>{r.observer.after.at(-1).exitCode=1;}]){const r=structuredClone(v);mutate(r);assert.equal(observed(r),false);}});
function aggregate(){
 const member=pid=>({pid,image:'C:/fixed/'+(pid===1||pid===2||pid%10===0?'electron.exe':pid%10===1?'powershell.exe':'fixture.exe'),createdFileTime:String(100000+pid),alive:true});
 const slots=Array.from({length:8},(_,slot)=>{const r=fixture(),held=Array.from({length:6},(_,i)=>member(10+slot*10+i)),before={root:held[0],shell:held[1],held,active:6,killOnClose:true,breakaway:false,inheritable:false},stopped=structuredClone(before);stopped.active=0;stopped.held.forEach(p=>{p.alive=false;p.exitCode=77;});stopped.root=stopped.held[0];stopped.shell=stopped.held[1];return{...r,slot,before,stopped,sessionClosed:true,stopMs:30,fixturePids:Object.fromEntries(['root','branch','grandchild','detached'].map((k,i)=>[k,held[i+2].pid])),worker:{workerPid:held[0].pid,rootPid:held[1].pid,osConpty:true,useConptyDll:false,nodePty:'1.1.0'}};});
 const hostBefore={root:member(2),held:[member(2),...slots.flatMap(s=>s.before.held)],active:49,killOnClose:true,breakaway:false,inheritable:false};
 const credit=(bytes,closed=false)=>({outstandingUtf8Bytes:bytes,inFlightBytes:0,payloadUtf8Bytes:bytes,maxOutstandingUtf8Bytes:2097152,maxInFlightBytes:262144,views:closed?[]:slots.map(s=>({slot:s.slot,pendingUtf8Bytes:bytes/8})),attachments:closed?0:8,closed});
 const pressure=credit(2097152),afterLock=credit(0,true),finalDelivery=credit(0);
 const native={admitted:false,status:'AGGREGATE_FLOW_OBSERVED_NOT_ADMITTED',runtime:{electron:'44.5.1',modules:'149',arch:'x64',platform:'win32'},ageMs:70000,slots,hostBefore,hostClosed:true,ninth:{code:'SESSION_CAPACITY_REFUSED',bootstrapPresent:false},lockSynchronous:true,oldAckRefused:8,blockedReadTransportCalls:0,commonOverlapMs:62001,siblingsAfterFirstStop:slots.slice(1).map(s=>s.before),pressure,afterLock,finalDelivery,creditSamples:[pressure,afterLock,finalDelivery]};
 const ready={mainPid:1,host:hostBefore,slots:slots.map(({slot,worker,before,fixturePids})=>({slot,worker,before,fixturePids}))},finish={mainPid:1,commonOverlapMs:62001,slots:slots.map(({slot,flood,finalStats,controller})=>({slot,flood,finalStats,controller}))};
 const before=[member(1),...hostBefore.held],after=before.map(p=>({...p,alive:false,exitCode:p.pid===1||p.pid===2?0:77}));
 const observer={admitted:false,status:'AGGREGATE_FLOW_SAFETY_OBSERVED_NOT_ADMITTED',ageMs:71000,main:member(1),ready,finish,before,after,cleanupVerified:true,safetyOpenAtObservation:true,activeBeforeSafetyCleanup:0,measurementMs:63000,peakSafetyJobMemoryBytes:1000000,samples:[0,60000].map(intervalMs=>({intervalMs,ageMs:intervalMs+100,peakSafetyJobMemoryBytes:1000000,heldCount:50,active:50}))};return{native,observer,ready,finish};
}
test('synthetic full eight-session receipt accepts and aggregate identity/overlap/credit/lifecycle contradictions refuse',()=>{const good=aggregate();assert.equal(observed(good),true);const changes=[v=>{v.native.slots[7]=v.native.slots[0];},v=>{v.native.slots[0].before.held[0].pid=0;},v=>{v.native.slots[0].stopped.held[0].exitCode=0;},v=>{v.native.siblingsAfterFirstStop[0].held[0].alive=false;},v=>{v.native.pressure.outstandingUtf8Bytes=2097153;},v=>{v.native.pressure.payloadUtf8Bytes--;},v=>{v.native.afterLock.outstandingUtf8Bytes=1;},v=>{v.native.finalDelivery.inFlightBytes=1;},v=>{v.native.pressure.views[0].pendingUtf8Bytes=262145;},v=>{v.native.ninth.bootstrapPresent=true;},v=>{v.native.lockSynchronous=false;},v=>{v.native.oldAckRefused=7;},v=>{v.native.blockedReadTransportCalls=1;},v=>{v.native.commonOverlapMs=59999;},v=>{v.native.slots[1].flood.startedQpc+=3000000;},v=>{v.native.slots[1].flood.qpcFrequency++;},v=>{v.native.hostBefore.held.pop();},v=>{v.observer.after[2].alive=true;},v=>{v.observer.activeBeforeSafetyCleanup=1;},v=>{v.observer.samples[1].active--;},v=>{v.observer.measurementMs=59999;},v=>{v.observer.peakSafetyJobMemoryBytes=0;},v=>{v.finish.mainPid=2;},v=>{v.native.slots[0].samples[0].tailGap=null;}];for(const change of changes){const v=structuredClone(good);change(v);assert.equal(observed(v),false,change.toString());}});
