import assert from 'node:assert/strict';
import test from 'node:test';
import {isElectronCapacityObserved,isExpectedElectronCapacityRefusal} from './terminal-electron-capacity-verdict.mjs';
function sample(negative=false){
 const labels=[...'ABCDEFGH'],r={status:negative?'EXPECTED_EIGHT_SESSION_ASSIGNMENT_REFUSED':'EIGHT_ELECTRON_CREATORS_OBSERVED_NOT_ADMITTED',admitted:false,negative,os:'10.0.26100',fixtureImage:'C:\\fixture.exe',electronImage:'C:\\electron.exe',systemConhostImage:'C:\\Windows\\System32\\conhost.exe',fixtureAgeMs:negative?5000:3000,stopMs:negative?2001:15,groups:[],before:[],after:[],cleanup:{verified:true,active:0,held:[]},stopWaits:[],workersRssTotalBytes:8*50000000};
 for(const [i,label] of labels.entries()){const workerPid=i*8+1,fixturePids=[2,3,4,5].map(n=>i*8+n),session=negative&&i===0?null:label;
  r.groups.push({label,workerPid,workerBeforeResume:session!==null,rootPid:fixturePids[0],fixturePids,workerReady:{workerPid,rootPid:fixturePids[0],runtime:{electron:'44.5.1',node:'24.21.0',modules:'149',napi:'10',platform:'win32',arch:'x64'},nodePty:'1.1.0',osConpty:true,inputWrites:0,receivedBytes:215,retainedBytes:215,rssBytes:50000000,helperListObserved:true,helperExitCode:0,helperPid:100+i,consolePids:[fixturePids[0],100+i]}});
  for(let j=1;j<=8;j++){const pid=i*8+j;r.before.push({pid,image:j===1?r.electronImage:j<=5?r.fixtureImage:r.systemConhostImage,createdFileTime:String(1000+pid),alive:true,exitCode:259,inA:session==='A',inB:session==='B',session});}
 }
 r.hostActiveBefore=r.before.length;r.after=r.before.map(p=>({...p,...(!negative&&p.session==='A'?{alive:false,exitCode:77}:{})}));r.cleanup.held=r.before.map(p=>({...p,alive:false,exitCode:!negative&&p.session==='A'?77:98}));r.stopWaits=r.before.filter(p=>p.session==='A').map(p=>({pid:p.pid,initialWait:258,finalWait:0,elapsedMs:10}));r.sessionActiveAfterStop=0;return r;
}
test('eight actual worker startup snapshots and held sessions qualify only their bounded observation',()=>{assert.equal(isElectronCapacityObserved(sample()),true);assert.equal(isExpectedElectronCapacityRefusal(sample(true)),true);});
test('capacity needs eight unique groups, exact RSS sum and actual runtime/helper observations',()=>{for(const mutate of [r=>r.groups.pop(),r=>r.groups[7].label='A',r=>r.groups[3].workerReady.runtime.modules='148',r=>r.groups[4].workerReady.helperExitCode=1,r=>r.groups[5].workerReady.inputWrites=1,r=>r.workersRssTotalBytes--,r=>r.os='',r=>r.groups[6].fixturePids[0]=r.groups[0].rootPid]){const r=sample();mutate(r);assert.equal(isElectronCapacityObserved(r),false);}});
test('one stopped session must not stop any of the seven others or leave captured helpers outside groups',()=>{for(const mutate of [r=>r.after[8].alive=false,r=>r.before[63].session=null,r=>r.after[3].exitCode=0,r=>r.cleanup.held[0].exitCode=98,r=>r.stopWaits.pop(),r=>r.stopMs=3000,r=>r.fixtureAgeMs=11000,r=>r.cleanup.active=1]){const r=sample();mutate(r);assert.equal(isElectronCapacityObserved(r),false);}});
test('omitted first assignment is explicit survival evidence, not capacity approval',()=>{const r=sample(true);assert.equal(isElectronCapacityObserved(r),false);r.stopMs=1999;assert.equal(isExpectedElectronCapacityRefusal(r),false);});
