import test from 'node:test';import assert from 'node:assert/strict';
import {inertShellFlowObservation} from './terminal-shell-flow-test-fixture.mjs';
let isShellFlowObserved;try{({isShellFlowObserved}=await import('./terminal-shell-flow-verdict.mjs'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
test('missing, empty and self-asserted status-only results can never qualify native shell flow',()=>{assert.equal(typeof isShellFlowObserved,'function','MISSING_SHELL_FLOW_VERDICT');for(const r of [null,{}, {native:{status:'SHELL_FLOW_OBSERVED_NOT_ADMITTED'},observer:{status:'SHELL_FLOW_SAFETY_OBSERVED_NOT_ADMITTED',cleanupVerified:true}}])assert.equal(isShellFlowObserved(r),false);});
test('explicitly inert internally consistent baseline exercises the accepting branch only',()=>{assert.equal(isShellFlowObserved(inertShellFlowObservation()),true);});
for(const [name,change] of [
 ['short native flood',r=>r.native.flood.elapsedMs=59999],['unbounded output',r=>r.native.samples[0].stats.allocatedBytes=4194305],['input while closed',r=>r.native.completedWhileLocked.inputWrites=2],['unknown attempted input',r=>r.native.completedWhileLocked.inputWriteAttempts=2],['changed command hash',r=>r.native.completedWhileLocked.inputAttemptSha256='c'.repeat(64)],['no fresh output',r=>r.native.finalScanner.seen=['start','done']],['wrong Stop cause',r=>r.native.stopped.held[0].exitCode=0],['missing held member',r=>r.observer.after.pop()],['PID reused',r=>r.observer.after[2].createdFileTime='different'],['duplicate ready altered',r=>r.ready.worker.workerPid=999],['finish altered',r=>r.finish.finalStats.inputWrites=3],['Safety closed early',r=>r.observer.safetyOpenAtObservation=false],['cleanup failed',r=>r.observer.cleanupVerified=false],['memory interval too short',r=>r.observer.measurementMs=59999],['memory samples stop early',r=>r.observer.samples[1].intervalMs=58000],['unknown memory',r=>r.observer.peakSafetyJobMemoryBytes=0],['memory identity changed',r=>r.observer.samples[1].heldCount=7],['slow gate',r=>{r.native.controller.gateAckMs[1]=501;r.finish.controller.gateAckMs[1]=501;r.observer.finish.controller.gateAckMs[1]=501;}],['late family exit',r=>r.native.ageMs=110000],['live after Stop',r=>r.native.stopped.held[0].alive=true],['no explicit truncation',r=>r.native.history.gaps=0],['silently admitted',r=>r.native.admitted=true],['host flags invalid',r=>r.native.before.breakaway=true],['unknown cleanup',r=>r.native.hostCleanupError='unknown'],
])test('refuses inert contradiction: '+name,()=>{const r=inertShellFlowObservation();change(r);
 // Semantic contradictions deliberately preserve duplicate-stage equality so
 // they exercise the intended numeric/identity/cause gates, not an earlier
 // duplicate-ready mismatch. Two dedicated cases test that mismatch itself.
 if(!['duplicate ready altered','finish altered'].includes(name)){
  r.ready.session=structuredClone(r.native.before);r.ready.host=structuredClone(r.native.hostBefore);r.ready.worker=structuredClone(r.native.worker);r.ready.fixturePids=structuredClone(r.native.fixturePids);r.observer.ready=structuredClone(r.ready);
  r.finish.flood=structuredClone(r.native.flood);r.finish.finalStats=structuredClone(r.native.finalStats);r.finish.controller=structuredClone(r.native.controller);r.observer.finish=structuredClone(r.finish);
 }
 assert.equal(isShellFlowObserved(r),false);});
