// Publication/checkout parity, no native entrypoint imports or execution.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir,lstat} from 'node:fs/promises';
let findMissingRelativeImports;try{({findMissingRelativeImports}=await import('./terminal-publication-closure.mjs'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
const desktop=new URL('../../',import.meta.url),before=JSON.parse(await readFile(new URL('tests/fixtures/terminal-shell-flow-publication-before.json',desktop)));
const foundations=['contracts','input-gate','gate-link','output'].map(n=>'desktop/src/terminal/'+n+'.mjs');
const roots=(await readdir(new URL('./',import.meta.url))).filter(n=>/terminal-shell-flow.*\.mjs$|terminal-publication-closure.*\.mjs$/.test(n)).map(n=>'desktop/tests/native/'+n);
const sources=[];for(const path of [...roots,...foundations])try{sources.push({path,content:await readFile(new URL(path.slice(8),desktop),'utf8')});}catch(e){if(e.code!=='ENOENT')throw e;}
test('exact failed-CI tree projection reproduces two missing foundations before any native work',()=>{assert.equal(typeof findMissingRelativeImports,'function','MISSING_PUBLICATION_CLOSURE');const available=[...before.paths,...roots];assert.deepEqual(findMissingRelativeImports({sources,availablePaths:available}).missingPaths,['desktop/src/terminal/gate-link.mjs','desktop/src/terminal/input-gate.mjs']);});
test('adding exact pure foundations closes the fixed literal-import graph',()=>{assert.equal(typeof findMissingRelativeImports,'function');assert.deepEqual(findMissingRelativeImports({sources,availablePaths:[...before.paths,...roots,...foundations]}).missingPaths,[]);});
test('actual checkout contains every fixed literal dependency needed by shell-flow before native execution',async()=>{assert.equal(typeof findMissingRelativeImports,'function');const graph=findMissingRelativeImports({sources,availablePaths:[]}),actual=[];for(const path of graph.requiredPaths)try{const st=await lstat(new URL(path.slice(8),desktop));if(st.isFile()&&!st.isSymbolicLink())actual.push(path);}catch(e){if(e.code!=='ENOENT')throw e;}assert.deepEqual(findMissingRelativeImports({sources,availablePaths:actual}).missingPaths,[]);});
