// Test-worker control seam, not a production manager/bridge or native evidence.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
let createShellFlowCore;
try{({createShellFlowCore}=await import('./terminal-shell-flow-core.mjs'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
const setup=()=>{assert.equal(typeof createShellFlowCore,'function');const writes=[],resizes=[];return {core:createShellFlowCore({write:data=>writes.push(data),resize:(c,r)=>resizes.push([c,r])}),writes,resizes};};
test('starts closed and refuses input before any host acknowledgement',()=>{const {core,writes}=setup();assert.equal(core.submit(0,'help\r').ok,false);assert.equal(writes.length,0);assert.equal(core.stats().inputWrites,0);});
test('open gate permits exact UTF8 bytes and closing synchronously blocks new writes',()=>{const {core,writes}=setup();assert.deepEqual(core.applyGate({generation:1,open:true}),{ok:true,generation:1,open:true});const command="Write-Output 'Șiren 🔒'\r";assert.equal(core.submit(1,command).ok,true);assert.deepEqual(core.applyGate({generation:2,open:false}),{ok:true,generation:2,open:false});assert.equal(core.submit(1,'old\r').ok,false);assert.equal(core.submit(2,'locked\r').ok,false);assert.deepEqual(writes,[command]);assert.equal(core.stats().inputUtf8Bytes,Buffer.byteLength(command));});
test('stale gate cannot reopen; fresh generation is needed after unlock',()=>{const {core,writes}=setup();core.applyGate({generation:1,open:true});core.applyGate({generation:2,open:false});assert.equal(core.applyGate({generation:1,open:true}).ok,false);assert.equal(core.applyGate({generation:2,open:true}).ok,false);core.applyGate({generation:3,open:true});assert.equal(core.submit(1,'stale').ok,false);assert.equal(core.submit(3,'fresh\r').ok,true);assert.deepEqual(writes,['fresh\r']);});
test('output continues while closed and readback emits zero input',()=>{const {core,writes}=setup();core.append('before\r\n');core.applyGate({generation:1,open:false});core.append('command completed while locked\r\n');const output=core.read({fromSequence:0});assert.match(output.chunks.map(c=>c.data).join(''),/completed while locked/);assert.equal(writes.length,0);assert.equal(core.stats().receivedUtf8Bytes,Buffer.byteLength('before\r\ncommand completed while locked\r\n'));});
test('long closed output stays within4MiB and replay reports a gap with zero writes',()=>{const {core,writes}=setup();for(let i=0;i<192;i++)core.append('x'.repeat(32768));const s=core.stats();assert.equal(s.receivedUtf8Bytes,6291456);assert.equal(s.retainedUtf8Bytes,4194304);assert.equal(s.allocatedBytes,4194304);assert.equal(s.droppedUtf8Bytes,2097152);const r=core.read({fromSequence:0});assert.equal(r.gap.droppedUtf8Bytes,2097152);assert.ok(r.chunks.reduce((n,c)=>n+c.utf8Bytes,0)<=32768);assert.equal(writes.length,0);});
test('eight controlled rings retain at most32MiB in aggregate',()=>{const cores=Array.from({length:8},()=>setup().core);for(const c of cores)for(let i=0;i<160;i++)c.append('x'.repeat(32768));assert.equal(cores.reduce((n,c)=>n+c.stats().retainedUtf8Bytes,0),33554432);assert.equal(cores.reduce((n,c)=>n+c.stats().allocatedBytes,0),33554432);});
for(const [name,generation,data]of [['stale',0,'x'],['negative',-1,'x'],['fractional',1.5,'x'],['empty',1,''],['nontext',1,42],['lone surrogate',1,'\ud800'],['oversize ASCII',1,'x'.repeat(32769)],['oversize Unicode',1,'🔒'.repeat(8193)]])test('refuses '+name+' submission without partial write',()=>{const {core,writes}=setup();core.applyGate({generation:1,open:true});assert.equal(core.submit(generation,data).ok,false);assert.equal(writes.length,0);});
test('exact32KiB UTF8 input is permitted whole',()=>{const {core,writes}=setup();core.applyGate({generation:1,open:true});const data='🔒'.repeat(8192);assert.equal(core.submit(1,data).ok,true);assert.deepEqual(writes,[data]);});
test('resize is gated and bounded without affecting already written commands',()=>{const {core,writes,resizes}=setup();assert.equal(core.fit(0,80,24).ok,false);core.applyGate({generation:1,open:true});core.submit(1,'fixed command\r');assert.equal(core.fit(1,80,24).ok,true);for(const dims of [[1,24],[501,24],[80,0],[80,201],[80.5,24]])assert.equal(core.fit(1,...dims).ok,false);core.applyGate({generation:2,open:false});assert.equal(core.fit(1,100,40).ok,false);assert.deepEqual(resizes,[[80,24]]);assert.deepEqual(writes,['fixed command\r']);});
test('write failure permanently fences this worker rather than retrying ambiguous input',()=>{assert.equal(typeof createShellFlowCore,'function');let calls=0;const core=createShellFlowCore({write:()=>{calls++;throw Error('fixture write failed');},resize:()=>{}});core.applyGate({generation:1,open:true});assert.equal(core.submit(1,'once').ok,false);assert.equal(core.applyGate({generation:2,open:true}).ok,false);assert.equal(core.submit(2,'retry').ok,false);assert.equal(calls,1);assert.equal(core.stats().unavailable,true);});
test('output remains readable after writer loss; constructor rejects missing PTY seams',()=>{assert.equal(typeof createShellFlowCore,'function');assert.throws(()=>createShellFlowCore({write:()=>{}}));const core=createShellFlowCore({write:()=>{throw Error('failure');},resize:()=>{}});core.applyGate({generation:1,open:true});core.submit(1,'once');core.append('last output');assert.equal(core.read({fromSequence:0}).chunks[0].data,'last output');});
test('exact accepted input bytes are hashed only at the one write seam; reads and stale input cannot change them',()=>{const {core}=setup();core.applyGate({generation:1,open:true});const data='Șiren 😀\r';core.submit(1,data);core.applyGate({generation:2,open:false});core.submit(1,'stale');core.read({fromSequence:0});const expected=createHash('sha256').update(data).digest('hex');assert.equal(core.stats().inputWriteSha256,expected);assert.equal(core.stats().inputAttemptSha256,expected);});
test('uncertain throwing write is captured as an attempt and never misreported as accepted bytes',()=>{const core=createShellFlowCore({write:()=>{throw Error('uncertain');},resize:()=>{}});core.applyGate({generation:1,open:true});core.submit(1,'once');assert.equal(core.stats().inputAttemptSha256,createHash('sha256').update('once').digest('hex'));assert.equal(core.stats().inputWriteSha256,createHash('sha256').digest('hex'));});
