// Real pure cores/credit accounting; no PTY/native execution or admission.
import test from 'node:test';import assert from 'node:assert/strict';
import {createShellFlowCore} from './terminal-shell-flow-core.mjs';
let createAggregateFlowDelivery;try{({createAggregateFlowDelivery}=await import('./terminal-aggregate-flow-delivery.mjs'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
const MB=1024*1024;
test('detaching one view releases only its frames and fences a late read from its replacement',async()=>{assert.equal(typeof createAggregateFlowDelivery,'function');let resolve;const d=createAggregateFlowDelivery({read:()=>new Promise(r=>{resolve=r;})});d.resume();const a=d.attach(0).value,b=d.attach(1).value;const pending=d.read(a);assert.equal(d.detach(a).ok,true);assert.equal(d.detach(a).code,'LEASE_STALE');assert.equal(d.stats().views.length,1);assert.equal(d.stats().inFlightBytes,32768);const fresh=d.attach(0,4).value;assert.equal((await d.read(fresh)).code,'TEST_LANE_BUSY');resolve({result:{chunks:[{sequence:0,data:'late',utf8Bytes:4}],nextSequence:4,gap:null}});assert.equal((await pending).code,'LEASE_STALE');assert.equal(d.stats().inFlightBytes,0);assert.equal(d.ack(b,0).ok,true);assert.equal(d.detach(fresh).ok,true);assert.equal(d.stats().views.length,1);});
function fixture(){assert.equal(typeof createAggregateFlowDelivery,'function','MISSING_AGGREGATE_DELIVERY');const cores=Array.from({length:8},()=>createShellFlowCore({write(){throw Error('no input');},resize(){}}));let calls=0;const delivery=createAggregateFlowDelivery({read:async(slot,cursor)=>{calls++;return {result:cores[slot].read({fromSequence:cursor}),stats:cores[slot].stats()};}});delivery.resume();const tokens=cores.map((_,i)=>delivery.attach(i).value);return{cores,delivery,tokens,calls:()=>calls};}
test('eight native-ring seams reach exact2MiB unacknowledged output and ninth/read-over-budget never invokes transport',async()=>{const f=fixture();for(const c of f.cores)c.append('x'.repeat(5*MB));assert.equal(f.delivery.attach(8).code,'CAPACITY_EXCEEDED');for(const t of f.tokens)for(let i=0;i<8;i++)assert.equal((await f.delivery.read(t)).ok,true);const s=f.delivery.stats();assert.equal(s.outstandingUtf8Bytes,2*MB);assert.equal(s.payloadUtf8Bytes,2*MB);assert.equal(s.inFlightBytes,0);assert.equal(f.cores.reduce((n,c)=>n+c.stats().retainedUtf8Bytes,0),32*MB);const calls=f.calls();for(const t of f.tokens)assert.equal((await f.delivery.read(t)).code,'CAPACITY_EXCEEDED');assert.equal(f.calls(),calls);for(const c of f.cores)c.append('y'.repeat(6*MB));assert.equal(f.delivery.stats().outstandingUtf8Bytes,2*MB);f.delivery.suspend();assert.equal(f.delivery.stats().outstandingUtf8Bytes,0);assert.equal(f.delivery.stats().payloadUtf8Bytes,0);});
test('eight late replies after Lock retain reservations until settled and cannot enter fresh leases',async()=>{assert.equal(typeof createAggregateFlowDelivery,'function');const release=[];const delivery=createAggregateFlowDelivery({read:(slot,cursor)=>new Promise(resolve=>{release[slot]=()=>resolve({result:{chunks:[{sequence:cursor,data:'late',utf8Bytes:4}],nextSequence:cursor+4,gap:null},stats:{}});})});delivery.resume();const old=Array.from({length:8},(_,i)=>delivery.attach(i).value),pending=old.map(t=>delivery.read(t));assert.equal(delivery.stats().inFlightBytes,262144);delivery.suspend();delivery.resume();const fresh=old.map(t=>delivery.attach(t.slot).value);for(const t of fresh)assert.equal((await delivery.read(t)).code,'TEST_LANE_BUSY');assert.equal(delivery.stats().inFlightBytes,262144);release.forEach(fn=>fn());for(const p of pending)assert.equal((await p).code,'LEASE_STALE');assert.equal(delivery.stats().inFlightBytes,0);assert.equal(delivery.stats().payloadUtf8Bytes,0);for(const t of old)assert.equal(delivery.ack(t,4).code,'LEASE_STALE');});
test('UTF8 output and exact cumulative ACK release retained payload only at valid frame boundaries',async()=>{const f=fixture(),t=f.tokens[0];f.cores[0].append('😀'.repeat(8193));const a=await f.delivery.read(t),b=await f.delivery.read(t);assert.equal(a.value.result.chunks[0].utf8Bytes,32768);assert.equal(b.value.result.chunks[0].utf8Bytes,4);assert.equal(f.delivery.ack(t,1).code,'REQUEST_REFUSED');assert.equal(f.delivery.stats().payloadUtf8Bytes,32772);assert.equal(f.delivery.ack(t,32768).value.releasedUtf8Bytes,32768);assert.equal(f.delivery.stats().payloadUtf8Bytes,4);assert.equal(f.delivery.ack(t,32772).ok,true);assert.equal(f.delivery.stats().payloadUtf8Bytes,0);});
test('ring eviction cannot silently refund output still awaiting ACK',async()=>{const f=fixture(),t=f.tokens[0];f.cores[0].append('a'.repeat(MB));await f.delivery.read(t);f.cores[0].append('b'.repeat(6*MB));assert.equal((await f.delivery.read(t)).code,'CAPACITY_EXCEEDED');assert.equal(f.delivery.stats().outstandingUtf8Bytes,32768);assert.equal(f.delivery.ack(t,32768).ok,true);const next=await f.delivery.read(t);assert.equal(next.ok,true);assert.equal(next.value.result.gap.fromSequence,32768);assert.equal(next.value.result.gap.resumeSequence,3*MB);});
test('malformed/oversized transport data revoke that lease and release its finite reservation',async()=>{for(const chunks of [[{sequence:0,data:'x',utf8Bytes:2}],[{sequence:1,data:'x',utf8Bytes:1}],[{sequence:0,data:'x'.repeat(32769),utf8Bytes:32769}],[{sequence:0,data:'\ud800',utf8Bytes:3}]]){assert.equal(typeof createAggregateFlowDelivery,'function');const d=createAggregateFlowDelivery({read:async()=>({result:{chunks,nextSequence:chunks[0].utf8Bytes,gap:null},stats:{}})});d.resume();const t=d.attach(0).value;assert.equal((await d.read(t)).code,'TEST_OUTPUT_REFUSED');assert.equal(d.stats().inFlightBytes,0);assert.equal(d.stats().outstandingUtf8Bytes,0);assert.equal(d.ack(t,0).code,'LEASE_STALE');}});
test('producer stress1GiB keeps32MiB aggregate rings; stale ACK and output Lock never write input',async()=>{const f=fixture(),block='x'.repeat(MB);for(let i=0;i<128;i++)for(const c of f.cores)c.append(block);assert.equal(f.cores.reduce((n,c)=>n+c.stats().retainedUtf8Bytes,0),32*MB);await f.delivery.read(f.tokens[0]);f.delivery.suspend();assert.equal(f.delivery.ack(f.tokens[0],1).code,'LEASE_STALE');assert.equal(f.cores.reduce((n,c)=>n+c.stats().inputWriteAttempts,0),0);assert.equal(f.delivery.nativeExecutionAdmitted,false);});
