import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ProjectStore} from '../../src/projects/store.mjs';
import {SourceRepository} from '../../src/sources/repository.mjs';
import {commitManifest} from '../../src/sources/manifest.mjs';
import {workspaceMetadata} from '../../src/windows/entities.mjs';
import {launchDesktop,unlockDesktop} from './drive.mjs';
import {attachNativePage} from './attach-page.mjs';
import {reserveInspectorPort,attachNativeKeyboard} from './native-keyboard.mjs';
const evidence=resolve('evidence/workspace-dock',new Date().toISOString().replaceAll(':','-'));await mkdir(evidence,{recursive:true});
const paths=['src/ui/windows/identity.js','src/ui/windows/docs.js','src/navigation/window-labels.mjs','src/ui/workspace/home.js','src/ui/shared/chrome.css','src/main.mjs','src/windows/surface.mjs','src/windows/registry.mjs','src/windows/factory.mjs','src/windows/dock-ipc.mjs','src/windows/focus.mjs','src/windows/layout.mjs','src/preload.cjs','src/windows/preload.cjs','src/ui/windows/entry.js','src/ui/windows/shelf.js','src/ui/windows/shelf.css','build/workspace.mjs','build/renderer.mjs','build/windows.mjs','generated/home.html','generated/app.html','generated/windows/code.html','generated/windows/docs.html','tests/native/native-keyboard.mjs','tests/native/workspace-dock.mjs'];
const hash=b=>createHash('sha256').update(b).digest('hex'),capture=async()=>Object.fromEntries(await Promise.all(paths.map(async p=>[p,hash(await readFile(p))]))),inputs=await capture();
const data=join(evidence,'owned-data'),projects=new ProjectStore(data),sources=new SourceRepository(data);await mkdir(data,{recursive:true});
const original=await projects.createProject({label:'Actual Code Docs docking',json:'{}'}),text='def agent(context):\n    return context + 1\n',ref=await sources.importSource({projectId:original.project.id,bytes:Buffer.from(text)});
const document={id:'doc-a',title:'Agent context',blocks:[{id:'text-a',kind:'text',html:'<p>Original context</p>'}]};
assert.equal((await commitManifest({projects,repository:sources,projectId:original.project.id,baseRevision:1,sourceRefs:[ref],metadata:{workpapers:[document],codeFiles:[{id:'agent-file',name:'agent Ș😀.py',sourceRef:{sourceId:ref.sourceId,version:ref.version,sha256:ref.sha256}}]},operationId:'owned-dock-seed'})).ok,true);
const selected=await projects.readProject(original.project.id),result={status:'ADVERSE',inputs,cases:[],scope:'Actual production Code/Docs same native renderer docking, two Code and two Docs, independent dirty state, native resize/visibility, exact save/common Lock. No physical monitor, full Task4 or release admission.'};let driver,native;
const keys=async(page,key,code,keyCode,modifiers=0)=>{for(const type of ['keyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:keyCode,modifiers});};
try{
 const port=await reserveInspectorPort();driver=await launchDesktop({extraArgs:[`--siren-test-root=${data}`,`--siren-test-project=${original.project.id}`,`--inspect=127.0.0.1:${port}`]});native=await attachNativeKeyboard({port,pid:driver.pid});result.ownedPid=driver.pid;
 await unlockDesktop(driver,{pin:'4826',autoSetup:true,surface:'home'});
 await driver.waitFor('document.querySelector(".home-current")!=null&&!document.body.inert');
 assert.equal(await driver.evaluate('document.querySelector(".home-current").textContent'),'Home · Actual Code Docs docking');
 assert.equal(await driver.evaluate('document.querySelector(".home-resume .home-eyebrow").textContent'),'CURRENT PROJECT');
 assert.equal(await driver.evaluate('document.querySelector(".home-resume h2").textContent'),'Actual Code Docs docking');
 await driver.screenshot(join(evidence,'home-project-context.png'));
 const open=async(role,entityId)=>{const response=await driver.evaluate('window.sirenWindow.openView('+JSON.stringify({role,entityId,...(role==='code'?{version:1}:{})})+')');assert.equal(response.ok,true,JSON.stringify(response));const url=`siren://app/windows/${role}.html?windowId=${response.view.windowId}`,page=await attachNativePage(driver,url);await page.waitFor(`document.body.dataset.${role==='code'?'source':'document'}Ready==='true'`);return {view:response.view,url,page};};
 const code=await open('code',ref.sourceId),docs=await open('docs','doc-a');
 const working=async item=>{const response=await item.page.evaluate(item.view.role==='code'?'window.sirenSourceEdit.openWorkingCopy()':'window.sirenDocsEdit.openWorkingCopy()');assert.equal(response.ok,true,JSON.stringify(response));const url=`siren://app/windows/${item.view.role}.html?windowId=${response.view.windowId}`,page=await attachNativePage(driver,url);await page.waitFor(`document.body.dataset.${item.view.role==='code'?'source':'document'}Ready==='true'&&document.body.dataset.${item.view.role==='code'?'source':'document'}Readonly==='false'`);return {view:response.view,url,page};};
 const editCode=await working(code),editDocs=await working(docs),all=[code,docs,editCode,editDocs];
 const before=await Promise.all(all.map(item=>native.surfaceState(item.url)));assert.ok(before.every(s=>s.nativeClass==='BaseWindow'&&s.parents.length===1));
 for(const item of all)await item.page.evaluate('globalThis.__dockIdentity={node:document.querySelector(".cm-editor")||document.getElementById("documentContent"),origin:performance.timeOrigin};true');
 await editDocs.page.click('#documentTitleInput');await keys(editDocs.page,'a','KeyA',65,2);await editDocs.page.send('Input.insertText',{text:'Context kept through docking'});await editDocs.page.waitFor('document.body.dataset.documentDirty==="true"');
 assert.equal(await editDocs.page.evaluate('document.getElementById("viewTitle").textContent'),'Docs · Context kept through docking');assert.equal(await editDocs.page.evaluate('document.querySelector("#documentContent > h1").textContent'),'Context kept through docking');
 for(const mode of ['light','dark']){
  await editDocs.page.evaluate('document.getElementById("documentTheme").value='+JSON.stringify(mode)+';document.getElementById("documentTheme").dispatchEvent(new Event("change"));true');
  assert.equal(await editDocs.page.evaluate('getComputedStyle(document.getElementById("documentTitleInput")).backgroundColor'),mode==='light'?'rgb(255, 255, 255)':'rgb(13, 21, 31)');
  await editDocs.page.screenshot(join(evidence,'docs-edit-'+mode+'.png'));
 }
 await editDocs.page.evaluate('document.getElementById("documentTitleInput").setSelectionRange(2,7);true');
 await editCode.page.click('.cm-content');await keys(editCode.page,'End','End',35,2);await editCode.page.send('Input.insertText',{text:'# Attached draft 😀\n'});await editCode.page.waitFor('document.body.dataset.sourceVersion==="2"');
 assert.deepEqual(await projects.readProject(original.project.id),selected);
 await driver.waitFor('document.querySelectorAll("#nativeWindowShelf [data-window-id]").length===4');
 const codeTab='#nativeWindowShelf [data-window-id="'+editCode.view.windowId+'"]',docsTab='#nativeWindowShelf [data-window-id="'+editDocs.view.windowId+'"]';
 await driver.waitFor('document.querySelector('+JSON.stringify(codeTab)+').textContent.includes("agent Ș😀.py · v2 · Working copy · Unsaved")&&document.querySelector('+JSON.stringify(docsTab)+').textContent.includes("Context kept through docking")&&document.querySelector('+JSON.stringify(docsTab)+').textContent.includes("Unsaved")');
 assert.equal((await editCode.page.evaluate('window.sirenWindowDock.getShelf()')).items.length,1);
 await native.minimizeView(code.url);
 const readerTab='#nativeWindowShelf [data-window-id="'+code.view.windowId+'"]';
 await driver.waitFor('document.querySelector('+JSON.stringify(readerTab)+').textContent.includes("Minimized")');
 assert.equal(await driver.evaluate('(()=>{const t=document.querySelector('+JSON.stringify(readerTab)+'),b=t.getBoundingClientRect(),s=t.querySelector(".native-shelf-state").getBoundingClientRect();return s.width>0&&s.left>=b.left&&s.right<=b.right&&t.getAttribute("aria-label").includes("Minimized");})()'),true);
 await native.windowShortcut(editCode.url,'1');await driver.waitFor('document.hasFocus()&&!document.body.inert');
 await driver.screenshot(join(evidence,'home-named-windows.png'));
 await driver.click(readerTab);assert.equal((await native.windowState(code.url)).minimized,false);
 await driver.waitFor('!document.querySelector('+JSON.stringify(readerTab)+').textContent.includes("Minimized")');
 assert.deepEqual(await projects.readProject(original.project.id),selected);
 result.cases.push({name:'Home identifies selected project without a continuation; shared shelf names actual source/version and independent unsaved Docs, restores a genuinely minimized view without saving or peer-title access',ok:true});
 for(let cycle=0;cycle<3;cycle++)for(const item of all){
   assert.equal((await item.page.evaluate('window.sirenWindowDock.attach('+JSON.stringify({windowId:item.view.windowId})+')')).ok,true);
   const state=await native.surfaceState(item.url),old=before[all.indexOf(item)];
   for(const key of ['contentsId','frameRoutingId','frameProcessId','nativeId'])assert.equal(state[key],old[key],key);
   assert.equal(state.parents.length,1);assert.equal(state.parents[0].bounds.y,48);assert.equal(state.parents[0].drawn,true);assert.equal(state.visible,false);
   assert.equal(await item.page.evaluate('__dockIdentity.node===(document.querySelector(".cm-editor")||document.getElementById("documentContent"))&&__dockIdentity.origin===performance.timeOrigin'),true);
 }
 const current=await Promise.all(all.map(item=>native.surfaceState(item.url)));assert.equal(current.filter(s=>s.parents[0].drawn).length,1);
 assert.equal(await editDocs.page.evaluate('document.getElementById("documentTitleInput").value'),'Context kept through docking');
 assert.deepEqual(await editDocs.page.evaluate('(()=>{const e=document.getElementById("documentTitleInput");return [e.selectionStart,e.selectionEnd];})()'),[2,7]);
 assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:2}),Buffer.from(text+'# Attached draft 😀\n'));
 result.cases.push({name:'12 actual attachments across two Code/two Docs keep exact native frame/contents, DOM, dirty title/selection and source draft; only selected native view is drawn',ok:true});
 await driver.waitFor('document.querySelectorAll("#nativeWindowShelf [data-window-id]").length===4');
 await driver.click('#nativeWindowShelf button:first-child');await driver.waitFor('(async()=>{const r=await window.sirenWindowDock.getShelf();return r.ok&&r.items.every(item=>!item.selected);})()');
 assert.equal((await native.surfaceState(editDocs.url)).parents[0].drawn,false);
 await driver.click('#nativeWindowShelf [data-window-id="'+editCode.view.windowId+'"]');await editCode.page.waitFor('document.body.dataset.nativePlacement==="attached"');
 await keys(editCode.page,'z','KeyZ',90,2);await editCode.page.waitFor('document.body.dataset.sourceVersion==="3"');assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:3}),Buffer.from(text));
 assert.equal((await editCode.page.evaluate('window.sirenWindowDock.detach('+JSON.stringify({windowId:editCode.view.windowId})+')')).ok,true);
 await keys(editCode.page,'y','KeyY',89,2);await editCode.page.waitFor('document.body.dataset.sourceVersion==="4"');assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:4}),Buffer.from(text+'# Attached draft 😀\n'));
 result.cases.push({name:'real shelf return/select and attached Undo plus detached Redo preserve the working editor history and exact immutable source versions',ok:true});
 assert.equal((await editCode.page.evaluate('window.sirenWindowDock.attach('+JSON.stringify({windowId:editCode.view.windowId})+')')).ok,true);
 await native.placeView('siren://app/home.html',{x:40,y:40,width:1120,height:780});
 const hostSize=(await native.surfaceState('siren://app/home.html')).contentBounds;
 await editCode.page.waitFor('innerWidth==='+hostSize.width);const resized=await native.surfaceState(editCode.url);
 assert.deepEqual(resized.parents[0].bounds,{x:0,y:48,width:hostSize.width,height:hostSize.height-48});
 await editCode.page.screenshot(join(evidence,'code-attached.png'));await driver.screenshot(join(evidence,'workspace-shelf.png'));
 assert.equal((await driver.evaluate('window.sirenWindow.focusView('+JSON.stringify({windowId:editDocs.view.windowId})+')')).ok,true);
 await editDocs.page.screenshot(join(evidence,'docs-attached.png'));
 await editDocs.page.click('#saveDocument');await editDocs.page.waitFor('document.body.dataset.documentDirty==="false"');
 const saved=await projects.readProject(original.project.id);assert.equal(workspaceMetadata(saved).workpapers[0].title,'Context kept through docking');assert.deepEqual(saved.sourceRefs,selected.sourceRefs);
 result.cases.push({name:'actual host resize fits the same Code view below the shelf; attached Docs explicitly saves while immutable selected source is retained',ok:true});
 await native.windowShortcut(editDocs.url,'D');await editDocs.page.waitFor('document.body.dataset.nativePlacement==="detached"');assert.equal((await native.surfaceState(editDocs.url)).visible,true);
 await native.windowShortcut(editDocs.url,'A');await editDocs.page.waitFor('document.body.dataset.nativePlacement==="attached"');assert.equal((await native.surfaceState(editDocs.url)).visible,false);
 await native.windowShortcut(editDocs.url,'1');assert.equal((await native.surfaceState(editDocs.url)).parents[0].drawn,false);
 await native.windowShortcut('siren://app/home.html','Right');assert.equal((await native.surfaceState(code.url)).parents[0].drawn,true);
 const monitor=await native.monitorCommand(code.url,0);result.monitor={...monitor,host:await native.windowState('siren://app/home.html'),source:await native.surfaceState(code.url)};
 if(!monitor.ok)result.geometryExperiment=await native.geometryReadbackExperiment('siren://app/home.html',{...result.monitor.host.bounds,width:1120,height:780});
 assert.equal(monitor.ok,true);assert.equal((await native.surfaceState(code.url)).parents[0].drawn,true);
 assert.equal((await native.surfaceState(code.url)).visible,false);
 result.cases.push({name:'actual native attach/detach/main/cycle keys route once to the same editor; attached monitor command moves the visible host and keeps its empty shell hidden',ok:true});
 assert.equal((await driver.evaluate('window.sirenWindowDock.showWorkspace()')).ok,true);await driver.click('#homeLock');await driver.waitFor('window.sirenDesktopBootstrap.mode==="locked"');
 assert.equal(await driver.evaluate('window.sirenDesktopBootstrap.snapshot'),null);assert.equal((await driver.send('Target.getTargets')).targetInfos.some(t=>t.url.startsWith('siren://app/windows/')),false);assert.equal((await driver.evaluate('window.sirenWindowDock.getShelf()')).ok,false);
 assert.deepEqual(await sources.exportSource({projectId:original.project.id,sourceId:ref.sourceId,version:1}),Buffer.from(text));assert.equal(workspaceMetadata(await projects.readProject(original.project.id)).workpapers[0].title,'Context kept through docking');
 result.cases.push({name:'real common Lock saves and destroys all four attached renderers plus hidden shells; locked shelf refuses data and original source remains exact',ok:true});result.status='COMPLETE';
}catch(cause){result.error={message:cause.message,stack:cause.stack};await driver?.screenshot(join(evidence,'failure.png')).catch(()=>{});result.log=driver?.logs();}
finally{native?.close();await driver?.close();result.afterInputs=await capture();result.inputsUnchanged=JSON.stringify(inputs)===JSON.stringify(result.afterInputs);if(!result.inputsUnchanged)result.status='ADVERSE';await writeFile(join(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({evidence,status:result.status,cases:result.cases.length,error:result.error?.message}));process.exitCode=result.status==='COMPLETE'?0:1;}
