const exact = (value, names) => value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).sort().join(',') === names.split(',').sort().join(',');
const version = value => typeof value === 'string' && /^\d{1,5}\.\d{1,5}\.\d{1,5}(?:\.\d{1,5})?(?:-[a-z0-9.]+)?$/.test(value) && value.length <= 64;
export function validateDiagnostics(report) {
  if (!exact(report, 'schema,product,build,runtime,system,mode,accountState,updatePhase,counts') || report.schema !== 1 || report.product !== 'siren' || !exact(report.build, 'desktopVersion,rendererVersion') || !Object.values(report.build).every(version) || !exact(report.runtime, 'electron,chromium,node') || !Object.values(report.runtime).every(version) || !exact(report.system, 'platform,arch,release') || report.system.platform !== 'win32' || report.system.arch !== 'x64' || !version(report.system.release) || !['normal','recovery','readonly'].includes(report.mode) || !['unactivated','online','offline','reauth-required','revoked'].includes(report.accountState) || !['unconfigured','idle','checking','current','available','downloading','ready','applying','error'].includes(report.updatePhase) || !exact(report.counts, 'projects,verifiedPoints,damagedPoints') || !Object.values(report.counts).every(n => Number.isSafeInteger(n) && n >= 0 && n <= 1000000)) throw new Error('Diagnostic export refused: invalid or unexpected field');
  return report;
}
export function buildDiagnostics(context) {
  return validateDiagnostics({ schema: 1, product: 'siren', build: { desktopVersion: context.desktopVersion, rendererVersion: context.rendererVersion }, runtime: { electron: context.electron, chromium: context.chromium, node: context.node }, system: { platform: context.platform, arch: context.arch, release: context.osRelease }, mode: context.mode, accountState: context.accountState, updatePhase: context.updatePhase, counts: { projects: context.projectCount, verifiedPoints: context.verifiedPointCount, damagedPoints: context.damagedPointCount } });
}
