import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join,relative} from 'node:path';
const root=new URL('../',import.meta.url),read=p=>readFile(new URL(p,root)),json=async p=>JSON.parse(await read(p)),sha=async p=>createHash('sha256').update(await read(p)).digest('hex');
const suitePath='evidence/workspace-surface/diagram-layout-full-suite-2026-10-07T11-22-28.486Z/result.json',scopePath='evidence/diagram-layout-supported-scope/2026-10-07T11-24-22.387Z/result.json',nativePath='evidence/workspace-surface/layout-native-regressions-2026-10-07T11-26-49.499Z/result.json';
const suite=await json(suitePath),scope=await json(scopePath),native=await json(nativePath),permanent='tests/native/diagram-layout-render-app.mjs',owner='evidence/workspace-surface/diagram-layout-supported-scope-app-owner.mjs';
for(const record of [suite,native]){assert.equal(record.author,'/root');assert.equal(record.status,'COMPLETE');assert.deepEqual(record.before,record.after);assert.deepEqual(record.changedInputs,[]);}
assert.deepEqual(suite.results.map(r=>[r.name,r.code,r.counts.tests,r.counts.pass,r.counts.fail]),[['identity',0,4,4,0],['units',0,1580,1580,0]]);
const drift=[];for(const [path,expected]of Object.entries(suite.after))if(await sha(path)!==expected)drift.push(path);assert.deepEqual(drift,[permanent]);
for(const [path,expected]of Object.entries(native.after))assert.equal(await sha(path),expected,path+' must match the final native capture');
assert.equal(scope.author,'/root');assert.equal(scope.status,'COMPLETE');assert.equal(scope.cases.length,27);assert.ok(scope.cases.every(c=>c.ok===true));assert.deepEqual(scope.inputs,scope.afterInputs);
assert.equal(await sha(owner),scope.inputs[owner]);const oracle=s=>s.slice(s.indexOf(' const declarations=['),s.indexOf("result.status='COMPLETE';",s.indexOf(' const declarations=[')));
const promoted=oracle((await read(permanent)).toString()),original=oracle((await read(owner)).toString());assert.ok(promoted.length>1500);assert.equal(promoted,original);
for(const [family,minimum]of [['classDiagram',4],['stateDiagram',6],['er',4],['requirement',2]]){const pair=scope.familyGeometries[family];assert.ok(pair.dagre.geometry.length>=minimum);assert.ok(pair.elk.geometry.length>=minimum);assert.notDeepEqual(pair.dagre,pair.elk);for(const geometry of [pair.dagre,pair.elk])for(const node of geometry.geometry){assert.deepEqual(Object.keys(node),['node','text','transform','box']);assert.ok(Object.values(node.box).every(Number.isFinite));}}
assert.equal(native.rows.length,10);let totalCases=0;const rows=[];
for(const row of native.rows){assert.equal(row.code,0);assert.equal(row.receipt.status,'COMPLETE');assert.deepEqual(row.receipt.inputs,row.receipt.afterInputs);assert.equal(await sha('tests/native/'+row.name+'.mjs'),row.harnessSha256);assert.equal(row.receipt.package,undefined);const path=relative(new URL(root).pathname.replace(/^\/([A-Za-z]:)/,'$1'),join(row.evidence,'result.json')).replaceAll('\\','/');const actual=JSON.parse(await readFile(join(row.evidence,'result.json'),'utf8'));assert.deepEqual(actual,row.receipt);totalCases+=actual.cases.length;rows.push({name:row.name,code:row.code,status:actual.status,cases:actual.cases.length,evidence:row.evidence,resultSha256:createHash('sha256').update(await readFile(join(row.evidence,'result.json'))).digest('hex')});}
assert.equal(totalCases,79);const permanentRecord=native.rows.find(r=>r.name==='diagram-layout-render').receipt;assert.equal(permanentRecord.cases.length,27);assert.equal(permanentRecord.inputs[permanent],await sha(permanent));
const originals=[];for(const path of ['evidence/workspace-surface/diagram-catalogue-full-suite-2026-10-07T11-05-20.704Z/result.json','evidence/diagram-layout-native/2026-10-07T11-01-15.468Z/result.json','evidence/diagram-layout-render/2026-10-07T11-15-38.028Z/result.json','evidence/diagram-layout-render/2026-10-07T11-16-46.376Z/result.json','evidence/diagram-layout-render/2026-10-07T11-17-29.648Z/result.json']){const original=await json(path);assert.equal(original.status,'ADVERSE');originals.push({path,sha256:await sha(path),status:original.status,error:original.error?.message,results:original.results});}
const identities=[];for(const path of [suitePath,scopePath,nativePath,permanent,owner,'reviews/2026-10-07-diagram-layout-evidence-addendum.check.mjs'])identities.push({path,sha256:await sha(path),bytes:(await stat(new URL(path,root))).size});
console.log(JSON.stringify({reviewer:'/root/catalogue_view',status:'READ_ONLY_EVIDENCE_ASSERTIONS_COMPLETE',suiteChecks:1584,capturedFiles:Object.keys(suite.after).length,suiteToCurrentDrift:drift,nativeCurrentDrift:[],promotedOracleBytes:promoted.length,promotedOracleIdentical:true,nativeSuites:10,nativeCases:totalCases,rows,originals,identities,limits:'Root executed all runtime/full-suite evidence. Reviewer only checked retained records, hashes and oracle text; no GUI/build/package/hosted/release approval.'},null,2));
