import assert from 'node:assert/strict';
import {readFile,stat,access} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join,sep,relative} from 'node:path';
import * as asar from '@electron/asar';
const desktop=fileURLToPath(new URL('../',import.meta.url)),sourceCommit='beab3cfe9cd86d54ddaf006fe8fbb7a9f1ecb201';
const preview=join(desktop,'dist/development-73428d47-d74e-48d6-b71b-ba42ae2a2bc9'),ownerIdentity='evidence/workspace-surface/appearance-package-identity-2026-10-07T13-12-55.107Z/result.json',programme='evidence/workspace-surface/appearance-package-native-2026-10-07T13-12-55.170Z/result.json';
const bytesHash=b=>createHash('sha256').update(b).digest('hex'),read=p=>readFile(join(desktop,p)),json=async p=>JSON.parse(await read(p));
async function identity(path){const hash=createHash('sha256');for await(const chunk of createReadStream(path))hash.update(chunk);return{bytes:(await stat(path)).size,sha256:hash.digest('hex')};}
const owner=await json(ownerIdentity),receipt=JSON.parse(await readFile(join(preview,'BUILD-IDENTITY.json'),'utf8')),archive=join(preview,'App/versions/0.1.0/resources/app.asar');
assert.equal(owner.status,'COMPLETE');assert.deepEqual(owner.receipt,receipt);assert.equal(receipt.sourceCommit,sourceCommit);assert.equal(receipt.kind,'development-preview');assert.equal(receipt.releaseAdmitted,false);
assert.deepEqual(await identity(archive),receipt.appArchive);assert.deepEqual(await identity(join(preview,receipt.appRelativePath)),receipt.runtimeBinary);assert.deepEqual(await identity(join(preview,'App/versions/0.1.0/resources/siren-process-identity.exe')),receipt.processReader.binary);assert.deepEqual(JSON.parse(await readFile(join(preview,'App/versions/0.1.0/resources/siren-process-identity.json'),'utf8')),receipt.processReader);
const members=[];for(const raw of asar.listPackage(archive)){const stored=raw.replace(/^[/\\]+/,''),metadata=asar.statFile(archive,stored);if(metadata.files)continue;assert.equal(metadata.link,undefined);assert.equal(metadata.unpacked,undefined);const path=stored.replaceAll('\\','/');assert.match(path,/^[A-Za-z0-9_@./-]+$/);assert.equal(path.split('/').includes('..'),false);const bytes=asar.extractFile(archive,stored);members.push({path,bytes:bytes.length,sha256:bytesHash(bytes)});}
members.sort((a,b)=>a.path.localeCompare(b.path));assert.equal(members.length,304);assert.deepEqual(members,[...owner.members].sort((a,b)=>a.path.localeCompare(b.path)));
const src=members.filter(m=>m.path.startsWith('src/')),git='C:/Users/Taras/.cache/codex-runtimes/codex-primary-runtime/dependencies/native/git/cmd/git.exe';
const gitBatch=execFileSync(git,['-c','safe.directory=C:/Claude/SIREN_WORK/portable','cat-file','--batch'],{cwd:desktop,input:src.map(m=>sourceCommit+':desktop/'+m.path+'\n').join(''),maxBuffer:16*1024*1024});
let cursor=0,gitExactSourceMembers=0,gitEolNormalizedSourceMembers=0;const gitEolPaths=[];for(const member of src){const end=gitBatch.indexOf(10,cursor),header=gitBatch.subarray(cursor,end).toString(),match=/^([a-f0-9]{40}) blob (\d+)$/.exec(header);assert.ok(match,member.path+' must exist at exact commit');const size=Number(match[2]),blob=gitBatch.subarray(end+1,end+1+size),packed=asar.extractFile(archive,member.path.replaceAll('/',sep));assert.match(member.path,/\.(?:mjs|cjs)$/);assert.deepEqual(await identity(join(desktop,member.path)),{bytes:member.bytes,sha256:member.sha256},member.path+' must match exact working-tree bytes');assert.ok(Buffer.from(blob.toString('utf8')).equals(blob));assert.ok(Buffer.from(packed.toString('utf8')).equals(packed));if(bytesHash(blob)===member.sha256)gitExactSourceMembers++;else {gitEolNormalizedSourceMembers++;gitEolPaths.push(member.path);}assert.equal(blob.toString('utf8').replaceAll('\r\n','\n'),packed.toString('utf8').replaceAll('\r\n','\n'),member.path+' must match committed source with only CRLF/LF normalization');cursor=end+size+2;}assert.equal(cursor,gitBatch.length);
let generated=0,dependencies=0;for(const member of members.filter(m=>m.path!=='package.json'&&!m.path.startsWith('src/'))){assert.deepEqual(await identity(join(desktop,member.path)),{bytes:member.bytes,sha256:member.sha256},member.path+' must match current frozen generated/dependency bytes');if(member.path.startsWith('generated/'))generated++;else if(member.path.startsWith('node_modules/'))dependencies++;else assert.fail('Unexpected archive group');}
const packageJSON=JSON.parse(asar.extractFile(archive,'package.json'));assert.equal(packageJSON.main,'src/start.mjs');assert.equal(packageJSON.type,'module');
const record={reviewer:'/root/catalogue_view',status:'ARCHIVE_VERIFIED_NATIVE_PENDING',sourceCommit,preview,releaseReceiptFlags:{releaseAdmitted:receipt.releaseAdmitted,inventoryQualified:receipt.inventoryQualified,launcherQualified:receipt.launcherQualified,accountConfigured:receipt.accountConfigured,updatesConfigured:receipt.updatesConfigured},appArchive:receipt.appArchive,runtimeBinary:receipt.runtimeBinary,processReader:receipt.processReader,membersVerified:members.length,committedSourceMembers:src.length,gitExactSourceMembers,gitEolNormalizedSourceMembers,gitEolPaths,generatedMembers:generated,installedDependencyMembers:dependencies,packageJSON,memberManifestSha256:bytesHash(Buffer.from(JSON.stringify(members))),ownerIdentity:{path:ownerIdentity,...await identity(join(desktop,ownerIdentity))},native:{final:false},limits:'Archive/member verification and read-only review of root-executed copied receipts. Source matches exact working tree and exact Git commit after explicitly limited CRLF/LF normalization. Reviewer runs no GUI or package launcher; no production release/hosted approval.'};
try{await access(join(desktop,programme));}catch{console.log(JSON.stringify(record,null,2));process.exit(0);}
const run=await json(programme);record.native={final:true,status:run.status,path:programme,identity:await identity(join(desktop,programme)),author:run.author,capturedFiles:Object.keys(run.before).length,rows:[],changedInputs:run.changedInputs};assert.equal(run.author,'/root');assert.equal(run.status,'COMPLETE');assert.equal(run.results.length,6);assert.deepEqual(run.before,run.after);assert.deepEqual(run.changedInputs,[]);
const copyRoots=new Set();for(const row of run.results){assert.equal(row.code,0);const resultPath=join(row.evidence,'result.json'),actual=JSON.parse(await readFile(resultPath,'utf8'));assert.deepEqual(actual,row.receipt);if(row.name==='shell'){assert.equal(actual.completed,true);assert.equal(actual.checks.length,4);assert.equal(actual.runtime.node,'undefined');assert.equal(actual.runtime.process,'undefined');assert.equal(actual.attack.protocol,403);}else if(row.name==='packaged'){assert.equal(actual.completed,true);assert.equal(actual.sourceCommit,sourceCommit);assert.deepEqual(actual.archive,receipt.appArchive);assert.deepEqual(actual.runtime,receipt.runtimeBinary);assert.equal(actual.probeSha256,row.harnessSha256);assert.equal(actual.saveDiagnostic.flush,'resolved');assert.equal(actual.saveDiagnostic.postReadSha256,actual.acknowledgedProjectSha256);assert.notEqual(actual.initialProjectSha256,actual.acknowledgedProjectSha256);}else{assert.equal(actual.status,'COMPLETE');assert.equal(actual.package.sourceCommit,sourceCommit);assert.deepEqual(actual.package.archive,receipt.appArchive);assert.deepEqual(actual.package.runtime,receipt.runtimeBinary);assert.deepEqual(actual.inputs,actual.afterInputs);assert.ok(actual.packageUnchanged===true||actual.inputsUnchanged===true);assert.ok(actual.cases.every(c=>c.ok===true));}assert.equal((await identity(join(desktop,'tests/native/'+row.name+'.mjs'))).sha256,row.harnessSha256);assert.ok(row.postRunCopies.length>=1);if(actual.package?.copy)assert.equal(actual.package.copy,row.postRunCopies[0].copy);const copies=[];
 for(const copy of row.postRunCopies){assert.equal(copyRoots.has(copy.copy),false,'Every probe owns a separate copy');copyRoots.add(copy.copy);const archiveActual=await identity(join(copy.copy,'App/versions/0.1.0/resources/app.asar')),runtimeActual=await identity(join(copy.copy,receipt.appRelativePath)),helperActual=await identity(join(copy.copy,'App/versions/0.1.0/resources/siren-process-identity.exe'));assert.deepEqual(archiveActual,receipt.appArchive);assert.deepEqual(runtimeActual,receipt.runtimeBinary);assert.deepEqual(helperActual,receipt.processReader.binary);assert.deepEqual(archiveActual,copy.archive);assert.deepEqual(runtimeActual,copy.runtime);assert.deepEqual(helperActual,copy.helper);assert.deepEqual(JSON.parse(await readFile(join(copy.copy,'BUILD-IDENTITY.json'),'utf8')),receipt);assert.deepEqual(JSON.parse(await readFile(join(copy.copy,'App/versions/0.1.0/resources/siren-process-identity.json'),'utf8')),receipt.processReader);copies.push({copy:copy.copy,archive:archiveActual,runtime:runtimeActual,helper:helperActual});}
 record.native.rows.push({name:row.name,status:actual.status??(actual.completed?'COMPLETE':undefined),scope:actual.scope,code:row.code,checks:actual.checks,cases:Array.isArray(actual.cases)?actual.cases.length:undefined,evidence:row.evidence,resultIdentity:await identity(resultPath),harnessSha256:row.harnessSha256,copies});}
assert.equal(run.expectedProgrammes,6);assert.equal(run.allProgrammeCount,6);assert.equal(run.remainingOnly,false);assert.deepEqual(run.excluded,[]);assert.deepEqual(run.results.map(r=>r.name),['workspace-appearance','diagram-edit','diagram-style','diagram-guided','shell','packaged']);record.native.copyCount=copyRoots.size;record.native.postRunBinaryHashes=copyRoots.size*3;record.native.explicitNativeCases=record.native.rows.reduce((sum,r)=>sum+(r.cases??0),0);record.native.probes=run.results.length;record.retainedOriginals=[];for(const path of ['evidence/workspace-surface/render-appearance-full-suite-2026-10-07T12-50-20.524Z/result.json','evidence/workspace-surface/diagram-catalogue-full-suite-2026-10-07T11-05-20.704Z/result.json','evidence/diagram-layout-native/2026-10-07T11-01-15.468Z/result.json','evidence/diagram-layout-render/2026-10-07T11-15-38.028Z/result.json','evidence/diagram-layout-render/2026-10-07T11-16-46.376Z/result.json','evidence/diagram-layout-render/2026-10-07T11-17-29.648Z/result.json']){const original=await json(path);assert.equal(original.status,'ADVERSE');record.retainedOriginals.push({path,...await identity(join(desktop,path)),status:original.status});}assert.equal(record.native.copyCount,8);assert.equal(record.native.postRunBinaryHashes,24);assert.equal(record.native.explicitNativeCases,23);
for(const key of ['releaseAdmitted','inventoryQualified','launcherQualified','accountConfigured','updatesConfigured'])assert.equal(receipt[key],false,key+' stays unqualified');
assert.deepEqual(await identity(join(desktop,'package.json')),members.find(m=>m.path==='package.json')&&{bytes:members.find(m=>m.path==='package.json').bytes,sha256:members.find(m=>m.path==='package.json').sha256});
record.currentCapturedInputVerification={count:0,mismatches:[]};for(const [path,expected]of Object.entries(run.before)){const actual=await identity(join(desktop,path));if(actual.sha256!==expected)record.currentCapturedInputVerification.mismatches.push({path,expected,actual:actual.sha256});record.currentCapturedInputVerification.count++;}assert.deepEqual(record.currentCapturedInputVerification.mismatches,[]);assert.equal(record.currentCapturedInputVerification.count,657);
const buildPath='evidence/workspace-surface/render-appearance-package-build.json',build=await json(buildPath);assert.equal(build.author,'/root');assert.deepEqual(build.receipt,receipt);assert.equal(build.previewRoot,preview);record.buildReceipt={path:buildPath,...await identity(join(desktop,buildPath))};
record.members=members;record.reviewedAt=new Date().toISOString();record.originalFailurePolicy='Original adverse receipts retained and rehashed; not replaced or represented as passed.';
const utilityPath='evidence/render-appearance/2026-10-07T12-49-40.386Z/result.json',utility=await json(utilityPath);assert.equal(utility.status,'COMPLETE');assert.equal(utility.inputsUnchanged,true);assert.deepEqual(utility.inputs,utility.afterInputs);assert.ok(utility.cases.every(c=>c.ok===true));record.developmentSupplement={path:utilityPath,...await identity(join(desktop,utilityPath)),author:utility.author,status:utility.status,caseCount:utility.cases.length,cases:utility.cases.map(c=>c.name),scope:utility.scope,relationship:'Earlier owner-executed development utility evidence; not one of six copied programmes and not independently executed here.',capturedFiles:Object.keys(utility.inputs).length};
record.status='ARCHIVE_AND_FINAL_COPIED_RECEIPTS_VERIFIED';console.log(JSON.stringify(record,null,2));


