import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join,isAbsolute,sep} from 'node:path';
import vm from 'node:vm';
import * as asar from '@electron/asar';
const desktop=fileURLToPath(new URL('../',import.meta.url)),commit='f04b4613dac2338d3ec0fd9f11c42cbc6bc50d9a';
const preview=join(desktop,'dist/development-66f41e93-04f5-4b14-9f9a-de9273ab0259');
const ownerPath='evidence/workspace-surface/help-package-identity-2026-10-07T14-33-43.079Z/result.json';
const batchPath='evidence/workspace-surface/help-package-native-2026-10-07T14-33-43.153Z/result.json';
const git='C:/Users/Taras/.cache/codex-runtimes/codex-primary-runtime/dependencies/native/git/cmd/git.exe';
const hash=b=>createHash('sha256').update(b).digest('hex'),absolute=p=>isAbsolute(p)?p:join(desktop,p),json=async p=>JSON.parse(await readFile(absolute(p),'utf8'));
async function identity(p){const location=absolute(p),h=createHash('sha256');for await(const b of createReadStream(location))h.update(b);return {bytes:(await stat(location)).size,sha256:h.digest('hex')};}
async function reference(p){return {path:p,...await identity(p)};}
const owner=await json(ownerPath),receipt=await json(join(preview,'BUILD-IDENTITY.json')),archive=join(preview,'App/versions/0.1.0/resources/app.asar');
assert.equal(owner.author,'/root');assert.equal(owner.status,'COMPLETE');assert.equal(owner.commit,commit);assert.deepEqual(owner.receipt,receipt);assert.equal(receipt.sourceCommit,commit);assert.equal(receipt.kind,'development-preview');
for(const key of ['releaseAdmitted','inventoryQualified','launcherQualified','accountConfigured','updatesConfigured'])assert.equal(receipt[key],false);
async function verifyCopy(root){const binaries={archive:await identity(join(root,'App/versions/0.1.0/resources/app.asar')),runtime:await identity(join(root,receipt.appRelativePath)),helper:await identity(join(root,'App/versions/0.1.0/resources/siren-process-identity.exe'))};assert.deepEqual(binaries.archive,receipt.appArchive);assert.deepEqual(binaries.runtime,receipt.runtimeBinary);assert.deepEqual(binaries.helper,receipt.processReader.binary);assert.deepEqual(await json(join(root,'BUILD-IDENTITY.json')),receipt);assert.deepEqual(await json(join(root,'App/versions/0.1.0/resources/siren-process-identity.json')),receipt.processReader);return binaries;}
const previewBinaries=await verifyCopy(preview),members=[];
for(const raw of asar.listPackage(archive)){const stored=raw.replace(/^[/\\]+/,''),info=asar.statFile(archive,stored);if(info.files)continue;assert.equal(info.link,undefined);assert.equal(info.unpacked,undefined);const p=stored.replaceAll('\\','/');assert.match(p,/^[A-Za-z0-9_@./-]+$/);assert.equal(p.split('/').includes('..'),false);const b=asar.extractFile(archive,stored);members.push({path:p,bytes:b.length,sha256:hash(b)});}
members.sort((a,b)=>a.path.localeCompare(b.path));assert.equal(members.length,305);assert.deepEqual(members,[...owner.members].sort((a,b)=>a.path.localeCompare(b.path)));
const sources=members.filter(m=>m.path.startsWith('src/')),requests=sources.map(m=>commit+':desktop/'+m.path+'\n').join('');
const gitBytes=execFileSync(git,['-c','safe.directory=C:/Claude/SIREN_WORK/portable','cat-file','--batch'],{cwd:desktop,input:requests,maxBuffer:16*1024*1024});
let cursor=0;const gitEolOnly=[],gitRawExact=[];
for(const m of sources){const end=gitBytes.indexOf(10,cursor),header=gitBytes.subarray(cursor,end).toString(),match=/^([a-f0-9]{40}) blob (\d+)$/.exec(header);assert.ok(match,m.path+' must exist at exact commit');const size=Number(match[2]),blob=gitBytes.subarray(end+1,end+1+size),packed=asar.extractFile(archive,m.path.replaceAll('/',sep));assert.deepEqual(await identity(m.path),{bytes:m.bytes,sha256:m.sha256});assert.ok(Buffer.from(blob.toString('utf8')).equals(blob));assert.ok(Buffer.from(packed.toString('utf8')).equals(packed));assert.equal(blob.toString().replaceAll('\r\n','\n'),packed.toString().replaceAll('\r\n','\n'),m.path+' must differ at most by line endings');(hash(blob)===m.sha256?gitRawExact:gitEolOnly).push(m.path);cursor=end+size+2;}
assert.equal(cursor,gitBytes.length);
const generated=members.filter(m=>m.path.startsWith('generated/')),dependencies=members.filter(m=>m.path.startsWith('node_modules/'));
assert.equal(sources.length+generated.length+dependencies.length+1,members.length);
for(const m of members.filter(m=>!m.path.startsWith('src/')))assert.deepEqual(await identity(m.path),{bytes:m.bytes,sha256:m.sha256},m.path+' exact working bytes');
const packageBlob=execFileSync(git,['-c','safe.directory=C:/Claude/SIREN_WORK/portable','show',commit+':desktop/package.json'],{cwd:desktop});assert.ok(packageBlob.equals(asar.extractFile(archive,'package.json')));const packageJSON=JSON.parse(packageBlob);assert.equal(packageJSON.main,'src/start.mjs');assert.equal(packageJSON.type,'module');
// Execute only the finite pure catalogue/resolver IIFE in a DOM/network-free VM.
// No application window, packaged executable, shell, or full browser bundle runs.
const shell=asar.extractFile(archive,'generated/assets/shell.js').toString(),at=shell.indexOf('window.SirenHelpCatalog='),start=shell.lastIndexOf('(()=>{',at),end=shell.indexOf('})()',at)+4;
assert.ok(at>0&&start>=0&&end>at);const catalogueIIFE=shell.slice(start,end),context=vm.createContext({window:{}},{codeGeneration:{strings:false,wasm:false}});new vm.Script(catalogueIIFE,{filename:'exact-ASAR-pure-help-catalogue.js'}).runInContext(context,{timeout:1000});
const {HELP_ARTICLES,HELP_CATALOG_VERSION}=await import('../src/help/catalog.mjs');
const expectedCatalogBlob=execFileSync(git,['-c','safe.directory=C:/Claude/SIREN_WORK/portable','show',commit+':desktop/src/help/catalog.mjs'],{cwd:desktop});assert.equal((await readFile(join(desktop,'src/help/catalog.mjs'),'utf8')).replaceAll('\r\n','\n'),expectedCatalogBlob.toString().replaceAll('\r\n','\n'));
assert.deepEqual(JSON.parse(JSON.stringify(context.window.SirenHelpCatalog)),HELP_ARTICLES);assert.equal(context.window.SirenHelpCatalogVersion,HELP_CATALOG_VERSION);assert.equal(typeof context.window.SirenHelpResolver.resolve,'function');
assert.equal(asar.extractFile(archive,'generated/windows/audience.html').toString().includes('assets/shell.js'),false,'Audience must not load private manual bundle');
const catalog={version:HELP_CATALOG_VERSION,articles:HELP_ARTICLES.length,ids:HELP_ARTICLES.map(a=>a.id),exactDataSha256:hash(Buffer.from(JSON.stringify(HELP_ARTICLES))),packedPureIifeSha256:hash(Buffer.from(catalogueIIFE)),packedPureIifeBytes:Buffer.byteLength(catalogueIIFE),source:await reference('src/help/catalog.mjs'),matchesSourceCommitAndAllArticleData:true,audienceExcluded:true,scope:'Only exact pure catalogue IIFE in isolated VM; no DOM/GUI/app code execution'};
async function captureCurrent(map){const mismatches=[];for(const [p,expected]of Object.entries(map)){const actual=await identity(p);if(actual.sha256!==expected)mismatches.push({path:p,expected,actual:actual.sha256});}assert.deepEqual(mismatches,[]);return {count:Object.keys(map).length,mismatches};}
const fullPath='evidence/workspace-surface/help-full-suite-2026-10-07T14-29-17.785Z/result.json',full=await json(fullPath);assert.equal(full.author,'/root');assert.equal(full.status,'COMPLETE');assert.deepEqual(full.before,full.after);assert.deepEqual(full.changedInputs,[]);assert.equal(full.results.length,2);assert.deepEqual(full.results.map(r=>[r.name,r.code,r.counts.tests,r.counts.pass,r.counts.fail,r.counts.cancelled,r.counts.skipped]),[['identity',0,4,4,0,0,0],['units',0,1646,1646,0,0,0]]);const fullCurrent=await captureCurrent(full.before);
const developmentPath='evidence/help-diagnostics/2026-10-07T14-27-01.862Z/result.json',development=await json(developmentPath);assert.equal(development.status,'COMPLETE');assert.equal(development.cases.length,12);assert.ok(development.cases.every(c=>c.ok===true));assert.deepEqual(development.inputs,development.afterInputs);assert.equal(development.inputsUnchanged,true);const developmentCurrent=await captureCurrent(development.inputs);
const run=await json(batchPath);assert.equal(run.author,'/root');assert.equal(run.sourceCommit,commit);assert.equal(run.status,'COMPLETE');assert.deepEqual(run.before,run.after);assert.deepEqual(run.changedInputs,[]);assert.equal(run.expectedProgrammes,4);assert.equal(run.allProgrammeCount,4);assert.equal(run.remainingOnly,false);assert.deepEqual(run.excluded,[]);assert.deepEqual(run.results.map(r=>r.name),['help-diagnostics','ui-personality','workspace-appearance','diagram-edit']);
const copyRoots=new Set(),rows=[];
for(const row of run.results){assert.equal(row.code,0);const p=join(row.evidence,'result.json'),actual=await json(p);assert.deepEqual(actual,row.receipt);assert.equal(actual.status,'COMPLETE');assert.equal(actual.packageUnchanged,true);assert.equal(actual.inputsUnchanged,true);assert.deepEqual(actual.inputs,actual.afterInputs);assert.ok(actual.cases.every(c=>c.ok===true));assert.equal(actual.package.sourceCommit,commit);assert.deepEqual(actual.package.archive,receipt.appArchive);assert.deepEqual(actual.package.runtime,receipt.runtimeBinary);const harnessPath='tests/native/'+row.name+'.mjs';assert.equal((await identity(harnessPath)).sha256,row.harnessSha256);assert.equal(actual.inputs[harnessPath],row.harnessSha256);assert.equal(row.postRunCopies.length,1);assert.equal(row.postRunCopies[0].copy,actual.package.copy);const copied=[];
 for(const copy of row.postRunCopies){assert.equal(copyRoots.has(copy.copy),false);copyRoots.add(copy.copy);const actualBinaries=await verifyCopy(copy.copy);assert.deepEqual(actualBinaries.archive,copy.archive);assert.deepEqual(actualBinaries.runtime,copy.runtime);assert.deepEqual(actualBinaries.helper,copy.helper);copied.push({copy:copy.copy,...actualBinaries});}
 if(row.name==='ui-personality'){assert.equal(actual.publicFrames.length,6);for(const frame of actual.publicFrames.slice(1)){assert.deepEqual(frame.presenter,frame.audience);assert.equal(frame.acceptedEvent.theme,frame.theme);assert.deepEqual(frame.presenter.corner,frame.expectedCorner);assert.ok(frame.presenter.sequence>frame.acceptedEvent.sequenceBeforeRender);assert.equal((await identity(join(row.evidence,'public-'+frame.theme+'.png'))).sha256,frame.presenter.imageSha256);}}
 rows.push({name:row.name,code:row.code,status:actual.status,cases:actual.cases,scope:actual.scope,receipt:await reference(p),harnessSha256:row.harnessSha256,copied,inputs:Object.keys(actual.inputs).length,inputCurrent:await captureCurrent(actual.inputs)});
}
assert.equal(copyRoots.size,4);const batchCurrent=await captureCurrent(run.before);assert.equal(batchCurrent.count,668);assert.equal(rows.reduce((n,r)=>n+r.cases.length,0),36);
const buildPath='evidence/workspace-surface/help-package-build.json',build=await json(buildPath);assert.equal(build.author,'/root');assert.equal(build.previewRoot,preview);assert.deepEqual(build.receipt,receipt);
const originals=[];for(const p of ['reviews/2026-10-07-help-diagnostics-independent.json','reviews/2026-10-07-help-diagnostics-independent.md','reviews/2026-10-07-help-catalog-independent.json','reviews/2026-10-07-help-catalog-independent.md'])originals.push(await reference(p));const originalReview=await json(originals[0].path);assert.ok(originalReview.verdict.startsWith('ORIGINAL ADVERSE'));assert.equal(originalReview.findings.length,4);
const hostedOriginals=[];for(const p of ['evidence/workspace-surface/ci37629602152/desktop-packaged-evidence-original/evidence/ui-personality/2026-10-07T13-42-00.587Z/result.json','evidence/workspace-surface/ci37629602152/desktop-native-diagrams-evidence-original/evidence/ui-personality/2026-10-07T13-46-10.478Z/result.json']){const r=await json(p);assert.equal(r.status,'ADVERSE');hostedOriginals.push({...await reference(p),status:r.status});}
console.log(JSON.stringify({author:'/root/catalogue_view',reviewedUtc:new Date().toISOString(),status:'EXACT_ARCHIVE_AND_FINAL_COPIED_RECEIPTS_VERIFIED',scope:'Read-only archive/member and owner-run receipt verification, plus isolated pure catalogue VM. No independent GUI, copied executable launch, test rerun, installed replacement, CI/production/release approval.',sourceCommit:commit,preview,previewBinaries,receipt,members,memberCounts:{all:members.length,source:sources.length,gitRawExact:gitRawExact.length,gitEolOnly:gitEolOnly.length,gitEolPaths:gitEolOnly,generated:generated.length,dependencies:dependencies.length,packageJSON:1},catalog,ownerIdentity:await reference(ownerPath),build:await reference(buildPath),sourceFullSuite:{identity:await reference(fullPath),author:full.author,status:full.status,results:full.results,inputCurrent:fullCurrent},ownerDevelopment:{identity:await reference(developmentPath),status:development.status,cases:development.cases,inputCurrent:developmentCurrent},copied:{identity:await reference(batchPath),author:run.author,status:run.status,probes:rows.length,copies:copyRoots.size,postRunBinaryHashes:copyRoots.size*3,explicitNativeCases:rows.reduce((n,r)=>n+r.cases.length,0),rows,inputCurrent:batchCurrent,changedInputs:run.changedInputs},originalIndependentReviews:originals,originalIndependentVerdict:originalReview.verdict,originalFindings:originalReview.findings.map(f=>({id:f.id,priority:f.priority,title:f.title,status:f.status})),hostedOriginalAdverses:hostedOriginals,productionFlags:{releaseAdmitted:false,installedReplacement:false,independentGUI:false,hostedGreenClaim:false},limits:['Original independent Help ADVERSE is not rewritten as passed; later owner permanent regressions/full suite and native copies are separate evidence.','Readback checks exact archive/commit/working bytes and recorded outputs, not all product security or every manual repair claim.','Catalogue VM runs only pure embedded content/resolver in a DOM/network-free context; it does not execute browser/application code.','Full suite is 4 identity plus 1646 unit tests (1650 total), not 1650 unit tests.','Four copied programmes total 36 explicit cases, four separate copies and twelve post-run binary hashes; no hidden shell/packaged programmes are included.']},null,2));
