import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {buildDiagramMetadata} from '../build/diagram-metadata.mjs';
const read=p=>readFile(new URL(p,import.meta.url),'utf8');
const code=[buildDiagramMetadata(),await read('../src/ui/diagram/draft.js'),await read('../src/ui/diagram/walkthrough.js'),await read('../src/ui/diagram/annotations.js'),await read('../src/ui/windows/diagram.js')].join('\n');
async function fixture(){
 class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.style={setProperty(){}};this.dataset={};this.attrs={};this.hidden=false;this.value='';this.isConnected=true;this.clientWidth=598;this.clientHeight=398;this.offsetWidth=600;this.offsetHeight=400;this.clientLeft=1;this.clientTop=1;}
  append(...items){for(const item of items){item.parentElement=this;this.children.push(item);}}replaceChildren(...items){this.children=[];this.append(...items);}contains(n){return n===this||this.children.some(c=>c.contains(n));}addEventListener(k,fn){this.listeners[k]=fn;}removeEventListener(k){delete this.listeners[k];}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}removeAttribute(k){delete this.attrs[k];}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(c=>c!==this);this.isConnected=false;}focus(){}getBoundingClientRect(){return this.rect??{left:0,top:0,width:600,height:400};}closest(){return null;}querySelectorAll(){return [];}}
 const elements=new Map(),$=id=>{if(!elements.has(id)){const e=new Element();e.id=id;elements.set(id,e);}return elements.get(id);},callbacks={},events={},sessionCalls=[],timers=[];
 const inert=()=>({paint(){},reset(){},dispose(){},pause(){},setTargets(){},isEditing:()=>false,commit:()=>true});
 const window={addEventListener:(k,fn)=>events[k]=fn,SirenNativeViewIdentity:{set(){},clear(){}},SirenNativeDiagramStyleView:{create:o=>{callbacks.style=o;return inert();}},SirenNativeDiagramBuildView:{create:o=>{callbacks.build=o;return inert();}},SirenNativeGuidedView:{create:()=>inert()},SirenPresentationAuthoring:{create:()=>inert()},SirenNativeDiagramHistoryView:{create:o=>{callbacks.history=o;return {...inert(),keydown(){}};}},sirenDeckNavigation:{onAuthoring:fn=>callbacks.author=fn},SirenNativeDiagramSession:{create:o=>{callbacks.session=o;return {invalidate(){sessionCalls.push('invalidate');return true;},refresh(){sessionCalls.push('refresh');},renderLocal(){sessionCalls.push('render');},pause:async()=>true,resume(){},dispose(){}};}},SirenNativeDiagramTransfer:{whenPlaced:async()=>true},sirenDiagramEdit:{onReferenceChanged:fn=>{callbacks.reference=fn;return ()=>{};}},sirenDiagramRead:{},sirenWindow:{onReady:fn=>callbacks.ready=fn},sirenViewControl:{onPrepare:fn=>callbacks.prepare=fn,onResume:fn=>callbacks.resume=fn}};
 const media={matches:false,addEventListener:(k,fn)=>callbacks.media=fn},document={getElementById:$,createElement:tag=>new Element(tag),body:new Element(),head:new Element(),documentElement:new Element()};
 vm.runInNewContext(code,{window,document,getComputedStyle:()=>({opacity:'1'}),matchMedia:()=>media,crypto:webcrypto,structuredClone,TextEncoder,setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout(){},confirm:()=>true,ResizeObserver:class{observe(){}disconnect(){}}});await Promise.resolve();
 const diagram={id:'D',name:'Exact colours',source:'flowchart TD\nA-->B\nstyle A fill:#ff3366'},context={ok:true,readonly:false,diagram,version:1,sha256:'a'.repeat(64),projectRevision:1};callbacks.session.onSource(context);
 const svg=new Element('svg'),a=new Element('g'),b=new Element('g');a.rect={left:100,top:80,width:40,height:30};a.textContent='Start';b.rect={left:200,top:180,width:40,height:30};b.textContent='Next';svg.append(a,b);const render=()=>callbacks.session.onPreview({svg,targets:[{id:'A',groups:[a]},{id:'B',groups:[b]}],fontDeclared:false});render();
 const field=id=>{const walk=n=>n.id===id?n:n.children.map(walk).find(Boolean);return walk($('diagramInspectorPanel'));};return{$,field,callbacks,sessionCalls,timers,render,context,events,document};
}
test('mounted Inspector pending fields refuse Save/history/source/Refresh/presentation and auto-refresh without dropping text',async()=>{
 const f=await fixture();assert.ok(f.field('diagramMetadata_owner'),'actual annotations must be mounted');f.$('diagramInspect').listeners.click();const owner=f.field('diagramMetadata_owner');owner.value='pending owner';owner.listeners.input();const before=f.$('diagramSource').value;
 assert.equal(f.callbacks.history.commit(),false);f.$('diagramSource').value='new source';f.$('diagramSource').listeners.input();assert.equal(f.$('diagramSource').value,before);f.$('refreshDiagram').listeners.click();f.$('diagramWorkspaceMode').listeners.click();f.$('saveDiagram').listeners.click();assert.equal(owner.value,'pending owner');assert.equal(f.$('diagramInspectorPanel').hidden,false);assert.equal(f.$('diagramLayout').hidden,false);
 const timers=f.timers.length;f.callbacks.reference({diagramId:'D',version:2,projectRevision:2});assert.equal(f.timers.length,timers);assert.equal(f.document.body.dataset.diagramDirty,'false');
});
test('common prepare refuses pending Inspector while hiding content; rollback restores fields; source/error invalidation retires selection',async()=>{
 const f=await fixture();assert.ok(f.field('diagramMetadata_owner'));f.$('diagramInspect').listeners.click();const owner=f.field('diagramMetadata_owner');owner.value='pending';owner.listeners.input();const result=await f.callbacks.prepare();assert.equal(result.ok,false);assert.equal(result.code,'INSPECTOR_EDIT_PENDING');assert.equal(f.document.documentElement.style.visibility,'hidden');assert.equal(owner.value,'pending');f.callbacks.resume();assert.equal(owner.value,'pending');assert.equal(f.document.documentElement.style.visibility,'');f.render();f.field('diagramInspectorCancel').listeners.click();f.callbacks.session.onError();assert.equal(f.$('diagramInspect').disabled,true);assert.equal(f.field('diagramInspectorApply').disabled,true);f.events.pagehide();assert.equal(f.$('diagramInspectorPanel').children.length,0);
});
test('annotation module and metadata contract belong to native Diagram only; overlays preserve preview height',async()=>{
 const builder=await read('../build/diagram-window.mjs'),template=await read('../src/ui/diagram/window.html');assert.ok(builder.includes('buildDiagramMetadata'));assert.ok(builder.includes('../src/ui/diagram/annotations.js'));for(const id of ['diagramInspect','diagramFilters','diagramInspectorPanel','diagramFiltersPanel'])assert.ok(template.includes('id="'+id+'"'));assert.match(template,/\.diagram-annotations-panel\{[^}]*position:absolute/);
 for(const p of ['../build/diagram-vector.mjs','../build/presentation-render.mjs'])assert.equal((await read(p)).includes('annotations.js'),false);
});
test('new annotation controls occupy overlay chrome without adding another preview toolbar row',async()=>{
 const template=await read('../src/ui/diagram/window.html'),toolbar=template.slice(template.indexOf('<div class="diagram-toolbar">'),template.indexOf('<section id="diagramBuildPanel"'));assert.equal(toolbar.includes('id="diagramInspect"'),false);assert.equal(toolbar.includes('id="diagramFilters"'),false);assert.match(template,/\.diagram-annotation-controls\{[^}]*position:absolute/);assert.match(template,/class="diagram-annotation-controls"[^]*id="diagramInspect"/);
});
test('overlay controls and form content keep their pointer/wheel gestures instead of canvas capture or zoom',async()=>{
 const f=await fixture(),viewport=f.$('diagramViewport');let captures=0;viewport.setPointerCapture=()=>captures++;
 for(const selector of ['.diagram-annotations-panel','.diagram-annotation-controls']){const target={closest:value=>value===selector?{}:null};viewport.listeners.pointerdown({button:0,target});assert.equal(captures,0);let prevented=false;const before=f.$('diagramZoom').textContent;viewport.listeners.wheel({ctrlKey:true,deltaY:-1,target,preventDefault(){prevented=true;}});assert.equal(prevented,false);assert.equal(f.$('diagramZoom').textContent,before);}
});
