import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const code=await readFile(new URL('../src/ui/diagram/catalogue-focus.js',import.meta.url),'utf8').catch(()=> '');
function fixture(){const listeners={},events=[],window={addEventListener:(k,fn)=>listeners[k]=fn,removeEventListener:(k,fn)=>{if(listeners[k]===fn)delete listeners[k];}};let context={},enabled=true;
 const document={activeElement:null,body:{inert:false},documentElement:{style:{}},addEventListener:(k,fn)=>listeners['doc:'+k]=fn,removeEventListener:(k,fn)=>{if(listeners['doc:'+k]===fn)delete listeners['doc:'+k];}};
 const field={isConnected:true,disabled:false,selectionStart:2,selectionEnd:6,selectionDirection:'forward',focus(){events.push('focus');document.activeElement=this;},setSelectionRange(...args){events.push(args);}};document.activeElement=field;
 vm.runInNewContext(code,{window,document});assert.ok(window.SirenDiagramCatalogueFocus,'focus adapter missing');
 const views=[1,2].map(n=>({beginExternalInteraction:()=>{events.push('begin'+n);return {restore:()=>events.push('restore'+n),retire:()=>events.push('retire'+n)};}}));
 const scope=window.SirenDiagramCatalogueFocus.create({views,contextFor:()=>context,enabled:()=>enabled});return {scope,events,listeners,document,field,setContext:()=>context={},disable:()=>enabled=false};}
test('focus capture is idempotent, restores selection before releasing and preserves mounted pending fields',()=>{const f=fixture();assert.equal(f.scope.begin(),true);assert.equal(f.scope.begin(),true);assert.deepEqual(f.events,['begin1','begin2']);f.document.activeElement={};f.scope.close({restoreFocus:true});assert.equal(f.document.activeElement,f.field);assert.deepEqual(f.events.slice(2),['focus',[2,6,'forward'],'restore1','restore2']);assert.equal(f.scope.isHeld(),false);});
test('successful separate opening does not steal focus; lease retires on genuine window return',()=>{const f=fixture();f.scope.begin();f.scope.close({restoreFocus:false});assert.equal(f.scope.isHeld(),true);assert.equal(f.events.includes('focus'),false);f.listeners.focus();assert.equal(f.scope.isHeld(),false);assert.equal(f.document.activeElement,f.field);});
test('context change, pause, disposal and hidden Lock cannot restore private content',()=>{for(const mode of ['context','pause','dispose','lock']){const f=fixture();f.scope.begin();if(mode==='context')f.setContext();if(mode==='lock')f.document.body.inert=true;if(mode==='pause')f.scope.pause();if(mode==='dispose')f.scope.dispose();f.scope.close({restoreFocus:true});assert.equal(f.events.includes('focus'),false);assert.equal(f.scope.isHeld(),false);if(mode==='dispose')assert.equal(Object.keys(f.listeners).length,0);}});
test('composition prevents acquisition before focus moves and disabled contexts cannot acquire',()=>{const f=fixture();f.listeners['doc:compositionstart']();assert.equal(f.scope.begin(),false);assert.deepEqual(f.events,[]);f.listeners['doc:compositionend']();assert.equal(f.scope.begin(),true);f.scope.pause();assert.equal(f.scope.isHeld(),false);f.disable();assert.equal(f.scope.begin(),false);});

test('genuine origin focus returning before the create response restores its field when success closes the catalogue',()=>{const f=fixture();f.scope.begin();f.document.activeElement={};f.document.hasFocus=()=>true;f.listeners.focus();assert.equal(f.events.includes('focus'),false);f.scope.close({restoreFocus:false});assert.equal(f.scope.isHeld(),false);assert.equal(f.document.activeElement,f.field);assert.deepEqual(f.events.slice(2),['focus',[2,6,'forward'],'restore1','restore2']);});
