import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {createHash,webcrypto} from 'node:crypto';
const draftScript=await readFile(new URL('../src/ui/diagram/draft.js',import.meta.url),'utf8'),viewScript=await readFile(new URL('../src/ui/diagram/history-view.js',import.meta.url),'utf8').catch(e=>{if(e.code!=='ENOENT')throw e;return '';});
function fixture(){
 class Element{children=[];listeners={};attrs={};value='';disabled=false;hidden=false;append(...items){this.children.push(...items);}replaceChildren(){this.children=[];}addEventListener(type,fn){this.listeners[type]=fn;}setAttribute(k,v){this.attrs[k]=v;}closest(){return this.field?this:null;}focus(){}}
 const document={createElement:()=>new Element()},window={};vm.runInNewContext(draftScript+'\n'+viewScript,{window,document,crypto:webcrypto,structuredClone,TextEncoder});assert.equal(typeof window.SirenNativeDiagramHistoryView?.create,'function');
 const diagram={id:'a',source:'flowchart TD\nA-->B'},draft=window.SirenNativeDiagramDraft.create({context:{ok:true,readonly:false,diagram,version:1,sha256:createHash('sha256').update(JSON.stringify(diagram)).digest('hex')},bridge:{}}),host=new Element(),source=new Element(),other=new Element();other.field=true;let enabled=true,pending=false,restored=0;
 const messages=[],view=window.SirenNativeDiagramHistoryView.create({host,draftFor:()=>draft,enabled:()=>enabled,commit:()=>!pending,onRestore:()=>{restored++;},onStatus:v=>messages.push(v)});
 const field=id=>{const visit=n=>n.id===id?n:n.children.map(visit).find(Boolean);return visit(host);};return{draft,view,field,source,other,messages,pending:v=>pending=v,enabled:v=>{enabled=v;view.paint();},restored:()=>restored,event(extra={}){const e={key:'z',ctrlKey:true,target:source,prevented:false,preventDefault(){this.prevented=true;},...extra};return e;}};
}
test('mounted Undo/Redo/History use actual bounded draft and refuse pending fields without discarding source',()=>{
 const f=fixture(),d=f.draft;d.setSource('Build edit');d.setStyle({fontSize:20});f.view.paint();assert.equal(f.field('diagramUndo').disabled,false);f.pending(true);f.field('diagramUndo').listeners.click();assert.equal(d.getDiagram().fontSize,20);assert.equal(f.restored(),0);assert.ok(f.messages.at(-1).includes('fields'));f.pending(false);f.field('diagramUndo').listeners.click();assert.equal(Object.hasOwn(d.getDiagram(),'fontSize'),false);assert.equal(f.restored(),1);f.field('diagramRedo').listeners.click();assert.equal(d.getDiagram().fontSize,20);
 f.field('diagramHistoryToggle').listeners.click();assert.equal(f.field('diagramHistoryPanel').hidden,false);const steps=f.field('diagramHistorySteps');steps.value=d.getHistory().entries[0].id;steps.listeners.change();assert.equal(d.getDiagram().source,'flowchart TD\nA-->B');assert.equal(Object.hasOwn(d.getDiagram(),'fontSize'),false);assert.equal(f.field('diagramUndo').disabled,true);assert.equal(f.field('diagramRedo').disabled,false);
 f.enabled(false);const before=d.getDiagram();f.field('diagramRedo').listeners.click();assert.deepEqual(d.getDiagram(),before);f.view.dispose();f.enabled(true);f.field('diagramRedo')?.listeners.click();assert.deepEqual(d.getDiagram(),before);
});
test('semantic source Ctrl+Z/Shift+Z/Y respects focused fields, composition, modifiers and repeated keydown without browser divergence',()=>{
 const f=fixture();f.draft.setSource('first');f.draft.setSource('second');for(const extra of [{target:f.other},{isComposing:true},{altKey:true},{defaultPrevented:true}]){const e=f.event(extra);assert.equal(f.view.keydown(e,f.source),false);assert.equal(e.prevented,false);assert.equal(f.draft.getDiagram().source,'second');}
 let e=f.event();assert.equal(f.view.keydown(e,f.source),true);assert.equal(e.prevented,true);assert.equal(f.draft.getDiagram().source,'first');e=f.event({shiftKey:true});assert.equal(f.view.keydown(e,f.source),true);assert.equal(f.draft.getDiagram().source,'second');e=f.event({repeat:true});assert.equal(f.view.keydown(e,f.source),false);assert.equal(e.prevented,true);assert.equal(f.draft.getDiagram().source,'second');f.view.keydown(f.event(),f.source);assert.equal(f.view.keydown(f.event({key:'y'}),f.source),true);assert.equal(f.draft.getDiagram().source,'second');f.enabled(false);e=f.event();assert.equal(f.view.keydown(e,f.source),false);assert.equal(e.prevented,true);
});
