import test from 'node:test';import assert from 'node:assert/strict';import{sourceReadFixture}from'./fixtures/source-read-context.mjs';import{DomainRepository}from'../src/windows/domain.mjs';import{ProjectStore}from'../src/projects/store.mjs';import{SourceRepository}from'../src/sources/repository.mjs';import{WorkspaceCoordinator}from'../src/windows/coordinator.mjs';import{NativeDocsReads}from'../src/windows/docs-reads.mjs';
const module=await import('../src/windows/docs-references.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {};});
async function fixture(){const f=await sourceReadFixture({workpapers:[{id:'doc-a',links:[{kind:'document',documentId:'doc-b',blockId:''},{kind:'diagram',diagramId:'diagram-a',nodeId:''}]},{id:'doc-b',title:'Peer',blocks:[{text:'SECRET_BODY'}],agent:{instructions:'SECRET_AGENT'}}],diagrams:[{id:'diagram-a',name:'Map',source:'SECRET_SOURCE'}]});
 const domains=new DomainRepository({projects:()=>new ProjectStore(f.root,{canSave:()=>false}),sources:()=>new SourceRepository(f.root,{canWrite:()=>false}),validatePatch:()=>false}),owner=new WorkspaceCoordinator({registry:f.registry,domains,sources:()=>new SourceRepository(f.root,{canWrite:()=>false}),access:(_g,s)=>f.isUnlocked()&&s.action==='read-domain'&&s.domain==='docs'&&s.entityId==='doc-a'});
 const reads=new NativeDocsReads({registry:f.registry,owner,documentFor:()=>JSON.parse(f.selected.json).workpapers[0]});let shown=0;assert.equal(typeof module.NativeDocsReferences,'function');
 const service=new module.NativeDocsReferences({registry:f.registry,owner,reads,snapshotFor:()=>f.selected,canOpen:()=>f.isUnlocked(),show:()=>shown++});return {...f,owner,reads,service,shown:()=>shown,call:(method,payload)=>service.invoke({event:f.event(1),method,payload})};}
test('own Docs discovers bounded metadata only and opens only its exact saved reference/version',async()=>{const f=await fixture(),doc=await f.reads.invoke({event:f.event(1),method:'getDocument'}),targets=await f.call('getTargets',{});assert.equal(targets.ok,true);assert.equal(targets.items.length,2);assert.equal(targets.items.some(v=>v.id==='doc-a'),false);assert.equal(JSON.stringify(targets).includes('SECRET'),false);assert.equal(targets.version,doc.version);
 const opened=await f.call('openReference',{index:0,expectedDocumentVersion:doc.version});assert.equal(opened.ok,true);assert.equal(opened.view.role,'docs');assert.equal(opened.view.entityId,'doc-b');assert.equal(f.shown(),1);assert.deepEqual(await f.projects.readProject(f.selected.project.id),f.selected);});
test('references reject forged targets, stale versions, getters, private preparation and lock without opening peers',async()=>{const f=await fixture(),doc=await f.reads.invoke({event:f.event(1),method:'getDocument'});for(const p of [{entityId:'doc-b'},{cursor:-1},{kind:'code'},{query:'a'.repeat(161)}])assert.equal((await f.call('getTargets',p)).code,'REQUEST_REFUSED');let getter=0;assert.equal((await f.call('getTargets',Object.defineProperty({},'query',{enumerable:true,get(){getter++;return '';}}))).code,'REQUEST_REFUSED');assert.equal(getter,0);
 assert.equal((await f.call('openReference',{index:0,expectedDocumentVersion:'0'.repeat(64)})).code,'DOCUMENT_CONFLICT');assert.equal((await f.call('openReference',{index:2,expectedDocumentVersion:doc.version})).code,'LINK_TARGET_REFUSED');assert.equal((await f.service.invoke({event:f.event(1),method:'getTargets',payload:{},flushNonce:'fake'})).code,'REQUEST_REFUSED');f.owner.pause('lock');assert.equal((await f.call('getTargets',{})).code,'ACCESS_REFUSED');assert.equal(f.shown(),0);});
test('pending reference discovery cannot publish after lock or current document replacement',async()=>{const f=await fixture();let entered,release;const ready=new Promise(r=>entered=r),gate=new Promise(r=>release=r),old=f.reads.invoke.bind(f.reads);f.reads.invoke=async r=>{const v=await old(r);entered();await gate;return v;};const pending=f.call('getTargets',{});await ready;f.lock();release();const result=await pending;assert.equal(result.ok,false);assert.equal(result.items,undefined);assert.equal(f.shown(),0);});
