import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
import {createHash,webcrypto} from 'node:crypto';
import {createDocumentActivityContract} from '../src/documents/document-activity.mjs';
const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const scripts=await Promise.all(['draft.js','reader.js','../windows/docs.js'].map(path=>readFile(new URL('../src/ui/docs/'+path,import.meta.url),'utf8')));
const activityScript=await readFile(new URL('../src/ui/docs/activity.js',import.meta.url),'utf8');
async function waitFor(predicate){for(let i=0;i<100;i++){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,2));}assert.ok(predicate(),'Expected asynchronous real Save acknowledgement');}
async function fixture({readonly=false,conflict=false,realActivity=false}={}){
 const nodes=[],events={};let document,activity,options,prepare,resume,writes=0,revision=1;
 class Node{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.events={};this.hidden=false;this.className='';this.isConnected=true;this.classList={contains:name=>this.className.split(' ').includes(name)};nodes.push(this);}append(...children){for(const child of children){child.parent=this;this.children.push(child);}}insertBefore(child,before){child.parent=this;const at=this.children.indexOf(before);if(at<0)this.children.push(child);else this.children.splice(at,0,child);}setAttribute(k,v){this[k]=v;}addEventListener(k,v){this.events[k]=v;}emit(k='click'){return this.events[k]?.({target:this,preventDefault(){}});}replaceChildren(){for(const child of this.children)child.isConnected=false;this.children=[];}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);this.isConnected=false;}querySelectorAll(selector){const all=this.children.flatMap(n=>[n,...n.querySelectorAll('*')]);return all.filter(n=>selector==='*'||selector.startsWith('.')?selector==='*'||n.classList.contains(selector.slice(1)):selector===':scope > h1'?n.parent===this&&n.tagName==='H1':selector.startsWith('[data-')?(()=>{const match=selector.match(/^\[data-([\w-]+)(?:="([^"]*)")?\]$/);if(!match)return false;const key=match[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return Object.hasOwn(n.dataset,key)&&(match[2]===undefined||n.dataset[key]===match[2]);})():false);}querySelector(s){return this.querySelectorAll(s)[0]??null;}get lastElementChild(){return this.children.at(-1);}scrollIntoView(){this.scrolled=true;}focus(){document.activeElement=this;}contains(node){return node===this||this.children.some(child=>child.contains(node));}}
 const body=new Node('body'),html=new Node('html'),ids=['documentContent','documentOutline','viewStatus','viewTitle','retryDocument','documentTheme','openWorkingDocument','saveDocument','documentChangesNotice','documentChangesMessage','exportDocument','revealDocumentExport','documentContext','documentActivity','documentActivityPanel','reviewLatestDocument','replaceLatestDocument'];
 const elements=Object.fromEntries(ids.map(id=>{const n=new Node(id==='documentContent'?'article':'div');n.id=id;body.append(n);return[id,n];}));elements.documentTheme.value='light';
 document={body,documentElement:html,activeElement:null,createElement:tag=>new Node(tag),createTextNode:text=>({textContent:text,children:[],querySelectorAll:()=>[],contains:()=>false}),getElementById:id=>elements[id]??nodes.find(n=>n.id===id),getSelection:()=>null};
 let saved={id:'activity-doc',title:'Activity',blocks:Array.from({length:95},(_,i)=>({id:'id-'+i,kind:'heading',level:2,text:'Heading '+i})),comments:[{text:'Jump',resolved:false,blockId:'id-83'}],review:{state:'approved',decidedBy:'recorded claim'},revisions:[]};saved.revisions=[{blocks:structuredClone(saved.blocks),by:'Recorded revision'}];
 const read=()=>({ok:true,readonly,canEdit:true,document:structuredClone(saved),version:String(revision).repeat(64),sha256:hash(saved),projectRevision:revision});
 const window={SirenDocumentActivity:createDocumentActivityContract(),SirenNativeDocsActivity:{create(value){options=value;activity={context:null,dirty:false,invalidations:0,paused:false,setContext(value){this.context=value;this.dirty=value.dirty;},updateState(value){this.dirty=value.dirty;},invalidate(){this.invalidations++;},pause(){this.paused=true;},resume(){this.paused=false;},dispose(){this.context=null;}};return activity;}},SirenNativeDocsExportView:{create:()=>({update(){},reset(){},pause:async()=>{},resume(){},dispose(){}})},SirenNativeViewIdentity:{clear(){},set(){}},SirenDocsContext:{open(){},close(){}},SirenNativeDocsRichText:{editable:()=>false},SirenStructuredDocs:{isEditableBlock:()=>false,names:{}},sirenDocsRead:{getDocument:async()=>read()},sirenDocsEdit:{onReferenceChanged:()=>()=>{},applyDocument:async request=>{writes++;if(conflict)return{ok:false,code:'DOCUMENT_CONFLICT'};saved={...saved,...structuredClone(request.payload)};revision++;return{ok:true,domain:'docs',entityId:saved.id,operationId:request.operationId,version:read().version,sha256:hash(saved),projectRevision:revision,durability:'committed'};},flushDocument:async request=>({ok:true,domain:'docs',entityId:saved.id,version:request.expectedVersion,sha256:hash(saved),projectRevision:revision,durability:'committed'})},sirenViewControl:{onPrepare(fn){prepare=fn;},onResume(fn){resume=fn;}},addEventListener:(name,fn)=>events[name]=fn};
 const context={window,document,structuredClone,crypto:webcrypto,TextEncoder,matchMedia:()=>({matches:false,addEventListener(){},removeEventListener(){}}),confirm:()=>true,setTimeout,clearTimeout};if(realActivity)runInNewContext(activityScript,context);for(const code of scripts)runInNewContext(code,context);await window.sirenNativeDocsView.connect();
 return {nodes,elements,window,document,readContext:read,get activity(){return activity;},get options(){return options;},get saved(){return saved;},get writes(){return writes;},prepare:()=>prepare(),resume:()=>resume(),edit(){const input=nodes.find(n=>n.tagName==='TEXTAREA'&&n.dataset.blockId==='id-0');assert.ok(input);input.value='Working exact Ș😀';input.emit('input');return input;}};
}
test('Activity compares an explicit saved or working target and reveals lazy editor blocks without repaint or save',async()=>{
 const f=await fixture();assert.ok(f.activity,'Docs Activity integration missing');const original=JSON.stringify(f.saved),input=f.edit();input.focus();const saved=await f.options.onCompare({position:0,against:'saved'}),working=await f.options.onCompare({position:0,against:'working'});assert.equal(saved.identical,true);assert.equal(working.identical,false);assert.equal(working.rows[0].change,'changed');assert.equal(f.activity.dirty,true);
 const result=await f.options.onJump('id-83');assert.equal(result.ok,true);assert.equal(f.nodes.find(n=>n.tagName==='TEXTAREA'&&n.dataset.blockId==='id-0'),input);assert.equal(input.value,'Working exact Ș😀');assert.equal(f.writes,0);assert.equal(JSON.stringify(f.saved),original);assert.equal(f.document.activeElement.dataset.blockId,'id-83');assert.equal((await f.options.onJump('missing')).code,'BLOCK_MISSING');
});
test('verified Save replaces Activity saved context once and keeps archived records exact',async()=>{
 const f=await fixture();assert.ok(f.activity,'Docs Activity integration missing');const originalRecords=JSON.stringify([f.saved.comments,f.saved.revisions,f.saved.review]);f.edit();f.elements.saveDocument.emit();await waitFor(()=>f.document.body.dataset.documentDirty==='false');assert.equal(f.writes,1);assert.equal(f.activity.context.version,'2'.repeat(64));assert.equal(f.activity.dirty,false);assert.equal(f.activity.context.document.blocks[0].text,'Working exact Ș😀');assert.equal((await f.options.onCompare({position:0,against:'saved'})).identical,false);assert.equal(JSON.stringify([f.saved.comments,f.saved.revisions,f.saved.review]),originalRecords);
});
test('save conflict retains original saved Activity context and exact unsaved editor content',async()=>{
 const f=await fixture({conflict:true});assert.ok(f.activity,'Docs Activity integration missing');const input=f.edit();f.elements.saveDocument.emit();await waitFor(()=>f.document.body.dataset.documentSaveError==='DOCUMENT_CONFLICT');assert.equal(f.activity.context.version,'1'.repeat(64));assert.equal(f.activity.dirty,true);assert.equal(input.value,'Working exact Ș😀');assert.equal((await f.options.onCompare({position:0,against:'saved'})).identical,true);assert.equal((await f.options.onCompare({position:0,against:'working'})).identical,false);
});
test('Lock preparation pauses Activity and verified flush updates its context on resume',async()=>{
 const f=await fixture();assert.ok(f.activity,'Docs Activity integration missing');f.edit();assert.equal((await f.prepare()).ok,true);assert.equal(f.activity.paused,true);assert.equal((await f.options.onJump('id-83')).ok,false);assert.equal((await f.options.onCompare({position:0,against:'saved'})).ok,false);f.resume();assert.equal(f.activity.paused,false);assert.equal(f.activity.context.version,'2'.repeat(64));assert.equal(f.activity.dirty,false);assert.equal(f.saved.blocks[0].text,'Working exact Ș😀');
});
test('readonly Docs exposes Activity and exact reader jump without granting working comparison or writes',async()=>{
 const f=await fixture({readonly:true});assert.ok(f.activity,'Docs Activity integration missing');assert.equal(f.activity.context.readonly,true);assert.equal((await f.options.onJump('id-83')).ok,true);assert.equal((await f.options.onCompare({position:0,against:'working'})).ok,false);assert.equal((await f.options.onCompare({position:0,against:'saved'})).identical,true);assert.equal(f.writes,0);
});
test('actual Activity regains saved admission after pending Refresh is retired by preparation and rollback',async()=>{
 const f=await fixture({readonly:true,realActivity:true});assert.equal(f.elements.documentActivity.disabled,false);let release;f.window.sirenDocsRead.getDocument=()=>new Promise(resolve=>release=resolve);const reading=f.window.sirenNativeDocsView.connect();assert.equal(f.elements.documentActivity.disabled,true);const preparing=f.prepare();release(f.readContext());assert.equal(await reading,false);assert.equal((await preparing).ok,true);f.resume();assert.equal(f.document.body.inert,false);assert.equal(f.document.body.dataset.documentReady,'true');assert.equal(f.elements.documentActivity.disabled,false,'Activity must recover unchanged saved context after rollback');f.elements.documentActivity.emit();assert.equal(f.elements.documentActivityPanel.hidden,false);assert.equal(f.writes,0);
});
