import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';import {runInNewContext} from 'node:vm';
const m=await import('../src/documents/images.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {};});
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aC1kAAAAASUVORK5CYII=';
test('raster inspection accepts a bounded PNG and rejects remote, executable, spoofed, corrupt and oversized inputs',()=>{assert.equal(typeof m.inspectDocumentImage,'function');assert.equal(m.inspectDocumentImage(png).ok,true);for(const value of ['https://outside.invalid/a.png','data:image/svg+xml;base64,PHN2Zz4=',png.replace('image/png','image/jpeg'),png.slice(0,-8)+'AAAAAAAA','data:image/png;base64,'+'A'.repeat(3*1024*1024)])assert.equal(m.inspectDocumentImage(value).ok,false);});
test('image edits preserve opaque imported fields and refuse invalid changes atomically',()=>{assert.equal(typeof m.editDocumentImage,'function');const original={id:'image-a',kind:'image',dataUri:png,caption:'Old',fileName:'a.png',role:'purpose',future:{exact:'PRIVATE'}};const edited=m.editDocumentImage(original,{caption:'Ș 😀'});assert.deepEqual(edited,{...original,caption:'Ș 😀'});assert.equal(original.caption,'Old');for(const changes of [{dataUri:'https://bad.invalid'},{caption:'a'.repeat(1001)},{future:{}},{fileName:'x'.repeat(161)}])assert.throws(()=>m.editDocumentImage(original,changes));});

test('JPEG SOF dimensions reject decompression-sized rasters before assigning an image source',()=>{const jpeg=(w,h)=>'data:image/jpeg;base64,'+Buffer.from([255,216,255,192,0,11,8,h>>8,h&255,w>>8,w&255,1,1,17,0,255,217]).toString('base64');assert.equal(m.inspectDocumentImage(jpeg(1,1)).ok,true);assert.equal(m.inspectDocumentImage(jpeg(30000,30000)).ok,false);assert.equal(m.inspectDocumentImage('data:image/jpeg;base64,/9j/2Q==').ok,false);});
test('a late decoded image cannot stage after Lock or overwrite a newer draft edit',async()=>{
 const source=await readFile(new URL('../src/ui/docs/images.js',import.meta.url),'utf8');
 for(const race of ['lock','edited']){let finish,entered;const reached=new Promise(r=>entered=r),nodes=[],state={paused:false},content={title:'Image',blocks:[{id:'image-a',kind:'image',dataUri:png,caption:'Original',fileName:'a.png'}]};let writes=0;
  const node=()=>({isConnected:true,dataset:{},events:{},append(){},setAttribute(){},removeAttribute(){},addEventListener(name,fn){this.events[name]=fn;}}),window={SirenDocumentImages:m},document={createElement(){const n=node();nodes.push(n);return n;}};
  runInNewContext(source,{window,document,TextEncoder,Uint8Array,Blob,btoa,structuredClone,createImageBitmap:()=>new Promise(r=>{finish=r;entered();})});
  window.SirenNativeDocsImages.renderEditor({parent:node(),draft:{getContent:()=>structuredClone(content),getStatus:()=>state,setContent(){writes++;}},index:0,canEdit:()=>!state.paused,onRejected(){},onRemove(){}});
  const input=nodes.find(n=>n.type==='file');input.files=[{size:Buffer.from(png.split(',')[1],'base64').length,name:'new.png',arrayBuffer:async()=>Uint8Array.from(Buffer.from(png.split(',')[1],'base64')).buffer}];const pending=input.events.change();await reached;if(race==='lock')state.paused=true;else content.blocks[0].caption='Newer draft';finish({width:1,height:1,close(){}});await pending;assert.equal(writes,0,race);assert.equal(content.blocks[0].fileName,'a.png');
 }
});
