import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {parse} from 'parse5';
import {mkdtemp} from './fixtures/temporary.mjs';import {buildWorkspaceEntrypoint} from '../build/workspace.mjs';
const resources=await import('./native/home-entry-resources.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return{};});
test('Home fixture admits exactly its five genuine local resources, including catalogue assets',()=>{
 assert.deepEqual(resources.expectedHomeResources,['siren://app/home.html','siren://app/assets/shell.js','siren://app/assets/shell.css','siren://app/assets/home-workspace.js','siren://app/assets/diagram-catalogue.css']);assert.equal(Object.isFrozen(resources.expectedHomeResources),true);assert.equal(resources.hasOnlyHomeResources([...resources.expectedHomeResources,'siren://app/home.html']),true);
});
test('Home fixture continues to reject foreign, diagram, source and unexpected local requests',()=>{
 assert.equal(typeof resources.hasOnlyHomeResources,'function');for(const url of ['https://example.invalid/tracker','siren://app/app.html','siren://app/windows/diagram.html','siren://app/assets/unknown.js','siren://app/assets/home-workspace.js?forged=1','siren://app/source/private'])assert.equal(resources.hasOnlyHomeResources(['siren://app/home.html',url]),false);for(const value of [[],null,{},['siren://app/home.html',null]])assert.equal(resources.hasOnlyHomeResources(value),false);
});
test('actual fresh Home builder references every whitelisted asset with integrity, and no other external asset',async()=>{
 assert.equal(typeof resources.hasOnlyHomeResources,'function');const dir=await mkdtemp(join(tmpdir(),'siren-home-resources-'));await mkdir(dir,{recursive:true});await buildWorkspaceEntrypoint({outputDir:dir});const html=await readFile(join(dir,'home.html'),'utf8'),nodes=[];const visit=node=>{nodes.push(node);for(const child of node.childNodes||[])visit(child);};visit(parse(html));const tags=nodes.filter(n=>['script','link'].includes(n.tagName)).map(n=>Object.fromEntries(n.attrs.map(a=>[a.name,a.value]))).filter(a=>a.src||a.href),urls=tags.map(a=>a.src||a.href);assert.deepEqual(new Set(urls),new Set(resources.expectedHomeResources.filter(u=>!u.endsWith('/home.html'))));assert.equal(resources.hasOnlyHomeResources(['siren://app/home.html',...urls]),true);for(const tag of tags){const path=(tag.src||tag.href).slice('siren://app/'.length);assert.equal(tag.integrity,'sha384-'+createHash('sha384').update(await readFile(join(dir,path))).digest('base64'));}
});
