import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';
const api=await import('../scripts/native-verification.mjs').catch(error=>{if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;return {};});
const required=["shell","protected-storage","account-transition","code-windows","desktop-ui","code-recovery","recovery-zoom","code-diagram-interaction","guided-intro","dev-first-run","access-screen","local-pin","headless-import","source-owner","source-read","source-analysis","source-diff","source-map","source-edit","source-link","source-link-create","docs-sources","source-sync","docs-edit","diagram-preview","diagram-edit","diagram-guided","diagram-style","diagram-build","diagram-vector","diagram-export","view-control-rollback","large-source-docs","code-view-flush","domain-workspaces","readonly-roster","home-entry","home-navigation","home-recovery","home-library","home-library-search","home-documents","docs-structured","home-source-projects","presentation-render","presentation-style","presentation-cards","presentation-windows","window-focus","toast-transition"];
test('all original native checks are assigned once to finite independent CI groups with an all-group qualification gate',async()=>{
 const additions=['window-close-keys','window-role-privacy'];
 assert.equal(typeof api.nativeGroups,'object','Native group definitions must exist');assert.deepEqual(Object.keys(api.nativeGroups),['desktop','sources','diagrams']);const actual=Object.values(api.nativeGroups).flat();assert.deepEqual([...actual].sort(),[...required,...additions].sort());assert.equal(new Set(actual).size,required.length+additions.length);for(const names of Object.values(api.nativeGroups)){assert.ok(names.length>0&&names.length<=20);for(const name of names)await access(new URL('../tests/native/'+name+'.mjs',import.meta.url));}
 const workflow=await readFile(new URL('../../.github/workflows/desktop-verify.yml',import.meta.url),'utf8');assert.match(workflow,/fail-fast: false/);assert.match(workflow,/group: \[desktop, sources, diagrams\]/);assert.match(workflow,/run: node scripts\/native-verification.mjs --group \$\{\{ matrix.group \}\}/);assert.match(workflow,/needs: \[windows, native_windows, packaged_windows\]/);assert.match(workflow,/SIREN_NATIVE_RESULT: \$\{\{ needs.native_windows.result \}\}/);assert.match(workflow,/\$env:SIREN_NATIVE_RESULT -ne 'success'/);assert.match(workflow,/name: desktop-native-\$\{\{ matrix.group \}\}-evidence/);assert.equal((workflow.match(/timeout-minutes: 25/g)||[]).length,3);
 assert.match(workflow,/node tests\/native\/window-close-keys\.mjs --package \$preview\.previewRoot/);
 assert.match(workflow,/if \(\$LASTEXITCODE -ne 0\) \{ throw "Packaged native close commands failed" \}/);
 assert.equal((workflow.match(/desktop\/evidence\/window-close-keys\/\*\/result\.json/g)||[]).length,3);
 assert.equal((workflow.match(/desktop\/evidence\/window-close-keys\/\*\/electron\.log/g)||[]).length,3);
});
test('a native failure or spawn refusal cannot become group success, and later checks still execute exactly once',async()=>{
 assert.equal(typeof api.runNativeGroup,'function','Native group runner must exist');let calls=[];await assert.rejects(api.runNativeGroup('forged',{run:async name=>{calls.push(name);return {code:0,signal:null};}}));assert.deepEqual(calls,[]);const names=api.nativeGroups.sources;const result=await api.runNativeGroup('sources',{run:async name=>{calls.push(name);if(name===names[0])return {code:1,signal:null};if(name===names[1])throw Object.assign(Error('PLANTED_PRIVATE_BODY'),{code:'EPERM'});return {code:0,signal:null};}});assert.deepEqual(calls,names);assert.equal(result.ok,false);assert.equal(result.results.length,names.length);assert.deepEqual(result.failed,names.slice(0,2));assert.equal(JSON.stringify(result).includes('PLANTED_PRIVATE_BODY'),false);
});
