// Build derivation tests only. Never compiles/imports/executes a native addon.
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {deriveHostRosterCandidate,HOST_ROSTER_BASE} from '../build/terminal-host-roster-candidate-derive.mjs';
const old=new URL('../native/terminal-creator-host-async/',import.meta.url),candidate=new URL('../native/terminal-host-roster-candidate/',import.meta.url),names={ownership:'ownership.cc',peer:'peer-endpoints.inc',binding:'binding.gyp'};
const input=Object.fromEntries(await Promise.all(Object.entries(names).map(async([k,f])=>[k,await readFile(new URL(f,old))]))),hash=b=>createHash('sha256').update(b).digest('hex');
test('exact known base yields deterministic detached source buffers without input mutation',()=>{const before=Object.fromEntries(Object.entries(input).map(([k,b])=>[k,hash(b)])),a=deriveHostRosterCandidate(input),b=deriveHostRosterCandidate(input);assert(Object.isFrozen(a));assert.deepEqual(a,b);for(const k of Object.keys(names)){assert(Buffer.isBuffer(a[k]));assert.notEqual(a[k],input[k]);assert.notEqual(a[k],b[k]);assert.equal(hash(input[k]),before[k]);assert.equal(before[k],HOST_ROSTER_BASE[k]);}a.ownership.fill(0);assert.notDeepEqual(a.ownership,b.ownership);assert.equal(hash(input.ownership),before.ownership);});
for(const k of Object.keys(names))test(`unknown ${k} source refuses before producing candidate`,()=>{assert.throws(()=>deriveHostRosterCandidate({...input,[k]:Buffer.concat([input[k],Buffer.from('\n')])}),/HOST_ROSTER_BASE_DRIFT/);});
for(const v of [null,undefined,0,'source',[],Promise.resolve(1)])test(`invalid build input ${String(v)}`,()=>assert.throws(()=>deriveHostRosterCandidate(v),/HOST_ROSTER_INPUT_REFUSED/));
test('exact build DATA shape and buffers only',()=>{assert.throws(()=>deriveHostRosterCandidate({...input,extra:true}),/HOST_ROSTER_INPUT_REFUSED/);assert.throws(()=>deriveHostRosterCandidate(input,undefined),/HOST_ROSTER_INPUT_REFUSED/);for(const k of Object.keys(names)){const missing={...input};delete missing[k];assert.throws(()=>deriveHostRosterCandidate(missing),/HOST_ROSTER_INPUT_REFUSED/);for(const v of [input[k].toString(),new Uint8Array(input[k]),null])assert.throws(()=>deriveHostRosterCandidate({...input,[k]:v}),/HOST_ROSTER_INPUT_REFUSED/);}assert.deepEqual(deriveHostRosterCandidate(Object.assign(Object.create(null),input)),deriveHostRosterCandidate(input));});
test('build input hooks and Proxy are rejected without running traps',()=>{let calls=0;const value={...input};Object.defineProperty(value,'ownership',{enumerable:true,get(){calls++;throw Error();}});assert.throws(()=>deriveHostRosterCandidate(value),/HOST_ROSTER_INPUT_REFUSED/);for(const revoked of [false,true]){const p=Proxy.revocable(input,{get(){calls++;throw Error();},ownKeys(){calls++;throw Error();},getPrototypeOf(){calls++;throw Error();}});if(revoked)p.revoke();assert.throws(()=>deriveHostRosterCandidate(p.proxy),/HOST_ROSTER_INPUT_REFUSED/);}const proxyBuffer=new Proxy(input.ownership,{get(){calls++;throw Error();}});assert.throws(()=>deriveHostRosterCandidate({...input,ownership:proxyBuffer}),/HOST_ROSTER_INPUT_REFUSED/);assert.equal(calls,0);});
test('shadowed Buffer decoding hooks are never called for genuine pinned bytes',()=>{let calls=0;const other=Object.fromEntries(Object.entries(input).map(([k,b])=>{const v=Buffer.from(b);Object.defineProperty(v,'toString',{get(){calls++;throw Error('UNTRUSTED_DECODE_HOOK');}});return [k,v];}));assert.deepEqual(deriveHostRosterCandidate(other),deriveHostRosterCandidate(input));assert.equal(calls,0);});
test('typed source bytes ignore shadowed length and UTF8/primitive hooks',()=>{for(const key of ['utf8Slice','length','byteLength','buffer','valueOf',Symbol.toPrimitive,Symbol.iterator]){let calls=0;const other=Object.fromEntries(Object.entries(input).map(([k,b])=>{const v=Buffer.from(b);Object.defineProperty(v,key,{get(){calls++;throw Error('SOURCE_BUFFER_HOOK');}});return [k,v];}));assert.deepEqual(deriveHostRosterCandidate(other),deriveHostRosterCandidate(input));assert.equal(calls,0);}assert.throws(()=>deriveHostRosterCandidate({...input,ownership:Object.create(Buffer.prototype)}),/HOST_ROSTER_INPUT_REFUSED/);});
for(const [k,name]of Object.entries(names))test(`generated WIP ${name} is exactly the reproducible candidate`,async()=>assert.deepEqual(await readFile(new URL(name,candidate)),deriveHostRosterCandidate(input)[k]));
test('new binding target and all opaque tag families are isolated from actual original',()=>{const output=deriveHostRosterCandidate(input),binding=JSON.parse(output.binding);assert.equal(binding.targets.length,1);assert.equal(binding.targets[0].target_name,'siren_terminal_host_roster_candidate');const tags=s=>new Map([...s.matchAll(/const napi_type_tag (\w+)=\{([^}]+)\}/g)].map(m=>[m[1],m[2]])),prior=tags(input.ownership+'\n'+input.peer),next=tags(output.ownership+'\n'+output.peer);assert.equal(prior.size,5);assert.equal(next.size,5);assert.equal(new Set(next.values()).size,5);for(const [key,value]of prior)assert.notEqual(next.get(key),value);});
