import test from 'node:test';
import assert from 'node:assert/strict';
const api=await import('./native/terminal-normal-probe-core.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {};});
function fixture(){assert.equal(typeof api.NormalShellProbe,'function');let now=1;const writes=[],output=[];const probe=new api.NormalShellProbe({writeInput:s=>writes.push(s),appendOutput:s=>output.push(s),clock:()=>now++});return {probe,writes,output};}
test('fixed command markers cannot be mistaken for command echo',()=>{const {probe,writes}=fixture();assert.equal(probe.requestCommand(0).ok,false);assert.equal(writes.length,0);assert.equal(probe.applyGate({generation:1,open:true}).ok,true);assert.equal(probe.requestCommand(1).ok,true);assert.equal(writes.length,1);assert.ok(!writes[0].includes(api.NORMAL_BEGIN));assert.ok(!writes[0].includes(api.NORMAL_DONE));assert.match(writes[0],/Start-Sleep -Milliseconds 1200/);});
test('Lock keeps collecting output but prohibits further input',()=>{const {probe,writes,output}=fixture();probe.applyGate({generation:1,open:true});probe.requestCommand(1);probe.ingest(api.NORMAL_BEGIN.slice(0,10));probe.ingest(api.NORMAL_BEGIN.slice(10)+'\r\n');probe.applyGate({generation:2,open:false});assert.equal(probe.requestCommand(2).ok,false);probe.ingest(api.NORMAL_DONE+'\r\n');const s=probe.snapshot();assert.equal(writes.length,1);assert.equal(s.refusedInput,1);assert.ok(s.beginMs<s.lockMs&&s.lockMs<s.doneMs);assert.ok(output.join('').includes(api.NORMAL_DONE));});
test('stale gate/repeated open never runs the command twice',()=>{const {probe,writes}=fixture();probe.applyGate({generation:1,open:true});probe.requestCommand(1);assert.equal(probe.requestCommand(1).ok,false);probe.applyGate({generation:2,open:false});assert.equal(probe.applyGate({generation:1,open:true}).ok,false);assert.equal(probe.requestCommand(1).ok,false);probe.applyGate({generation:3,open:true});assert.equal(probe.requestCommand(3).ok,false);assert.equal(writes.length,1);});
test('output Unicode validation and bounded marker parser reject oversized or ill-formed chunks',()=>{const {probe,output}=fixture();assert.throws(()=>probe.ingest('\ud800'));assert.throws(()=>probe.ingest('x'.repeat(32769)));assert.equal(output.length,0);for(let n=0;n<40;n++)probe.ingest('x'.repeat(32768));assert.ok(probe.snapshot().parserCharacters<=1024);});
test('ambiguous throwing write is never retried',()=>{assert.equal(typeof api.NormalShellProbe,'function');let calls=0;const p=new api.NormalShellProbe({writeInput:()=>{calls++;throw Error('uncertain');},appendOutput:()=>{}});p.applyGate({generation:1,open:true});assert.equal(p.requestCommand(1).ok,false);p.applyGate({generation:2,open:true});assert.equal(p.requestCommand(2).ok,false);assert.equal(calls,1);assert.equal(p.snapshot().inputWrites,1);assert.equal(p.snapshot().writeKnown,false);});
