import {Worker} from 'node:worker_threads';
import test from 'node:test';import assert from 'node:assert/strict';import {win32 as path} from 'node:path';
import {dispatchTerminalRequest} from '../src/terminal/contracts.mjs';
async function implementation(){try{return await import('../src/terminal/profiles.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Shell profile catalogue implementation is missing');throw e;}}
const executable='C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe';
function file(p){const parts=path.dirname(p).slice(3).split('\\');return {canonicalPath:p,identity:'executable-id',file:true,reparse:false,ancestors:['C:\\',...parts.map((_,i)=>path.join('C:\\',...parts.slice(0,i+1)))].map(q=>({path:q,identity:'dir:'+q,directory:true,reparse:false}))};}
async function fixture(extra={}){const {createShellProfileCatalogue}=await implementation();assert.equal(typeof createShellProfileCatalogue,'function');const state={allowed:true,generation:0,calls:[],hook:async()=>{},file:file(executable),env:{SystemRoot:'C:\\Windows',PATH:'C:\\Windows\\System32',TEMP:'C:\\Temp',USERNAME:'human'}};const call=async(type,value)=>{state.calls.push(type);await state.hook(type);return value();};const catalogue=createShellProfileCatalogue({authorize:()=>state.allowed,captureAdmission:()=>{const n=state.generation;return {isCurrent:()=>state.generation===n};},getSystemDirectory:()=>call('system',()=> 'C:\\Windows\\System32'),inspectExecutable:p=>call('inspect',()=>{assert.equal(p,executable);return state.file;}),readEnvironment:()=>call('env',()=>state.env),...extra});return {catalogue,state};}
const rejects=(fn,code)=>assert.rejects(fn,e=>e?.code===code);

test('profile defaults do not discover files or issue a usable executable',async()=>{const {listShellProfiles,resolveShellProfile,createShellProfileCatalogue}=await implementation();await rejects(()=>listShellProfiles(),'SENDER_REFUSED');await rejects(()=>resolveShellProfile('powershell'),'SENDER_REFUSED');let calls=0;const a=createShellProfileCatalogue({getSystemDirectory:()=>{calls++;return 'C:\\Windows\\System32';}});await rejects(()=>a.listShellProfiles(),'SENDER_REFUSED');assert.equal(calls,0);});
test('profile list is immutable and exposes no native executable argv or environment',async()=>{const {catalogue:a}=await fixture();const result=await a.listShellProfiles();assert.deepEqual(result,[{profileId:'powershell',label:'Windows PowerShell',available:true}]);assert.equal(Object.isFrozen(result),true);assert.equal(Object.isFrozen(result[0]),true);});
test('profile resolver returns absolute fixed interactive PowerShell envelope without commands',async()=>{const {catalogue:a}=await fixture();const result=await a.resolveShellProfile('powershell');assert.deepEqual(Object.keys(result).sort(),['args','env','executable']);assert.equal(result.executable,executable);assert.deepEqual(result.args,['-NoLogo','-NoProfile']);assert.equal(result.env.PATH,'C:\\Windows\\System32');assert.equal(result.env.SystemRoot,'C:\\Windows');assert.equal(Object.isFrozen(result),true);assert.equal(Object.isFrozen(result.args),true);assert.equal(Object.isFrozen(result.env),true);});
test('profile missing native OS root or executable remains unavailable without PATH fallback',async()=>{for(const getSystemDirectory of [async()=>null,async()=>'',async()=> 'relative',async()=>{throw Error('private provider details');}]){const {catalogue:a,state}=await fixture({getSystemDirectory});assert.deepEqual(await a.listShellProfiles(),[{profileId:'powershell',label:'Windows PowerShell',available:false}]);await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');assert.equal(state.calls.includes('inspect'),false);}const {catalogue:a}=await fixture({inspectExecutable:async()=>null});assert.equal((await a.listShellProfiles())[0].available,false);await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');});
test('profile unknown optional ids and caller startup arguments cannot select a shell',async()=>{const {catalogue:a,state}=await fixture();for(const id of ['cmd','pwsh','C:\\evil.exe','powershell -Command x',null,{},'toString'])await rejects(()=>a.resolveShellProfile(id),'PROFILE_UNAVAILABLE');assert.equal(state.calls.length,0);await rejects(()=>a.resolveShellProfile('powershell',{args:['-Command','x']}),'REQUEST_REFUSED');await rejects(()=>a.listShellProfiles({env:{NODE_OPTIONS:'x'}}),'REQUEST_REFUSED');});
test('profile revalidates pinned executable and directory identities after discovery',async()=>{for(const mutation of [s=>{s.file.identity='new-file';},s=>{s.file.ancestors[1].identity='new-dir';},s=>{s.file.canonicalPath='D:\\powershell.exe';},s=>{s.file.file=false;},s=>{s.file.reparse=true;},s=>{s.file.ancestors[1].reparse=true;}]){const {catalogue:a,state}=await fixture();assert.equal((await a.listShellProfiles())[0].available,true);mutation(state);await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');}});
test('profile refuses native file evidence with missing ancestry identity or accessor fields',async()=>{let reads=0;const bad=file(executable);Object.defineProperty(bad,'identity',{enumerable:true,get(){reads++;return 'identity';}});for(const inspected of [bad,{...file(executable),identity:''},{...file(executable),ancestors:[]},{...file(executable),ancestors:file(executable).ancestors.slice(1)}]){const {catalogue:a}=await fixture({inspectExecutable:async()=>inspected});await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');}assert.equal(reads,0);});
test('profile environment strips injection keys without mutating native OS snapshot',async()=>{const {catalogue:a,state}=await fixture({privateEnvironmentKeys:['APP_ACCOUNT_TOKEN']});Object.assign(state.env,{nOdE_oPtIoNs:'--require evil',NODE_PATH:'evil',electron_run_as_node:'1',ELECTRON_NO_ASAR:'1',Electron_Extra_Launch_Args:'evil',VSCODE_INJECTION:'evil',CHROME_LOG_FILE:'private',PSModulePath:'application-injected-modules',SIREN_PIN:'1494',APP_ACCOUNT_TOKEN:'secret','ProgramFiles(x86)':'C:\\Program Files (x86)'});const original={...state.env};const result=await a.resolveShellProfile('powershell');assert.deepEqual({...result.env},{SystemRoot:'C:\\Windows',PATH:'C:\\Windows\\System32',TEMP:'C:\\Temp',USERNAME:'human','ProgramFiles(x86)':'C:\\Program Files (x86)'});assert.deepEqual(state.env,original);});
test('profile refuses duplicate case-folded environment variables and non-data snapshots',async()=>{let reads=0;const accessor={};Object.defineProperty(accessor,'PATH',{enumerable:true,get(){reads++;return 'evil';}});for(const env of [{PATH:'a',Path:'b'},accessor,Object.assign(Object.create({PATH:'inherited'}),{TEMP:'x'}),{PATH:1},{PATH:'bad\0value'},{PATH:'bad\ud800'},{PATH:'x'.repeat(32769)}]){const {catalogue:a,state}=await fixture();state.env=env;await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');}assert.equal(reads,0);});
test('profile total environment budget refuses oversized aggregate without silent truncation',async()=>{const {catalogue:a,state}=await fixture();state.env=Object.fromEntries(Array.from({length:100},(_,i)=>['VAR_'+i,'x'.repeat(3000)]));await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');});
test('profile scope is checked after OS-directory and executable awaits on list',async()=>{for(const boundary of ['system','inspect']){const {catalogue:a,state}=await fixture();state.hook=async type=>{if(type===boundary)state.generation++;};await rejects(()=>a.listShellProfiles(),'SENDER_REFUSED');assert.equal(state.calls.at(-1),boundary);}});
test('profile scope is checked after each resolve await including environment snapshot',async()=>{for(const boundary of ['system','inspect','env']){const {catalogue:a,state}=await fixture();state.hook=async type=>{if(type===boundary)state.generation++;};await rejects(()=>a.resolveShellProfile('powershell'),'SENDER_REFUSED');assert.equal(state.calls.at(-1),boundary);}});
test('profile revoke never revives an old asynchronous discovery and dispose is permanent',async()=>{let release;const {catalogue:a,state}=await fixture();state.hook=type=>type==='system'?new Promise(r=>release=r):Promise.resolve();const old=a.listShellProfiles();a.revoke();state.hook=async()=>{};assert.equal((await a.listShellProfiles())[0].available,true);release();await rejects(()=>old,'SENDER_REFUSED');a.dispose();await rejects(()=>a.resolveShellProfile('powershell'),'SENDER_REFUSED');});
test('profile concurrent operations are bounded without permanently consuming capacity on failure',async()=>{let release;const {catalogue:a,state}=await fixture({maxPending:1});state.hook=type=>type==='system'?new Promise(r=>release=r):Promise.resolve();const pending=a.listShellProfiles();await rejects(()=>a.listShellProfiles(),'CAPACITY_EXCEEDED');release();await pending;state.hook=async()=>{};assert.equal((await a.listShellProfiles())[0].available,true);});
test('profile asynchronous truthy or throwing authorization cannot discover a shell',async()=>{for(const authorize of [()=>1,()=>Promise.resolve(true),()=>{throw Error('lost');}]){const {catalogue:a,state}=await fixture({authorize});await rejects(()=>a.listShellProfiles(),'SENDER_REFUSED');assert.deepEqual(state.calls,[]);}});
test('usable native profile envelope never becomes a renderer supplied create authority',async()=>{let actualHostDispatch=0;const {catalogue:a}=await fixture();const envelope=await a.resolveShellProfile('powershell');for(const extra of [{executable:envelope.executable},{args:envelope.args},{env:envelope.env},{command:'hidden run'},{projectId:'forged'}]){const result=await dispatchTerminalRequest({method:'terminalCreate',payload:{operationId:'op1',epoch:7,cwdId:'cwd1',profileId:'powershell',cols:80,rows:24,...extra},dispatch:()=>{actualHostDispatch++;return {ok:true};}});assert.equal(result.code,'REQUEST_REFUSED');}assert.equal(actualHostDispatch,0);});
test('profile final scope check cannot reentrantly revoke and deliver executable or env',async()=>{let catalogue,armed=false,checks=0,inspects=0;const {catalogue:a}=await fixture({authorize:()=>{if(armed&&++checks===2)catalogue.revoke();return true;},inspectExecutable:async p=>{if(++inspects===2)armed=true;return file(p);}});catalogue=a;await rejects(()=>a.resolveShellProfile('powershell'),'SENDER_REFUSED');});
test('profile final native guard cannot dispose and still return a usable envelope',async()=>{let catalogue,armed=false,checks=0,inspects=0;const {catalogue:a}=await fixture({captureAdmission:()=>({isCurrent:()=>{if(armed&&++checks===2)catalogue.dispose();return true;}}),inspectExecutable:async p=>{if(++inspects===2)armed=true;return file(p);}});catalogue=a;await rejects(()=>a.resolveShellProfile('powershell'),'SENDER_REFUSED');});
test('profile replacement during environment await is rechecked before returning envelope',async()=>{const {catalogue:a,state}=await fixture();state.hook=async kind=>{if(kind==='env')state.file.identity='replaced-during-env';};await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');});
test('profile concurrent discovery never accepts two different pinned native identities',async()=>{let count=0,release;const {catalogue:a,state}=await fixture({inspectExecutable:async p=>{if(++count===1){await new Promise(r=>release=r);return {...file(p),identity:'old'};}return {...file(p),identity:'new'};}});const first=a.listShellProfiles();for(let i=0;i<32&&!release;i++)await Promise.resolve();assert.equal(typeof release,'function');const second=await a.listShellProfiles();release();const old=await first;assert.equal(second[0].available,true);assert.equal(old[0].available,false);assert.equal(state.calls.filter(x=>x==='system').length,2);});
test('profile missing required OS variables or malformed private-key policy refuses',async()=>{for(const env of [{PATH:'x'},{SystemRoot:'C:\\Windows'},{PATH:'',SystemRoot:'C:\\Windows'}]){const {catalogue:a,state}=await fixture();state.env=env;await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');}const {catalogue:a}=await fixture({privateEnvironmentKeys:['BAD=NAME']});await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');});
test('profile discovery refuses native device aliases before trusting executable evidence',async()=>{for(const root of ['C:\\COM¹','C:\\LPT².txt','C:\\CONIN$','C:\\CONOUT$']){const {catalogue:a}=await fixture({getSystemDirectory:async()=>root,inspectExecutable:async p=>file(p)});await rejects(()=>a.resolveShellProfile('powershell'),'PROFILE_UNAVAILABLE');}});
test('profile malformed provider reflection never leaks private errors through list or resolve',async()=>{const hostile=new Proxy({},{getPrototypeOf(){throw Error('PRIVATE_SECRET');}});const {catalogue:a}=await fixture({inspectExecutable:async()=>hostile});assert.equal((await a.listShellProfiles())[0].available,false);await assert.rejects(()=>a.resolveShellProfile('powershell'),e=>e.code==='PROFILE_UNAVAILABLE'&&!e.message.includes('PRIVATE_SECRET'));const {catalogue:b,state}=await fixture();state.env=hostile;await assert.rejects(()=>b.resolveShellProfile('powershell'),e=>e.code==='PROFILE_UNAVAILABLE'&&!e.message.includes('PRIVATE_SECRET'));});
test('profile final executable check is fenced after its own native await',async()=>{let inspected=0;const {catalogue:a,state}=await fixture();state.hook=async type=>{if(type==='inspect'&&++inspected===2)state.generation++;};await rejects(()=>a.resolveShellProfile('powershell'),'SENDER_REFUSED');assert.equal(inspected,2);});

// P2 regression: refuse excessive ancestry BEFORE materializing prefixes.
// Real pure module in a64MiB worker; no filesystem/dialog/native execution.
test('profiles bounds path prefix expansion before malformed evidence can exhaust64MiB',async()=>{
 const workerSource=String.raw`
const {parentPort,workerData}=require('node:worker_threads'),{win32:path}=require('node:path');
(async()=>{
 const {kind,components,url,validAncestors}=workerData,selected='C:\\'+Array(components).fill('a').join('\\');
 const chain=p=>{const root=path.parse(p).root,parts=p.slice(root.length).split('\\').filter(Boolean);return [root,...parts.map((_,i)=>path.join(root,...parts.slice(0,i+1)))].map((p,i)=>({path:p,identity:'directory-'+i,directory:true,reparse:false}));};
 let observed;
 if(kind==='cwd'){
  const {CwdAuthority}=await import(url),grant={windowId:'w',projectId:'p',epoch:1,role:'workspace'};
  const inspect=p=>{const parents=chain(p);return {canonicalPath:p,identity:parents.at(-1).identity,directory:true,reparse:false,ancestors:parents};};
  const a=new CwdAuthority({protectedRoots:['D:\\Protected'],authorize:()=>true,captureAdmission:()=>({isCurrent:()=>true}),pickDirectory:()=>({canceled:false,filePaths:[selected]}),inspectDirectory:p=>p===selected&&!validAncestors?{canonicalPath:p,identity:'selected',directory:true,reparse:false,ancestors:[]}:inspect(p)});
  try{await a.pick(grant);observed={code:'GRANTED'};}catch(e){observed={code:e.code,message:e.message};}
 }else{
  const {createShellProfileCatalogue}=await import(url),a=createShellProfileCatalogue({authorize:()=>true,captureAdmission:()=>({isCurrent:()=>true}),getSystemDirectory:()=>selected,inspectExecutable:p=>({canonicalPath:p,identity:'file',file:true,reparse:false,ancestors:validAncestors?chain(path.dirname(p)):[]}),readEnvironment:()=>({SystemRoot:'C:\\Windows',PATH:'C:\\Windows\\System32'})});
  try{await a.resolveShellProfile('powershell');observed={code:'RESOLVED'};}catch(e){observed={code:e.code,message:e.message};}
 }
 parentPort.postMessage({components,pathLength:selected.length,...observed});
})().catch(e=>parentPort.postMessage({unexpected:String(e)}));`;
 const run=(components,validAncestors)=>new Promise(done=>{
  let settled=false,observed=[];const w=new Worker(workerSource,{eval:true,workerData:{kind:'profiles',components,validAncestors,url:new URL('../src/terminal/profiles.mjs',import.meta.url).href},resourceLimits:{maxOldGenerationSizeMb:64,maxYoungGenerationSizeMb:8}});
  const finish=value=>{if(settled)return;settled=true;clearTimeout(timer);done({...value,observed});};
  const timer=setTimeout(()=>{void w.terminate();finish({status:'DEADLINE'});},10000);
  w.on('message',m=>observed.push(m));w.on('error',e=>finish({status:'WORKER_ERROR',code:e.code}));w.on('exit',exitCode=>finish({status:'EXIT',exitCode}));
 });
 const cases=[[3,false],[8192,false],[125,true],[126,true]],expected=["PROFILE_UNAVAILABLE","PROFILE_UNAVAILABLE","RESOLVED","PROFILE_UNAVAILABLE"];
 for(let i=0;i<cases.length;i++){const result=await run(...cases[i]);assert.equal(result.status,'EXIT',JSON.stringify(result));assert.equal(result.exitCode,0);assert.equal(result.observed.length,1);assert.equal(result.observed[0].code,expected[i],JSON.stringify(result));}
});
