// Local reference content. No article grants execution, write or recovery authority.
export const HELP_CATALOG_VERSION=1;
const categories=new Set(['general','projects','sources','docs','diagrams','present','windows','pin','recovery','updates','terminal']);
const identifier=v=>typeof v==='string'&&/^[a-z][a-z0-9-]{0,79}$/.test(v);
const prose=(v,max)=>typeof v==='string'&&v.length>0&&v.length<=max&&!/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(v);
const data=(value,keys)=>{
 if(!value||typeof value!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(value)))return false;
 const own=Reflect.ownKeys(value);return own.length===keys.length&&own.every(k=>{if(typeof k!=='string'||!keys.includes(k))return false;const d=Object.getOwnPropertyDescriptor(value,k);return d.enumerable===true&&Object.hasOwn(d,'value');});
};
const array=(value,max,check)=>Array.isArray(value)&&Object.getPrototypeOf(value)===Array.prototype&&value.length<=max&&Reflect.ownKeys(value).length===value.length+1&&Array.from({length:value.length},(_,i)=>{const d=Object.getOwnPropertyDescriptor(value,String(i));return !!d&&Object.hasOwn(d,'value')&&check(d.value);}).every(Boolean);
export function freezeHelpData(value){if(value&&typeof value==='object'){for(const v of Object.values(value))freezeHelpData(v);Object.freeze(value);}return value;}
function validFlow(flow){
 if(flow===null)return true;
 if(!data(flow,['nodes','edges'])||!array(flow.nodes,24,n=>data(n,['id','type','label'])&&identifier(n.id)&&['decision','check','outcome'].includes(n.type)&&prose(n.label,600))||flow.nodes.length===0||!array(flow.edges,48,e=>data(e,['from','to','label'])&&identifier(e.from)&&identifier(e.to)&&prose(e.label,160)))return false;
 const ids=new Set(flow.nodes.map(n=>n.id));if(ids.size!==flow.nodes.length)return false;
 const edges=new Set(),next=new Map([...ids].map(id=>[id,[]])),degree=new Map([...ids].map(id=>[id,0]));
 for(const e of flow.edges){const key=e.from+'\0'+e.to;if(!ids.has(e.from)||!ids.has(e.to)||edges.has(key))return false;edges.add(key);next.get(e.from).push(e.to);degree.set(e.to,degree.get(e.to)+1);}
 const queue=[...ids].filter(id=>degree.get(id)===0);let visited=0;
 for(let i=0;i<queue.length;i++){visited++;for(const id of next.get(queue[i])){degree.set(id,degree.get(id)-1);if(degree.get(id)===0)queue.push(id);}}
 if(visited!==ids.size||queue[0]!==flow.nodes[0].id)return false;
 const reachable=new Set([flow.nodes[0].id]),pending=[flow.nodes[0].id];for(let i=0;i<pending.length;i++)for(const id of next.get(pending[i]))if(!reachable.has(id)){reachable.add(id);pending.push(id);}
 return reachable.size===ids.size;
}
export function validateHelpCatalog(articles){
 const fail=()=>Object.freeze({ok:false,code:'INVALID_HELP_CATALOG'});
 try{
  const ids=new Set(),mappings=new Set();
  if(!array(articles,64,a=>{
   const keys=['id','category','title','summary','observed','causes','checks','recovery','dataImpact','technical','sources','related','mappings','flow'];
   if(!data(a,keys)||!identifier(a.id)||ids.has(a.id)||!categories.has(a.category)||!prose(a.title,160)||!prose(a.summary,600)||!['observed','causes','checks','recovery','dataImpact','technical'].every(k=>prose(a[k],4000)))return false;
   ids.add(a.id);
   if(!array(a.sources,16,p=>typeof p==='string'&&/^src\/(?:[a-z0-9-]+\/)*[a-z0-9-]+\.(?:mjs|js|cjs)$/.test(p))||!a.sources.length||!array(a.related,16,identifier)||!validFlow(a.flow))return false;
   return array(a.mappings,32,m=>{if(!data(m,['namespace','operation','code'])||!identifier(m.namespace)||!identifier(m.operation)||typeof m.code!=='string'||!/^[A-Z][A-Z0-9_]{0,95}$/.test(m.code))return false;const key=[m.namespace,m.operation,m.code].join('\0');if(mappings.has(key))return false;mappings.add(key);return true;});
  })||!ids.has('unknown-error')||!articles.every(a=>a.related.every(id=>id!==a.id&&ids.has(id))))return fail();
  return Object.freeze({ok:true});
 }catch{return fail();}
}
const maps=(namespace,operation,codes)=>codes.split(' ').filter(Boolean).map(code=>({namespace,operation,code}));
const article=(id,category,title,summary,sources,mappings,details={})=>({id,category,title,summary,observed:summary,causes:'The receipt alone does not identify the exact cause.',checks:'Keep the current work and inspect the affected operation before retrying.',recovery:'Use the existing SIREN controls. Do not remove project or recovery files to bypass this result.',dataImpact:'An unsuccessful receipt does not prove that no write occurred. Check the saved state before repeating a change.',technical:'This explanation covers the named SIREN operation only, not arbitrary dependency exceptions.',sources,related:['unknown-error'],mappings,flow:null,...details});
const conflictFlow={nodes:[{id:'start',type:'check',label:'Keep this draft open.'},{id:'saved',type:'decision',label:'Can you inspect the latest saved version separately?'},{id:'compare',type:'check',label:'Compare the saved version with your retained draft.'},{id:'retain',type:'outcome',label:'Keep both versions until you decide what to save.'}],edges:[{from:'start',to:'saved',label:'Continue'},{from:'saved',to:'compare',label:'Yes'},{from:'saved',to:'retain',label:'Not yet'},{from:'compare',to:'retain',label:'Review complete'}]};
const articles=[
 article('unknown-error','general','An error without a known explanation','SIREN cannot identify the exact cause from this error identity.',['src/ipc.mjs'],[],{related:[],checks:'Keep the visible message and note which operation you were using. Do not paste private source, credentials or full logs into a public report.',recovery:'Inspect the affected work and use the relevant manual category. If the problem repeats, report the operation and bounded error code without private content.'}),
 article('appearance-unavailable','general','Theme change unavailable','The requested theme change was refused or could not be confirmed.',['src/ui/shared/shell.js','src/appearance/ipc.mjs'],maps('appearance','choose','ACCESS_REFUSED INVALID_APPEARANCE APPEARANCE_WRITE_FAILED OPERATION_FAILED REQUEST_REFUSED'),{checks:'Wait for the current workspace transition to finish. Check which theme is actually selected before trying again.',dataImpact:'The previous preference may have been retained. An error message alone does not establish the active theme.'}),
 article('project-save','projects','Project save conflict','The current save does not match the accepted project revision, or saving was not confirmed.',['src/projects/store.mjs'],maps('project','save','REVISION_CONFLICT WRITER_BUSY SAVE_FAILED SCHEMA_UNSUPPORTED'),{checks:'Keep unsaved work. Inspect the latest saved project or available recovery copy before deciding what to retain.',recovery:'Wait if another save is running. Preserve or export your work using existing controls; never change the stored revision or schema to force a save.',flow:conflictFlow}),
 article('source-import','sources','Source import limits and encoding','Source import requires accepted UTF-8 content within the current source budget.',['src/navigation/source-import.mjs'],maps('sources','import','SOURCE_BUDGET UNSUPPORTED_ENCODING SOURCE_IMPORT_FAILED'),{checks:'Check the file encoding and size. The current single-source import limit is 32 MiB; it is a byte budget, not a line count.',recovery:'Keep the original file. Save a separate UTF-8 copy if needed; do not silently truncate a complex script.',dataImpact:'An import failure does not classify the code as invalid or prove that every partial import artifact was removed.'}),
 article('source-integrity','sources','Stored source integrity','The stored source or its readback did not satisfy SIREN integrity checks.',['src/sources/repository.mjs'],maps('sources','read','CORRUPT_SOURCE SOURCE_READBACK_FAILED SOURCE_PROOF_FAILED IMMUTABLE_CONFLICT'),{recovery:'Keep the original and any verified copies. Use recovery or import a separate trusted copy when available. Never edit hashes or replace stored blobs to bypass verification.'}),
 article('code-version-conflict','sources','Code version conflict','The edit refers to a different source version or operation than the accepted one.',['src/sources/repository.mjs','src/sources/text-model.mjs'],maps('sources','save','REVISION_CONFLICT OPERATION_CONFLICT OPERATION_ID_REUSE SOURCE_MISMATCH VERSION_EXHAUSTED'),{checks:'Retain your draft. Open the latest saved version separately and compare the exact versions.',recovery:'Use explicit save/replace controls only after reviewing both versions. SIREN does not automatically merge arbitrary source changes.',flow:conflictFlow}),
 article('document-change','docs','Document change not accepted','A document change, version or reference did not satisfy the current domain checks.',['src/windows/domain.mjs'],maps('docs','save','DOMAIN_VALIDATION_FAILED DOCUMENT_CONFLICT DOMAIN_VERSION_CHANGED REFERENCE_TARGET_REFUSED UNKNOWN_SOURCE_REFERENCE'),{recovery:'Retain the draft and inspect saved references or another saved version separately. Do not delete unfamiliar imported content to force validation.'}),
 article('diagram-change','diagrams','Diagram change not accepted','A diagram change does not match the current accepted document or version.',['src/windows/domain.mjs'],maps('diagram','save','DOMAIN_VALIDATION_FAILED DOCUMENT_CONFLICT DOMAIN_VERSION_CHANGED'),{checks:'Keep the draft and inspect the latest saved diagram before retrying.',flow:conflictFlow}),
 article('diagram-render','diagrams','A diagram preview cannot render','The preview did not render; this message alone does not identify a syntax error or the exact cause.',['src/ui/windows/diagram.js','src/ui/workspace/guide.js'],[],{checks:'Keep the Mermaid source. Check the selected diagram type and any specific validation message. Current desktop Guided/preview rendering is bounded to 50,000 characters.',recovery:'Inspect the source using Text or supported Guided controls. Build interaction varies by diagram type; not every Mermaid family supports mouse editing.',dataImpact:'The preview is distinct from a saved diagram. Inspect the saved state rather than treating a rendering failure as deletion.'}),
 article('analysis-coverage','sources','Python analysis and coverage','An analysis may be busy, unsupported, partial, cancelled or limited by its budget.',['src/windows/source-analysis.mjs','src/sources/analysis.mjs'],maps('sources','analyze','ANALYSIS_BUSY LANGUAGE_NOT_SUPPORTED'),{checks:'Read the reported status and coverage. Save the source before analysis and use a selected range when appropriate.',recovery:'Wait for or cancel the current analysis through its existing controls. Do not bypass worker identity checks.',dataImpact:'Static analysis does not execute Python and does not certify that a script runs correctly.'}),
 article('diagram-export-unavailable','diagrams','Saved SVG export unavailable','The saved SVG export was refused, changed version, was busy or could not be confirmed.',['src/windows/diagram-export.mjs'],maps('diagram','export','ACCESS_REFUSED EXPORT_BUSY EXPORT_CHANGED DIAGRAM_VERSION_CHANGED SVG_RENDER_REFUSED SVG_EXPORT_FAILED'),{checks:'Save local diagram changes first. Check that the saved version is still current and that another export is not running.',recovery:'Use the saved export and Show file controls when a receipt exists. Inspect the destination before retrying an unconfirmed export.',dataImpact:'Vector export uses the saved diagram, not preview pan/zoom. An error alone does not prove that no destination file exists.'}),
 article('docs-export','docs','Document export unavailable','The saved document export could not be accepted or confirmed.',['src/windows/docs-export.mjs'],maps('docs','export','EXPORT_BUSY EXPORT_CHANGED DOCUMENT_VERSION_CHANGED DOCS_EXPORT_FAILED'),{checks:'Check the saved document version and retain any current draft. Inspect an existing export before retrying.'}),
 article('backup-saved-transition','projects','Backup saved before access changed','The backup was committed before access changed; the final receipt no longer has the original access scope.',['src/navigation/backup-export.mjs'],maps('project','backup','EXPORT_COMMITTED'),{checks:'Inspect the destination you explicitly selected for the backup.',recovery:'Keep the committed backup. Do not assume that a second export is needed just because the final result was not a normal success.',dataImpact:'This code means a backup was saved. It must not be interpreted as no file was created.'}),
 article('backup-unavailable','projects','Backup export unavailable','The backup was cancelled, over budget, unavailable or its destination write was not confirmed.',['src/navigation/backup-export.mjs'],maps('project','backup','BACKUP_BUDGET BACKUP_UNAVAILABLE BACKUP_WRITE_FAILED CANCELLED'),{checks:'A backup has a 64 MiB budget. Cancellation is not a diagnosis of corrupted content. If writing was not confirmed, inspect the selected destination before retrying.'}),
 article('unfinished-edit','windows','Finish the current edit before leaving','A pending field or an unconfirmed save/flush can prevent a coordinated transition.',['src/ui/windows/diagram.js','src/windows/coordinator.mjs'],maps('workspace','transition','INSPECTOR_EDIT_PENDING GUIDED_EDIT_PENDING SOURCE_FLUSH_FAILED WORKSPACE_FLUSH_FAILED'),{checks:'Finish or cancel tentative Guided, Build or Style fields. Keep the draft if saving did not finish.',recovery:'Retry Lock/Close only after resolving the pending operation. A refusal is not confirmation that all windows are already locked.'}),
 article('pin-access','pin','PIN access and cooldown','The PIN operation was refused, the PIN was incorrect or an attempt cooldown is active.',['src/account/local-pin.mjs'],maps('pin','unlock','WRONG_PIN INVALID_PIN PIN_COOLDOWN PIN_NOT_CONFIGURED PIN_LOCKED'),{checks:'Use the displayed attempt/cooldown information. Do not assume a fixed waiting time from the code alone.',recovery:'Use the normal PIN controls when available. Do not delete protection files or bypass Lock.',dataImpact:'A PIN refusal does not diagnose loss of project data.'}),
 article('pin-storage','pin','Protected PIN storage unavailable','SIREN could not use the required protected local PIN storage.',['src/account/local-pin.mjs'],maps('pin','change','PIN_STORAGE_UNAVAILABLE'),{recovery:'Keep the protected files and existing data. The code alone does not prove that the PIN was forgotten or that a key was lost.'}),
 article('safe-recovery','recovery','Read-only and recovery startup','SIREN may start read-only or in recovery when startup or ownership checks cannot be confirmed.',['src/recovery/sessions.mjs','src/recovery/processes.mjs','src/ui/desktop.js'],[],{checks:'Read the actual startup reason and inspect verified recovery copies. Read-only and recovery are modes, not a diagnosis of one damaged project.',recovery:'Use Open recovered copy or export controls when offered. An exported damaged original is not a verified recovery point.',dataImpact:'Keep the original. The manual does not repair or clean recovery files automatically.'}),
 article('updates-unavailable','updates','Updates unavailable in this build','An update or installation step may be unconfigured or not yet qualified in this development build.',['src/main.mjs','src/ui/workspace/home.js'],maps('updates','install','HELPER_NOT_QUALIFIED'),{checks:'Check the build update status. Unconfigured does not mean an update download failed.',recovery:'Use Check for updates only when configured. Do not substitute an unsigned package or bypass helper qualification.'}),
 article('terminal-unavailable','terminal','Terminal execution not qualified','The current development work includes pure Terminal components; native shell ownership and execution remain unqualified.',['src/terminal/policy.mjs','src/terminal/session-state.mjs'],[],{checks:'Distinguish a documented planned feature from a working shell in the current build.',recovery:'Do not diagnose PowerShell or install dependencies from this status. Native ownership qualification is a separate development requirement.',dataImpact:'The manual does not start a shell, debugger or imported script.'}),
 article('diagram-created-not-opened','diagrams','Diagram created but not opened','A diagram may have been saved even though opening its editor was unavailable.',['src/windows/diagram-catalogue.mjs','src/ui/diagram/catalogue-view.js'],maps('catalogue','open','OPEN_UNAVAILABLE ENTITY_REFUSED'),{checks:'Inspect the creation result separately from the opening result.',recovery:'Use Retry opening saved diagram when available, retaining the same operation. Keep the saved result and inspect it before another creation.',dataImpact:'An opening failure does not cancel a successful diagram creation.'}),
];
if(!validateHelpCatalog(articles).ok)throw Error('INVALID_HELP_CATALOG');
export const HELP_ARTICLES=freezeHelpData(articles);
